import type { components as Bil } from './generated/bil';
import type { components as Clm } from './generated/clm';
import type { components as Fin } from './generated/fin';
import type { components as Pfc } from './generated/pfc';
import type { components as Plt } from './generated/plt';
import type { components as Pol } from './generated/pol';
import type { components as Pty } from './generated/pty';

/** Named schema types of the OpenAPI contracts (generated by `npm run gen:contracts`). */

// Party (pty.yaml)
export type PartyView = Pty['schemas']['PartyView'];
export type PartyCreateRequest = Pty['schemas']['PartyCreateRequest'];
export type PartyCreateResponse = Pty['schemas']['PartyCreateResponse'];
export type PartySearchCriteria = Pty['schemas']['PartySearchCriteria'];
export type PartySearchPage = Pty['schemas']['PartySearchPage'];
export type PartySearchItem = Pty['schemas']['PartySearchItem'];
export type PartyGetResponse = Pty['schemas']['PartyGetResponse'];

// Product (pfc.yaml)
export type ProductVersionResolveRequest = Pfc['schemas']['ProductVersionResolveRequest'];
export type ProductVersionResolveResponse = Pfc['schemas']['ProductVersionResolveResponse'];
export type CatalogueGetResponse = Pfc['schemas']['CatalogueGetResponse'];
export type CatalogueCoverage = Pfc['schemas']['CatalogueCoverage'];
export type QuestionSetGetResponse = Pfc['schemas']['QuestionSetGetResponse'];
export type Question = Pfc['schemas']['Question'];
export type QuestionSetEvaluateResponse = Pfc['schemas']['QuestionSetEvaluateResponse'];

// Policy (pol.yaml)
export type SubmissionCreateRequest = Pol['schemas']['SubmissionCreateRequest'];
export type SubmissionCreateResponse = Pol['schemas']['SubmissionCreateResponse'];
export type JobUpdateDraftRequest = Pol['schemas']['JobUpdateDraftRequest'];
export type JobUpdateDraftResponse = Pol['schemas']['JobUpdateDraftResponse'];
export type DraftInstruction = Pol['schemas']['DraftInstruction'];
export type JobQuoteResponse = Pol['schemas']['JobQuoteResponse'];
export type JobBindRequest = Pol['schemas']['JobBindRequest'];
export type JobBindResponse = Pol['schemas']['JobBindResponse'];
export type ChargeLine = Pol['schemas']['ChargeLine'];
export type UwIssue = Pol['schemas']['UwIssue'];
export type PolicyGetResponse = Pol['schemas']['PolicyGetResponse'];
export type TermStateCode = Pol['schemas']['TermStateCode'];
export type Money = Pol['schemas']['Money'];

// Billing (bil.yaml)
export type BillingAccountGetResponse = Bil['schemas']['BillingAccountGetResponse'];
export type InvoiceGetResponse = Bil['schemas']['InvoiceGetResponse'];
export type InvoiceView = Bil['schemas']['InvoiceView'];
export type InvoiceListPage = Bil['schemas']['InvoiceListPage'];
export type InvoiceFiscalStatus = Bil['schemas']['InvoiceFiscalStatus'];
export type PaymentTakeRequest = Bil['schemas']['PaymentTakeRequest'];
export type PaymentTakeResponse = Bil['schemas']['PaymentTakeResponse'];

// Finance (fin.yaml)
export type JournalQueryPage = Fin['schemas']['JournalQueryPage'];
export type JournalView = Fin['schemas']['JournalView'];

// Policy search (pol.yaml)
export type PolicySearchCriteria = Pol['schemas']['PolicySearchCriteria'];
export type PolicySearchPage = Pol['schemas']['PolicySearchPage'];
export type PolicySearchItem = Pol['schemas']['PolicySearchItem'];

// Payee accounts (bil.yaml)
export type PayeeAccountCreateRequest = Bil['schemas']['PayeeAccountCreateRequest'];
export type PayeeAccountCreateResponse = Bil['schemas']['PayeeAccountCreateResponse'];

// Claims (clm.yaml)
export type FnolSubmitRequest = Clm['schemas']['FnolSubmitRequest'];
export type FnolSubmitResponse = Clm['schemas']['FnolSubmitResponse'];
export type FnolValidateRequest = Clm['schemas']['FnolValidateRequest'];
export type FnolValidateResponse = Clm['schemas']['FnolValidateResponse'];
export type FnolIssue = Clm['schemas']['FnolIssue'];
export type DuplicateCandidate = Clm['schemas']['DuplicateCandidate'];
export type DuplicateDecision = Clm['schemas']['DuplicateDecision'];
export type CoverageIndication = Clm['schemas']['CoverageIndication'];
export type ClaimSummary = Clm['schemas']['ClaimSummary'];
export type ClaimView = Clm['schemas']['ClaimView'];
export type ClaimGetResponse = Clm['schemas']['ClaimGetResponse'];
export type ClaimSearchCriteria = Clm['schemas']['ClaimSearchCriteria'];
export type ClaimSearchPage = Clm['schemas']['ClaimSearchPage'];
export type ClaimCloseRequest = Clm['schemas']['ClaimCloseRequest'];
export type ClaimCloseResponse = Clm['schemas']['ClaimCloseResponse'];
export type ExposureView = Clm['schemas']['ExposureView'];
export type ExposureKind = Clm['schemas']['ExposureKind'];
export type ExposureCreateRequest = Clm['schemas']['ExposureCreateRequest'];
export type ExposureCreateResponse = Clm['schemas']['ExposureCreateResponse'];

// Approvals (plt.yaml)
export type ApprovalView = Plt['schemas']['ApprovalView'];
export type ApprovalDecisionView = Plt['schemas']['ApprovalDecisionView'];
export type ApprovalGetResponse = Plt['schemas']['ApprovalGetResponse'];
export type ApprovalListPage = Plt['schemas']['ApprovalListPage'];
export type ApprovalDecideRequest = Plt['schemas']['ApprovalDecideRequest'];
export type ApprovalDecideResponse = Plt['schemas']['ApprovalDecideResponse'];
