// <auto-generated />
using System;
using CoreIns.Modules.Compliance.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CoreIns.Modules.Compliance.Persistence.Migrations
{
    [DbContext(typeof(ComplianceDbContext))]
    partial class ComplianceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("cmp")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CoreIns.Modules.Compliance.Persistence.FiscalDocumentRow", b =>
                {
                    b.Property<Guid>("FiscalDocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("fiscal_document_id");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("channel");

                    b.Property<Guid?>("CorrelatedDocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlated_document_id");

                    b.Property<Guid>("CounterpartyPartyId")
                        .HasColumnType("uuid")
                        .HasColumnName("counterparty_party_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("char(3)")
                        .HasColumnName("currency");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("document_type");

                    b.Property<bool>("DocumentTypeIsPlaceholder")
                        .HasColumnType("boolean")
                        .HasColumnName("document_type_is_placeholder");

                    b.Property<DateOnly>("IssueDate")
                        .HasColumnType("date")
                        .HasColumnName("issue_date");

                    b.Property<string>("Jurisdiction")
                        .IsRequired()
                        .HasColumnType("char(2)")
                        .HasColumnName("jurisdiction");

                    b.Property<Guid>("LegalEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("legal_entity_id");

                    b.Property<string>("Lines")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("lines");

                    b.Property<string>("Mark")
                        .HasColumnType("text")
                        .HasColumnName("mark");

                    b.Property<string>("Number")
                        .HasColumnType("text")
                        .HasColumnName("number");

                    b.Property<string>("QrPayloadRef")
                        .HasColumnType("text")
                        .HasColumnName("qr_payload_ref");

                    b.Property<int>("RecordVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("record_version");

                    b.Property<DateTime?>("RegisteredAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("registered_at");

                    b.PrimitiveCollection<string[]>("RejectionCodes")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("rejection_codes");

                    b.Property<int>("Revision")
                        .HasColumnType("integer")
                        .HasColumnName("revision");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<string>("Series")
                        .HasColumnType("text")
                        .HasColumnName("series");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_id");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_type");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<bool>("Stub")
                        .HasColumnType("boolean")
                        .HasColumnName("stub");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("total");

                    b.Property<string>("Uid")
                        .HasColumnType("text")
                        .HasColumnName("uid");

                    b.HasKey("FiscalDocumentId")
                        .HasName("pk_fiscal_document");

                    b.HasIndex("LegalEntityId", "Series", "Number")
                        .IsUnique()
                        .HasDatabaseName("ux_fiscal_document_number");

                    b.HasIndex("LegalEntityId", "SourceType", "SourceId", "Role", "Revision")
                        .IsUnique()
                        .HasDatabaseName("ux_fiscal_document_source");

                    b.ToTable("fiscal_document", "cmp", t =>
                        {
                            t.HasCheckConstraint("ck_fiscal_document_currency", "currency ~ '^[A-Z]{3}$'");

                            t.HasCheckConstraint("ck_fiscal_document_record_version", "record_version >= 1");

                            t.HasCheckConstraint("ck_fiscal_document_registered", "status <> 'REGISTERED' OR (mark IS NOT NULL AND uid IS NOT NULL)");

                            t.HasCheckConstraint("ck_fiscal_document_revision", "revision >= 0");

                            t.HasCheckConstraint("ck_fiscal_document_role", "role IN ('ISSUE', 'CREDIT', 'CANCELLATION')");

                            t.HasCheckConstraint("ck_fiscal_document_status", "status IN ('PENDING', 'REGISTERED', 'REJECTED')");
                        });
                });

            modelBuilder.Entity("CoreIns.Modules.Compliance.Persistence.FiscalSeriesRow", b =>
                {
                    b.Property<Guid>("LegalEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("legal_entity_id");

                    b.Property<string>("SeriesId")
                        .HasColumnType("text")
                        .HasColumnName("series_id");

                    b.Property<long>("LastNumber")
                        .HasColumnType("bigint")
                        .HasColumnName("last_number");

                    b.HasKey("LegalEntityId", "SeriesId")
                        .HasName("pk_fiscal_series");

                    b.ToTable("fiscal_series", "cmp", t =>
                        {
                            t.HasCheckConstraint("ck_fiscal_series_last", "last_number >= 0");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
