// <auto-generated />
using System;
using System.Text.Json;
using CoreIns.Modules.Claims.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CoreIns.Modules.Claims.Persistence.Migrations
{
    [DbContext(typeof(ClaimsDbContext))]
    [Migration("20261009171616_RecoveryMoney")]
    partial class RecoveryMoney
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("clm")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CoreIns.Modules.Claims.Persistence.ClaimPaymentRow", b =>
                {
                    b.Property<Guid>("ClaimPaymentId")
                        .HasColumnType("uuid")
                        .HasColumnName("claim_payment_id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("amount");

                    b.Property<string>("ApprovalEvidenceRef")
                        .HasColumnType("text")
                        .HasColumnName("approval_evidence_ref");

                    b.Property<Guid>("ClaimId")
                        .HasColumnType("uuid")
                        .HasColumnName("claim_id");

                    b.Property<DateTime?>("ClearedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("cleared_at");

                    b.Property<Guid?>("CounterpartyInsurerPartyId")
                        .HasColumnType("uuid")
                        .HasColumnName("counterparty_insurer_party_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("char(3)")
                        .HasColumnName("currency");

                    b.Property<string>("DisbursementContentHash")
                        .IsRequired()
                        .HasColumnType("char(64)")
                        .HasColumnName("disbursement_content_hash");

                    b.Property<Guid?>("DisbursementId")
                        .HasColumnType("uuid")
                        .HasColumnName("disbursement_id");

                    b.Property<Guid>("ExposureId")
                        .HasColumnType("uuid")
                        .HasColumnName("exposure_id");

                    b.Property<string>("FiscalMark")
                        .HasColumnType("text")
                        .HasColumnName("fiscal_mark");

                    b.Property<Guid?>("FsStatementId")
                        .HasColumnType("uuid")
                        .HasColumnName("fs_statement_id");

                    b.Property<string>("HoldReason")
                        .HasColumnType("text")
                        .HasColumnName("hold_reason");

                    b.Property<DateTime?>("IssuedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("issued_at");

                    b.Property<string>("Jurisdiction")
                        .IsRequired()
                        .HasColumnType("char(2)")
                        .HasColumnName("jurisdiction");

                    b.Property<Guid>("LegalEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("legal_entity_id");

                    b.Property<string>("MaskedAccount")
                        .HasColumnType("text")
                        .HasColumnName("masked_account");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("method");

                    b.Property<Guid>("PayeeAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("payee_account_id");

                    b.Property<Guid>("PayeePartyId")
                        .HasColumnType("uuid")
                        .HasColumnName("payee_party_id");

                    b.Property<string>("PaymentType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payment_type");

                    b.Property<int>("RecordVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("record_version");

                    b.Property<Guid?>("ReissueOf")
                        .HasColumnType("uuid")
                        .HasColumnName("reissue_of");

                    b.Property<Guid?>("ReversalOf")
                        .HasColumnType("uuid")
                        .HasColumnName("reversal_of");

                    b.Property<Guid>("SetId")
                        .HasColumnType("uuid")
                        .HasColumnName("set_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("submitted_at");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("ClaimPaymentId")
                        .HasName("pk_claim_payment");

                    b.HasIndex("ClaimId")
                        .HasDatabaseName("ix_claim_payment_claim");

                    b.HasIndex("DisbursementId")
                        .IsUnique()
                        .HasDatabaseName("ux_claim_payment_disbursement")
                        .HasFilter("disbursement_id IS NOT NULL");

                    b.HasIndex("ExposureId");

                    b.HasIndex("ReissueOf")
                        .IsUnique()
                        .HasDatabaseName("ux_claim_payment_reissue")
                        .HasFilter("reissue_of IS NOT NULL");

                    b.HasIndex("ReversalOf");

                    b.HasIndex("SetId")
                        .HasDatabaseName("ix_claim_payment_set");

                    b.ToTable("claim_payment", "clm", t =>
                        {
                            t.HasCheckConstraint("ck_claim_payment_amount", "amount > 0");

                            t.HasCheckConstraint("ck_claim_payment_clearing", "method <> 'CLEARING' OR disbursement_id IS NULL");

                            t.HasCheckConstraint("ck_claim_payment_clearing_counterparty", "method <> 'CLEARING' OR counterparty_insurer_party_id IS NOT NULL");

                            t.HasCheckConstraint("ck_claim_payment_hold_shape", "status <> 'ON_HOLD' OR hold_reason IS NOT NULL");

                            t.HasCheckConstraint("ck_claim_payment_jurisdiction", "jurisdiction ~ '^[A-Z]{2}$'");

                            t.HasCheckConstraint("ck_claim_payment_record_version", "record_version >= 1");

                            t.HasCheckConstraint("ck_claim_payment_status", "status IN ('PENDING', 'APPROVED', 'ON_HOLD', 'SUBMITTED', 'ISSUED', 'CLEARED', 'REJECTED')");

                            t.HasCheckConstraint("ck_claim_payment_submitted_shape", "status NOT IN ('SUBMITTED', 'ISSUED', 'CLEARED') OR disbursement_id IS NOT NULL OR (method = 'CLEARING' AND fs_statement_id IS NOT NULL)");

                            t.HasCheckConstraint("ck_claim_payment_type", "payment_type IN ('PARTIAL', 'FINAL')");
                        });
                });

            modelBuilder.Entity("CoreIns.Modules.Claims.Persistence.ClaimRow", b =>
                {
                    b.Property<Guid>("ClaimId")
                        .HasColumnType("uuid")
                        .HasColumnName("claim_id");

                    b.Property<bool?>("AccidentInGreece")
                        .HasColumnType("boolean")
                        .HasColumnName("accident_in_greece");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("channel");

                    b.Property<string>("ClaimNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("claim_number");

                    b.Property<string>("CloseReasonCode")
                        .HasColumnType("text")
                        .HasColumnName("close_reason_code");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("closed_at");

                    b.Property<Guid?>("CounterpartyInsurerPartyId")
                        .HasColumnType("uuid")
                        .HasColumnName("counterparty_insurer_party_id");

                    b.Property<bool>("CoverageInQuestion")
                        .HasColumnType("boolean")
                        .HasColumnName("coverage_in_question");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<byte[]>("DescriptionEncrypted")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("description_encrypted");

                    b.Property<Guid?>("DuplicateOfClaimId")
                        .HasColumnType("uuid")
                        .HasColumnName("duplicate_of_claim_id");

                    b.Property<string>("DuplicateReasonCode")
                        .HasColumnType("text")
                        .HasColumnName("duplicate_reason_code");

                    b.Property<decimal?>("FaultInsuredPct")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("fault_insured_pct");

                    b.Property<string>("FaultSource")
                        .HasColumnType("text")
                        .HasColumnName("fault_source");

                    b.Property<string>("Handler")
                        .HasColumnType("text")
                        .HasColumnName("handler");

                    b.Property<string>("HandlingSegment")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("handling_segment");

                    b.Property<Guid>("InsuredPartyId")
                        .HasColumnType("uuid")
                        .HasColumnName("insured_party_id");

                    b.Property<bool?>("JointAccidentReport")
                        .HasColumnType("boolean")
                        .HasColumnName("joint_accident_report");

                    b.Property<string>("Jurisdiction")
                        .IsRequired()
                        .HasColumnType("char(2)")
                        .HasColumnName("jurisdiction");

                    b.Property<int>("LastExposureSequence")
                        .HasColumnType("integer")
                        .HasColumnName("last_exposure_sequence");

                    b.Property<int>("LastTransactionSequence")
                        .HasColumnType("integer")
                        .HasColumnName("last_transaction_sequence");

                    b.Property<Guid>("LegalEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("legal_entity_id");

                    b.Property<string>("LineOfBusiness")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("line_of_business");

                    b.Property<DateTime>("LossAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("loss_at");

                    b.Property<string>("LossCause")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("loss_cause");

                    b.Property<DateOnly>("LossDate")
                        .HasColumnType("date")
                        .HasColumnName("loss_date");

                    b.Property<byte[]>("LossLocationEncrypted")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("loss_location_encrypted");

                    b.Property<DateOnly>("NoticeOn")
                        .HasColumnType("date")
                        .HasColumnName("notice_on");

                    b.Property<string>("Outcome")
                        .HasColumnType("text")
                        .HasColumnName("outcome");

                    b.Property<Guid>("PolicyId")
                        .HasColumnType("uuid")
                        .HasColumnName("policy_id");

                    b.Property<bool>("PolicyInForceAtLoss")
                        .HasColumnType("boolean")
                        .HasColumnName("policy_in_force_at_loss");

                    b.Property<string>("PolicyNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("policy_number");

                    b.Property<string>("PolicyStatusAtLoss")
                        .HasColumnType("text")
                        .HasColumnName("policy_status_at_loss");

                    b.Property<Guid?>("PolicyTermId")
                        .HasColumnType("uuid")
                        .HasColumnName("policy_term_id");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("product_code");

                    b.Property<string>("ProductVersion")
                        .HasColumnType("text")
                        .HasColumnName("product_version");

                    b.Property<string>("ReceiptMedium")
                        .HasColumnType("text")
                        .HasColumnName("receipt_medium");

                    b.Property<int>("RecordVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("record_version");

                    b.Property<int>("ReopenCount")
                        .HasColumnType("integer")
                        .HasColumnName("reopen_count");

                    b.PrimitiveCollection<string[]>("SnapshotCoverageCodes")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("snapshot_coverage_codes");

                    b.Property<DateTime>("SnapshotKnownAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("snapshot_known_at");

                    b.Property<string>("SnapshotRef")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("snapshot_ref");

                    b.Property<Guid?>("SnapshotSegmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("snapshot_segment_id");

                    b.Property<string>("SnapshotStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("snapshot_status");

                    b.Property<DateTime>("SnapshotValidAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("snapshot_valid_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("SubStatus")
                        .HasColumnType("text")
                        .HasColumnName("sub_status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<int?>("VehicleCount")
                        .HasColumnType("integer")
                        .HasColumnName("vehicle_count");

                    b.HasKey("ClaimId")
                        .HasName("pk_claim");

                    b.HasIndex("DuplicateOfClaimId");

                    b.HasIndex("LegalEntityId", "ClaimNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_claim_number");

                    b.HasIndex("LegalEntityId", "InsuredPartyId")
                        .HasDatabaseName("ix_claim_insured_party");

                    b.HasIndex("LegalEntityId", "PolicyNumber")
                        .HasDatabaseName("ix_claim_policy_number");

                    b.HasIndex("LegalEntityId", "PolicyId", "LossDate")
                        .HasDatabaseName("ix_claim_policy_loss_date");

                    b.ToTable("claim", "clm", t =>
                        {
                            t.HasCheckConstraint("ck_claim_closed_shape", "status <> 'CLOSED' OR (sub_status IS NULL AND outcome IS NOT NULL AND closed_at IS NOT NULL)");

                            t.HasCheckConstraint("ck_claim_exposure_sequence", "last_exposure_sequence >= 0");

                            t.HasCheckConstraint("ck_claim_fault_pct", "fault_insured_pct IS NULL OR fault_insured_pct BETWEEN 0 AND 100");

                            t.HasCheckConstraint("ck_claim_jurisdiction", "jurisdiction ~ '^[A-Z]{2}$'");

                            t.HasCheckConstraint("ck_claim_notice_after_loss", "notice_on >= loss_date");

                            t.HasCheckConstraint("ck_claim_open_shape", "status <> 'OPEN' OR (sub_status IS NOT NULL AND outcome IS NULL AND closed_at IS NULL)");

                            t.HasCheckConstraint("ck_claim_outcome", "outcome IS NULL OR outcome IN ('COMPLETED', 'DENIED', 'WITHDRAWN', 'DUPLICATE', 'NO_PAYMENT')");

                            t.HasCheckConstraint("ck_claim_record_version", "record_version >= 1");

                            t.HasCheckConstraint("ck_claim_snapshot_status", "snapshot_status IN ('PENDING', 'VERIFIED', 'REVERIFICATION_REQUIRED')");

                            t.HasCheckConstraint("ck_claim_status", "status IN ('DRAFT', 'OPEN', 'CLOSED')");

                            t.HasCheckConstraint("ck_claim_sub_status", "sub_status IS NULL OR sub_status IN ('NEW', 'IN_PROGRESS', 'UNDER_INVESTIGATION', 'SETTLED')");

                            t.HasCheckConstraint("ck_claim_transaction_sequence", "last_transaction_sequence >= 0");

                            t.HasCheckConstraint("ck_claim_vehicle_count", "vehicle_count IS NULL OR vehicle_count >= 1");
                        });
                });

            modelBuilder.Entity("CoreIns.Modules.Claims.Persistence.ClaimantRow", b =>
                {
                    b.Property<Guid>("ClaimantId")
                        .HasColumnType("uuid")
                        .HasColumnName("claimant_id");

                    b.Property<Guid>("ClaimId")
                        .HasColumnType("uuid")
                        .HasColumnName("claim_id");

                    b.Property<string>("ClaimantType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("claimant_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Jurisdiction")
                        .IsRequired()
                        .HasColumnType("char(2)")
                        .HasColumnName("jurisdiction");

                    b.Property<Guid>("LegalEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("legal_entity_id");

                    b.Property<Guid>("PartyId")
                        .HasColumnType("uuid")
                        .HasColumnName("party_id");

                    b.Property<int>("RecordVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("record_version");

                    b.HasKey("ClaimantId")
                        .HasName("pk_claimant");

                    b.HasIndex("ClaimId", "PartyId")
                        .IsUnique()
                        .HasDatabaseName("ux_claimant_claim_party");

                    b.HasIndex("LegalEntityId", "PartyId")
                        .HasDatabaseName("ix_claimant_party");

                    b.ToTable("claimant", "clm", t =>
                        {
                            t.HasCheckConstraint("ck_claimant_jurisdiction", "jurisdiction ~ '^[A-Z]{2}$'");

                            t.HasCheckConstraint("ck_claimant_record_version", "record_version >= 1");

                            t.HasCheckConstraint("ck_claimant_type", "claimant_type IN ('INSURED', 'THIRD_PARTY', 'GUARANTEE_FUND', 'BUREAU')");
                        });
                });

            modelBuilder.Entity("CoreIns.Modules.Claims.Persistence.ExposureRow", b =>
                {
                    b.Property<Guid>("ExposureId")
                        .HasColumnType("uuid")
                        .HasColumnName("exposure_id");

                    b.Property<Guid>("ClaimId")
                        .HasColumnType("uuid")
                        .HasColumnName("claim_id");

                    b.Property<Guid>("ClaimantId")
                        .HasColumnType("uuid")
                        .HasColumnName("claimant_id");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("closed_at");

                    b.Property<string>("CoverageCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("coverage_code");

                    b.Property<string>("CoverageDecision")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("coverage_decision");

                    b.Property<string>("CoverageIndication")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("coverage_indication");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("DuplicateReason")
                        .HasColumnType("text")
                        .HasColumnName("duplicate_reason");

                    b.Property<string>("ExposureNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("exposure_number");

                    b.Property<Guid?>("IncidentId")
                        .HasColumnType("uuid")
                        .HasColumnName("incident_id");

                    b.Property<string>("Jurisdiction")
                        .IsRequired()
                        .HasColumnType("char(2)")
                        .HasColumnName("jurisdiction");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<Guid>("LegalEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("legal_entity_id");

                    b.Property<string>("Outcome")
                        .HasColumnType("text")
                        .HasColumnName("outcome");

                    b.Property<int>("RecordVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("record_version");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer")
                        .HasColumnName("sequence");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("StatutoryClocks")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("NOT_TRACKED")
                        .HasColumnName("statutory_clocks");

                    b.Property<string>("SubStatus")
                        .HasColumnType("text")
                        .HasColumnName("sub_status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("ExposureId")
                        .HasName("pk_exposure");

                    b.HasIndex("ClaimantId");

                    b.HasIndex("IncidentId");

                    b.HasIndex("ClaimId", "Sequence")
                        .IsUnique()
                        .HasDatabaseName("ux_exposure_claim_sequence");

                    b.HasIndex("LegalEntityId", "ExposureNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_exposure_number");

                    b.HasIndex("ClaimId", "CoverageCode", "ClaimantId", "IncidentId")
                        .IsUnique()
                        .HasDatabaseName("ux_exposure_open_coverage_claimant_incident")
                        .HasFilter("status = 'OPEN' AND duplicate_reason IS NULL");

                    NpgsqlIndexBuilderExtensions.AreNullsDistinct(b.HasIndex("ClaimId", "CoverageCode", "ClaimantId", "IncidentId"), false);

                    b.ToTable("exposure", "clm", t =>
                        {
                            t.HasCheckConstraint("ck_exposure_closed_shape", "status <> 'CLOSED' OR (sub_status IS NULL AND outcome IS NOT NULL AND closed_at IS NOT NULL)");

                            t.HasCheckConstraint("ck_exposure_decision", "coverage_decision IN ('PENDING', 'COVERED', 'COVERED_WITH_RESERVATION', 'PARTIALLY_COVERED', 'NOT_COVERED')");

                            t.HasCheckConstraint("ck_exposure_indication", "coverage_indication IN ('COVERED', 'NOT_COVERED', 'IN_QUESTION')");

                            t.HasCheckConstraint("ck_exposure_jurisdiction", "jurisdiction ~ '^[A-Z]{2}$'");

                            t.HasCheckConstraint("ck_exposure_open_shape", "status <> 'OPEN' OR (sub_status IS NOT NULL AND outcome IS NULL AND closed_at IS NULL)");

                            t.HasCheckConstraint("ck_exposure_outcome", "outcome IS NULL OR outcome IN ('COMPLETED', 'DENIED', 'WITHDRAWN', 'DUPLICATE', 'NO_PAYMENT')");

                            t.HasCheckConstraint("ck_exposure_record_version", "record_version >= 1");

                            t.HasCheckConstraint("ck_exposure_sequence", "sequence >= 1");

                            t.HasCheckConstraint("ck_exposure_status", "status IN ('OPEN', 'CLOSED')");

                            t.HasCheckConstraint("ck_exposure_sub_status", "sub_status IS NULL OR sub_status IN ('NEW', 'IN_PROGRESS')");
                        });
                });

            modelBuilder.Entity("CoreIns.Modules.Claims.Persistence.FinancialTransactionRow", b =>
                {
                    b.Property<Guid>("TxnId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("txn_id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("amount");

                    b.Property<Guid>("ClaimId")
                        .HasColumnType("uuid")
                        .HasColumnName("claim_id");

                    b.Property<Guid?>("ClaimPaymentId")
                        .HasColumnType("uuid")
                        .HasColumnName("claim_payment_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("char(3)")
                        .HasColumnName("currency");

                    b.Property<bool?>("Eroding")
                        .HasColumnType("boolean")
                        .HasColumnName("eroding");

                    b.Property<Guid>("ExposureId")
                        .HasColumnType("uuid")
                        .HasColumnName("exposure_id");

                    b.Property<decimal>("FunctionalAmount")
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("functional_amount");

                    b.Property<string>("FunctionalCurrency")
                        .IsRequired()
                        .HasColumnType("char(3)")
                        .HasColumnName("functional_currency");

                    b.Property<Guid?>("FxRateId")
                        .HasColumnType("uuid")
                        .HasColumnName("fx_rate_id");

                    b.Property<decimal>("GroupAmount")
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("group_amount");

                    b.Property<string>("GroupCurrency")
                        .IsRequired()
                        .HasColumnType("char(3)")
                        .HasColumnName("group_currency");

                    b.Property<string>("Jurisdiction")
                        .IsRequired()
                        .HasColumnType("char(2)")
                        .HasColumnName("jurisdiction");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<Guid>("LegalEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("legal_entity_id");

                    b.Property<string>("PaymentType")
                        .HasColumnType("text")
                        .HasColumnName("payment_type");

                    b.Property<bool>("Proposed")
                        .HasColumnType("boolean")
                        .HasColumnName("proposed");

                    b.Property<string>("ReasonCode")
                        .HasColumnType("text")
                        .HasColumnName("reason_code");

                    b.Property<int>("RecordVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("record_version");

                    b.Property<Guid?>("RecoveryId")
                        .HasColumnType("uuid")
                        .HasColumnName("recovery_id");

                    b.Property<Guid>("ReserveLineId")
                        .HasColumnType("uuid")
                        .HasColumnName("reserve_line_id");

                    b.Property<Guid?>("ReversesTxnId")
                        .HasColumnType("uuid")
                        .HasColumnName("reverses_txn_id");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer")
                        .HasColumnName("sequence");

                    b.Property<Guid>("SetId")
                        .HasColumnType("uuid")
                        .HasColumnName("set_id");

                    b.Property<DateOnly>("TransactionDate")
                        .HasColumnType("date")
                        .HasColumnName("transaction_date");

                    b.Property<string>("TxnNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("txn_number");

                    b.HasKey("TxnId")
                        .HasName("pk_financial_transaction");

                    b.HasIndex("RecoveryId");

                    b.HasIndex("ReserveLineId")
                        .HasDatabaseName("ix_financial_transaction_line");

                    b.HasIndex("ReversesTxnId");

                    b.HasIndex("SetId")
                        .HasDatabaseName("ix_financial_transaction_set");

                    b.HasIndex("ClaimId", "Sequence")
                        .IsUnique()
                        .HasDatabaseName("ux_financial_transaction_claim_sequence");

                    b.ToTable("financial_transaction", "clm", t =>
                        {
                            t.HasCheckConstraint("ck_financial_transaction_amount", "amount <> 0");

                            t.HasCheckConstraint("ck_financial_transaction_currencies", "currency ~ '^[A-Z]{3}$' AND functional_currency ~ '^[A-Z]{3}$' AND group_currency ~ '^[A-Z]{3}$'");

                            t.HasCheckConstraint("ck_financial_transaction_jurisdiction", "jurisdiction ~ '^[A-Z]{2}$'");

                            t.HasCheckConstraint("ck_financial_transaction_kind", "kind IN ('RESERVE', 'RECOVERY_RESERVE', 'RECOVERY', 'PAYMENT')");

                            t.HasCheckConstraint("ck_financial_transaction_payment_shape", "kind <> 'PAYMENT' OR ((amount > 0 OR (amount < 0 AND reverses_txn_id IS NOT NULL)) AND eroding IS NOT NULL AND payment_type IS NOT NULL AND claim_payment_id IS NOT NULL)");

                            t.HasCheckConstraint("ck_financial_transaction_record_version", "record_version >= 1");

                            t.HasCheckConstraint("ck_financial_transaction_recovery_shape", "kind NOT IN ('RECOVERY_RESERVE','RECOVERY') OR (recovery_id IS NOT NULL AND eroding IS NULL AND payment_type IS NULL AND claim_payment_id IS NULL)");

                            t.HasCheckConstraint("ck_financial_transaction_reserve_shape", "kind <> 'RESERVE' OR (eroding IS NULL AND payment_type IS NULL AND claim_payment_id IS NULL)");

                            t.HasCheckConstraint("ck_financial_transaction_sequence", "sequence >= 1");
                        });
                });

            modelBuilder.Entity("CoreIns.Modules.Claims.Persistence.FnolSnapshotRow", b =>
                {
                    b.Property<Guid>("FnolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("fnol_id");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("channel");

                    b.Property<Guid>("ClaimId")
                        .HasColumnType("uuid")
                        .HasColumnName("claim_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Jurisdiction")
                        .IsRequired()
                        .HasColumnType("char(2)")
                        .HasColumnName("jurisdiction");

                    b.Property<Guid>("LegalEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("legal_entity_id");

                    b.Property<byte[]>("PayloadEncrypted")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("payload_encrypted");

                    b.Property<int>("RecordVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("record_version");

                    b.Property<Guid?>("ReporterPartyId")
                        .HasColumnType("uuid")
                        .HasColumnName("reporter_party_id");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("submitted_at");

                    b.HasKey("FnolId")
                        .HasName("pk_fnol_snapshot");

                    b.HasIndex("ClaimId")
                        .IsUnique()
                        .HasDatabaseName("ux_fnol_snapshot_claim");

                    b.ToTable("fnol_snapshot", "clm", t =>
                        {
                            t.HasCheckConstraint("ck_fnol_snapshot_jurisdiction", "jurisdiction ~ '^[A-Z]{2}$'");

                            t.HasCheckConstraint("ck_fnol_snapshot_record_version", "record_version >= 1");
                        });
                });

            modelBuilder.Entity("CoreIns.Modules.Claims.Persistence.FsCaseRow", b =>
                {
                    b.Property<Guid>("FsCaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("fs_case_id");

                    b.Property<Guid>("ClaimId")
                        .HasColumnType("uuid")
                        .HasColumnName("claim_id");

                    b.Property<string>("ClearingReference")
                        .HasColumnType("text")
                        .HasColumnName("clearing_reference");

                    b.Property<decimal?>("ClearingValue")
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("clearing_value");

                    b.Property<Guid>("CounterpartyInsurerPartyId")
                        .HasColumnType("uuid")
                        .HasColumnName("counterparty_insurer_party_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("currency");

                    b.Property<string>("DisputeReason")
                        .HasColumnType("text")
                        .HasColumnName("dispute_reason");

                    b.Property<JsonDocument>("EligibilityResult")
                        .HasColumnType("jsonb")
                        .HasColumnName("eligibility_result");

                    b.Property<string>("EligibilityRuleId")
                        .HasColumnType("text")
                        .HasColumnName("eligibility_rule_id");

                    b.Property<string>("EligibilityRuleVersion")
                        .HasColumnType("text")
                        .HasColumnName("eligibility_rule_version");

                    b.Property<Guid?>("ExposureId")
                        .HasColumnType("uuid")
                        .HasColumnName("exposure_id");

                    b.Property<string>("Jurisdiction")
                        .IsRequired()
                        .HasColumnType("char(2)")
                        .HasColumnName("jurisdiction");

                    b.Property<Guid>("LegalEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("legal_entity_id");

                    b.Property<string>("LegalStatus")
                        .HasColumnType("text")
                        .HasColumnName("legal_status");

                    b.Property<string>("NotificationReference")
                        .HasColumnType("text")
                        .HasColumnName("notification_reference");

                    b.Property<bool>("Provisional")
                        .HasColumnType("boolean")
                        .HasColumnName("provisional");

                    b.Property<int>("RecordVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("record_version");

                    b.Property<Guid?>("RecoveryId")
                        .HasColumnType("uuid")
                        .HasColumnName("recovery_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<Guid?>("StatementLineId")
                        .HasColumnType("uuid")
                        .HasColumnName("statement_line_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("FsCaseId")
                        .HasName("pk_fs_case");

                    b.HasIndex("ExposureId");

                    b.HasIndex("RecoveryId");

                    b.HasIndex("ClaimId", "Role")
                        .IsUnique()
                        .HasDatabaseName("ux_fs_case_open_claim_role")
                        .HasFilter("status NOT IN ('NOT_ELIGIBLE','REJECTED','RECONCILED')");

                    b.HasIndex("LegalEntityId", "NotificationReference")
                        .IsUnique()
                        .HasDatabaseName("ux_fs_case_notification")
                        .HasFilter("notification_reference IS NOT NULL");

                    b.ToTable("fs_case", "clm", t =>
                        {
                            t.HasCheckConstraint("ck_fs_case_currency", "currency = 'EUR'");

                            t.HasCheckConstraint("ck_fs_case_jurisdiction", "jurisdiction ~ '^[A-Z]{2}$'");

                            t.HasCheckConstraint("ck_fs_case_record_version", "record_version >= 1");

                            t.HasCheckConstraint("ck_fs_case_role", "role IN ('OWN_INSURER','AT_FAULT_INSURER')");

                            t.HasCheckConstraint("ck_fs_case_rule", "eligibility_result IS NULL OR (eligibility_rule_id IS NOT NULL AND eligibility_rule_version IS NOT NULL AND legal_status IS NOT NULL)");

                            t.HasCheckConstraint("ck_fs_case_status", "status IN ('ELIGIBILITY_PENDING','ELIGIBLE','NOT_ELIGIBLE','SUBMITTED','ACCEPTED','DISPUTED','REJECTED','SETTLED','RECONCILED')");

                            t.HasCheckConstraint("ck_fs_case_value", "clearing_value IS NULL OR clearing_value >= 0");
                        });
                });

            modelBuilder.Entity("CoreIns.Modules.Claims.Persistence.FsStatementLineRow", b =>
                {
                    b.Property<Guid>("FsStatementLineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("fs_statement_line_id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("amount");

                    b.Property<Guid?>("ClaimId")
                        .HasColumnType("uuid")
                        .HasColumnName("claim_id");

                    b.Property<Guid?>("ClaimPaymentId")
                        .HasColumnType("uuid")
                        .HasColumnName("claim_payment_id");

                    b.Property<string>("ClearingReference")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("clearing_reference");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("currency");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("direction");

                    b.Property<string>("ExceptionReason")
                        .HasColumnType("text")
                        .HasColumnName("exception_reason");

                    b.Property<string>("ExternalReference")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("external_reference");

                    b.Property<Guid?>("FsCaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("fs_case_id");

                    b.Property<Guid>("FsStatementId")
                        .HasColumnType("uuid")
                        .HasColumnName("fs_statement_id");

                    b.Property<string>("Jurisdiction")
                        .IsRequired()
                        .HasColumnType("char(2)")
                        .HasColumnName("jurisdiction");

                    b.Property<Guid>("LegalEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("legal_entity_id");

                    b.Property<string>("MatchStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("match_status");

                    b.Property<int>("RecordVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("record_version");

                    b.Property<Guid?>("RecoveryId")
                        .HasColumnType("uuid")
                        .HasColumnName("recovery_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("FsStatementLineId")
                        .HasName("pk_fs_statement_line");

                    b.HasIndex("ClaimId");

                    b.HasIndex("ClaimPaymentId");

                    b.HasIndex("FsCaseId");

                    b.HasIndex("RecoveryId");

                    b.HasIndex("FsStatementId", "ExternalReference")
                        .IsUnique()
                        .HasDatabaseName("ux_fs_statement_line_reference");

                    b.ToTable("fs_statement_line", "clm", t =>
                        {
                            t.HasCheckConstraint("ck_fs_statement_line_amount", "amount > 0 AND currency = 'EUR'");

                            t.HasCheckConstraint("ck_fs_statement_line_direction", "direction IN ('PAYABLE','RECEIVABLE')");

                            t.HasCheckConstraint("ck_fs_statement_line_jurisdiction", "jurisdiction ~ '^[A-Z]{2}$'");

                            t.HasCheckConstraint("ck_fs_statement_line_match", "match_status IN ('UNMATCHED','MATCHED','EXCEPTION','SETTLED')");

                            t.HasCheckConstraint("ck_fs_statement_line_record_version", "record_version >= 1");
                        });
                });

            modelBuilder.Entity("CoreIns.Modules.Claims.Persistence.FsStatementRow", b =>
                {
                    b.Property<Guid>("FsStatementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("fs_statement_id");

                    b.Property<Guid?>("ApprovalRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("approval_request_id");

                    b.Property<Guid>("CounterpartyInsurerPartyId")
                        .HasColumnType("uuid")
                        .HasColumnName("counterparty_insurer_party_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("currency");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("direction");

                    b.Property<Guid?>("DisbursementId")
                        .HasColumnType("uuid")
                        .HasColumnName("disbursement_id");

                    b.Property<string>("ExternalReference")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("external_reference");

                    b.Property<string>("Jurisdiction")
                        .IsRequired()
                        .HasColumnType("char(2)")
                        .HasColumnName("jurisdiction");

                    b.Property<Guid>("LegalEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("legal_entity_id");

                    b.Property<decimal>("NetAmount")
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("net_amount");

                    b.Property<string>("Period")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("period");

                    b.Property<Guid?>("ReceivableId")
                        .HasColumnType("uuid")
                        .HasColumnName("receivable_id");

                    b.Property<int>("RecordVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("record_version");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("FsStatementId")
                        .HasName("pk_fs_statement");

                    b.HasIndex("LegalEntityId", "Period", "CounterpartyInsurerPartyId")
                        .IsUnique()
                        .HasDatabaseName("ux_fs_statement_period_counterparty");

                    b.ToTable("fs_statement", "clm", t =>
                        {
                            t.HasCheckConstraint("ck_fs_statement_currency", "currency = 'EUR'");

                            t.HasCheckConstraint("ck_fs_statement_direction", "direction IN ('PAYABLE','RECEIVABLE')");

                            t.HasCheckConstraint("ck_fs_statement_jurisdiction", "jurisdiction ~ '^[A-Z]{2}$'");

                            t.HasCheckConstraint("ck_fs_statement_net", "net_amount >= 0");

                            t.HasCheckConstraint("ck_fs_statement_period", "period ~ '^[0-9]{4}-(0[1-9]|1[0-2])$'");

                            t.HasCheckConstraint("ck_fs_statement_record_version", "record_version >= 1");

                            t.HasCheckConstraint("ck_fs_statement_status", "status IN ('PENDING','REQUESTED','SETTLED','REJECTED')");
                        });
                });

            modelBuilder.Entity("CoreIns.Modules.Claims.Persistence.IncidentRow", b =>
                {
                    b.Property<Guid>("IncidentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("incident_id");

                    b.Property<Guid>("ClaimId")
                        .HasColumnType("uuid")
                        .HasColumnName("claim_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.PrimitiveCollection<string[]>("DamageAreas")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("damage_areas");

                    b.Property<bool?>("Drivable")
                        .HasColumnType("boolean")
                        .HasColumnName("drivable");

                    b.Property<string>("IncidentType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("incident_type");

                    b.Property<string>("Jurisdiction")
                        .IsRequired()
                        .HasColumnType("char(2)")
                        .HasColumnName("jurisdiction");

                    b.Property<Guid>("LegalEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("legal_entity_id");

                    b.Property<int>("RecordVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("record_version");

                    b.Property<string>("VehicleRef")
                        .HasColumnType("text")
                        .HasColumnName("vehicle_ref");

                    b.HasKey("IncidentId")
                        .HasName("pk_incident");

                    b.HasIndex("ClaimId")
                        .HasDatabaseName("ix_incident_claim");

                    b.ToTable("incident", "clm", t =>
                        {
                            t.HasCheckConstraint("ck_incident_jurisdiction", "jurisdiction ~ '^[A-Z]{2}$'");

                            t.HasCheckConstraint("ck_incident_record_version", "record_version >= 1");

                            t.HasCheckConstraint("ck_incident_type", "incident_type IN ('VEHICLE', 'PROPERTY', 'INJURY', 'LIABILITY')");
                        });
                });

            modelBuilder.Entity("CoreIns.Modules.Claims.Persistence.PayeeAccountViewRow", b =>
                {
                    b.Property<Guid>("ClaimId")
                        .HasColumnType("uuid")
                        .HasColumnName("claim_id");

                    b.Property<Guid>("PayeeAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("payee_account_id");

                    b.Property<DateOnly?>("CoolingOffUntil")
                        .HasColumnType("date")
                        .HasColumnName("cooling_off_until");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsChange")
                        .HasColumnType("boolean")
                        .HasColumnName("is_change");

                    b.Property<string>("Jurisdiction")
                        .IsRequired()
                        .HasColumnType("char(2)")
                        .HasColumnName("jurisdiction");

                    b.Property<Guid>("LegalEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("legal_entity_id");

                    b.Property<string>("MaskedIban")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("masked_iban");

                    b.Property<Guid>("PartyId")
                        .HasColumnType("uuid")
                        .HasColumnName("party_id");

                    b.Property<int>("RecordVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("record_version");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<string>("VerificationStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("verification_status");

                    b.HasKey("ClaimId", "PayeeAccountId")
                        .HasName("pk_payee_account_view");

                    b.ToTable("payee_account_view", "clm", t =>
                        {
                            t.HasCheckConstraint("ck_payee_account_view_jurisdiction", "jurisdiction ~ '^[A-Z]{2}$'");

                            t.HasCheckConstraint("ck_payee_account_view_record_version", "record_version >= 1");
                        });
                });

            modelBuilder.Entity("CoreIns.Modules.Claims.Persistence.RecoveryRow", b =>
                {
                    b.Property<Guid>("RecoveryId")
                        .HasColumnType("uuid")
                        .HasColumnName("recovery_id");

                    b.Property<string>("AllocationRule")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("allocation_rule");

                    b.Property<Guid?>("BuyerPartyId")
                        .HasColumnType("uuid")
                        .HasColumnName("buyer_party_id");

                    b.Property<Guid>("ClaimId")
                        .HasColumnType("uuid")
                        .HasColumnName("claim_id");

                    b.Property<Guid>("CounterpartyPartyId")
                        .HasColumnType("uuid")
                        .HasColumnName("counterparty_party_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("currency");

                    b.Property<DateOnly?>("DemandedOn")
                        .HasColumnType("date")
                        .HasColumnName("demanded_on");

                    b.Property<decimal>("ExpectedAmount")
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("expected_amount");

                    b.Property<Guid?>("ExposureId")
                        .HasColumnType("uuid")
                        .HasColumnName("exposure_id");

                    b.Property<Guid?>("FsCaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("fs_case_id");

                    b.Property<Guid?>("FsStatementId")
                        .HasColumnType("uuid")
                        .HasColumnName("fs_statement_id");

                    b.Property<string>("Jurisdiction")
                        .IsRequired()
                        .HasColumnType("char(2)")
                        .HasColumnName("jurisdiction");

                    b.Property<Guid>("LegalEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("legal_entity_id");

                    b.Property<JsonDocument>("Milestones")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("milestones");

                    b.Property<string>("PaymentReference")
                        .HasColumnType("text")
                        .HasColumnName("payment_reference");

                    b.Property<Guid?>("ReceivableId")
                        .HasColumnType("uuid")
                        .HasColumnName("receivable_id");

                    b.Property<int>("RecordVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("record_version");

                    b.Property<decimal?>("SalePrice")
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("sale_price");

                    b.Property<decimal?>("SalvageEstimate")
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("salvage_estimate");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("WriteOffReason")
                        .HasColumnType("text")
                        .HasColumnName("write_off_reason");

                    b.HasKey("RecoveryId")
                        .HasName("pk_recovery");

                    b.HasIndex("ClaimId")
                        .HasDatabaseName("ix_recovery_claim");

                    b.HasIndex("ExposureId");

                    b.HasIndex("ReceivableId")
                        .IsUnique()
                        .HasDatabaseName("ux_recovery_receivable")
                        .HasFilter("receivable_id IS NOT NULL");

                    b.ToTable("recovery", "clm", t =>
                        {
                            t.HasCheckConstraint("ck_recovery_allocation", "allocation_rule IN ('PRO_RATA_PAID','SPECIFIED')");

                            t.HasCheckConstraint("ck_recovery_amount", "expected_amount >= 0 AND (salvage_estimate IS NULL OR salvage_estimate >= 0) AND (sale_price IS NULL OR sale_price >= 0)");

                            t.HasCheckConstraint("ck_recovery_currency", "currency = 'EUR'");

                            t.HasCheckConstraint("ck_recovery_jurisdiction", "jurisdiction ~ '^[A-Z]{2}$'");

                            t.HasCheckConstraint("ck_recovery_record_version", "record_version >= 1");

                            t.HasCheckConstraint("ck_recovery_status", "status IN ('OPEN','DEMANDED','AGREED','DISPUTED','IN_ARBITRATION','IN_LITIGATION','CLOSED','WRITTEN_OFF')");

                            t.HasCheckConstraint("ck_recovery_type", "type IN ('SUBROGATION','SALVAGE','FRIENDLY_SETTLEMENT')");
                        });
                });

            modelBuilder.Entity("CoreIns.Modules.Claims.Persistence.ReserveLineRow", b =>
                {
                    b.Property<Guid>("ReserveLineId")
                        .HasColumnType("uuid")
                        .HasColumnName("reserve_line_id");

                    b.Property<Guid>("ClaimId")
                        .HasColumnType("uuid")
                        .HasColumnName("claim_id");

                    b.Property<string>("CostCategory")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cost_category");

                    b.Property<string>("CostType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cost_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("char(3)")
                        .HasColumnName("currency");

                    b.Property<Guid>("ExposureId")
                        .HasColumnType("uuid")
                        .HasColumnName("exposure_id");

                    b.Property<bool>("FinalFlag")
                        .HasColumnType("boolean")
                        .HasColumnName("final_flag");

                    b.Property<string>("Jurisdiction")
                        .IsRequired()
                        .HasColumnType("char(2)")
                        .HasColumnName("jurisdiction");

                    b.Property<Guid>("LegalEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("legal_entity_id");

                    b.Property<int>("RecordVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("record_version");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("ReserveLineId")
                        .HasName("pk_reserve_line");

                    b.HasIndex("ClaimId")
                        .HasDatabaseName("ix_reserve_line_claim");

                    b.HasIndex("ExposureId", "CostType", "CostCategory", "Currency")
                        .IsUnique()
                        .HasDatabaseName("ux_reserve_line_key");

                    b.ToTable("reserve_line", "clm", t =>
                        {
                            t.HasCheckConstraint("ck_reserve_line_cost_type", "cost_type IN ('INDEMNITY', 'EXPENSE_ALLOCATED', 'EXPENSE_UNALLOCATED', 'STATUTORY_INTEREST')");

                            t.HasCheckConstraint("ck_reserve_line_currency", "currency ~ '^[A-Z]{3}$'");

                            t.HasCheckConstraint("ck_reserve_line_jurisdiction", "jurisdiction ~ '^[A-Z]{2}$'");

                            t.HasCheckConstraint("ck_reserve_line_record_version", "record_version >= 1");
                        });
                });

            modelBuilder.Entity("CoreIns.Modules.Claims.Persistence.ReverificationRow", b =>
                {
                    b.Property<Guid>("ReverificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("reverification_id");

                    b.Property<Guid>("CauseEventId")
                        .HasColumnType("uuid")
                        .HasColumnName("cause_event_id");

                    b.Property<string>("CauseEventType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cause_event_type");

                    b.Property<Guid>("ClaimId")
                        .HasColumnType("uuid")
                        .HasColumnName("claim_id");

                    b.Property<byte[]>("CommentEncrypted")
                        .HasColumnType("bytea")
                        .HasColumnName("comment_encrypted");

                    b.Property<bool?>("CoverageInQuestion")
                        .HasColumnType("boolean")
                        .HasColumnName("coverage_in_question");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DecidedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("decided_at");

                    b.Property<string>("DecidedBy")
                        .HasColumnType("text")
                        .HasColumnName("decided_by");

                    b.Property<string>("Jurisdiction")
                        .IsRequired()
                        .HasColumnType("char(2)")
                        .HasColumnName("jurisdiction");

                    b.Property<Guid>("LegalEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("legal_entity_id");

                    b.Property<string>("NewSnapshotRef")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("new_snapshot_ref");

                    b.Property<string>("OldSnapshotRef")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("old_snapshot_ref");

                    b.Property<DateTime>("RaisedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("raised_at");

                    b.Property<string>("ReasonCode")
                        .HasColumnType("text")
                        .HasColumnName("reason_code");

                    b.Property<int>("RecordVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("record_version");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("ReverificationId")
                        .HasName("pk_reverification");

                    b.HasIndex("ClaimId", "CauseEventId")
                        .IsUnique()
                        .HasDatabaseName("ux_reverification_claim_cause");

                    b.HasIndex("ClaimId", "Status")
                        .HasDatabaseName("ix_reverification_claim_status");

                    b.ToTable("reverification", "clm", t =>
                        {
                            t.HasCheckConstraint("ck_reverification_decided_shape", "(status = 'OPEN') = (decided_at IS NULL)");

                            t.HasCheckConstraint("ck_reverification_jurisdiction", "jurisdiction ~ '^[A-Z]{2}$'");

                            t.HasCheckConstraint("ck_reverification_reason", "status = 'OPEN' OR reason_code IS NOT NULL");

                            t.HasCheckConstraint("ck_reverification_record_version", "record_version >= 1");

                            t.HasCheckConstraint("ck_reverification_refs", "old_snapshot_ref <> new_snapshot_ref");

                            t.HasCheckConstraint("ck_reverification_status", "status IN ('OPEN', 'KEPT', 'ADOPTED')");
                        });
                });

            modelBuilder.Entity("CoreIns.Modules.Claims.Persistence.SetApprovalRow", b =>
                {
                    b.Property<Guid>("ApprovalRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("approval_request_id");

                    b.Property<string>("ApprovalType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("approval_type");

                    b.Property<decimal>("AuthorityAmount")
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("authority_amount");

                    b.Property<string>("AuthorityCostType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("authority_cost_type");

                    b.Property<string>("AuthorityType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("authority_type");

                    b.Property<string>("Checker")
                        .HasColumnType("text")
                        .HasColumnName("checker");

                    b.Property<Guid?>("CheckerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("checker_user_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("char(3)")
                        .HasColumnName("currency");

                    b.Property<DateTime?>("DecidedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("decided_at");

                    b.Property<string>("Jurisdiction")
                        .IsRequired()
                        .HasColumnType("char(2)")
                        .HasColumnName("jurisdiction");

                    b.Property<Guid>("LegalEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("legal_entity_id");

                    b.Property<string>("PayloadHash")
                        .IsRequired()
                        .HasColumnType("char(64)")
                        .HasColumnName("payload_hash");

                    b.Property<int>("RecordVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("record_version");

                    b.Property<Guid>("SetId")
                        .HasColumnType("uuid")
                        .HasColumnName("set_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("SubjectId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subject_id");

                    b.Property<string>("SubjectType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subject_type");

                    b.HasKey("ApprovalRequestId")
                        .HasName("pk_set_approval");

                    b.HasIndex("SetId", "AuthorityType", "AuthorityCostType")
                        .IsUnique()
                        .HasDatabaseName("ux_set_approval_bucket");

                    b.ToTable("set_approval", "clm", t =>
                        {
                            t.HasCheckConstraint("ck_set_approval_amount", "authority_amount > 0");

                            t.HasCheckConstraint("ck_set_approval_jurisdiction", "jurisdiction ~ '^[A-Z]{2}$'");

                            t.HasCheckConstraint("ck_set_approval_record_version", "record_version >= 1");

                            t.HasCheckConstraint("ck_set_approval_status", "status IN ('PENDING', 'APPROVED', 'REJECTED')");
                        });
                });

            modelBuilder.Entity("CoreIns.Modules.Claims.Persistence.TransactionSetRow", b =>
                {
                    b.Property<Guid>("SetId")
                        .HasColumnType("uuid")
                        .HasColumnName("set_id");

                    b.Property<decimal?>("ApprovalAuthorityAmount")
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("approval_authority_amount");

                    b.Property<string>("ApprovalAuthorityCostType")
                        .HasColumnType("text")
                        .HasColumnName("approval_authority_cost_type");

                    b.Property<string>("ApprovalAuthorityType")
                        .HasColumnType("text")
                        .HasColumnName("approval_authority_type");

                    b.Property<string>("ApprovalPayloadHash")
                        .HasColumnType("char(64)")
                        .HasColumnName("approval_payload_hash");

                    b.Property<Guid?>("ApprovalRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("approval_request_id");

                    b.Property<string>("ApprovalSubjectId")
                        .HasColumnType("text")
                        .HasColumnName("approval_subject_id");

                    b.Property<string>("ApprovalSubjectType")
                        .HasColumnType("text")
                        .HasColumnName("approval_subject_type");

                    b.Property<string>("ApprovalType")
                        .HasColumnType("text")
                        .HasColumnName("approval_type");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("approved_at");

                    b.Property<string>("Approver")
                        .HasColumnType("text")
                        .HasColumnName("approver");

                    b.Property<Guid?>("ApproverUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("approver_user_id");

                    b.PrimitiveCollection<Guid[]>("AuthorityCheckIds")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("authority_check_ids");

                    b.Property<string>("BasisHash")
                        .IsRequired()
                        .HasColumnType("char(64)")
                        .HasColumnName("basis_hash");

                    b.Property<Guid>("ClaimId")
                        .HasColumnType("uuid")
                        .HasColumnName("claim_id");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasColumnType("char(64)")
                        .HasColumnName("content_hash");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<long>("CreatedTxid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("created_txid")
                        .HasDefaultValueSql("txid_current()");

                    b.Property<DateTime?>("DecidedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("decided_at");

                    b.Property<string>("EvidenceKind")
                        .HasColumnType("text")
                        .HasColumnName("evidence_kind");

                    b.Property<string>("EvidenceRef")
                        .HasColumnType("text")
                        .HasColumnName("evidence_ref");

                    b.Property<bool>("FourEyes")
                        .HasColumnType("boolean")
                        .HasColumnName("four_eyes");

                    b.Property<string>("Jurisdiction")
                        .IsRequired()
                        .HasColumnType("char(2)")
                        .HasColumnName("jurisdiction");

                    b.Property<Guid>("LegalEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("legal_entity_id");

                    b.Property<int>("RecordVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("record_version");

                    b.Property<string>("ReferralRole")
                        .HasColumnType("text")
                        .HasColumnName("referral_role");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("text")
                        .HasColumnName("rejection_reason");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("submitted_at");

                    b.Property<string>("Submitter")
                        .HasColumnType("text")
                        .HasColumnName("submitter");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("SetId")
                        .HasName("pk_transaction_set");

                    b.HasIndex("ApprovalRequestId")
                        .IsUnique()
                        .HasDatabaseName("ux_transaction_set_approval_request")
                        .HasFilter("approval_request_id IS NOT NULL");

                    b.HasIndex("ClaimId")
                        .HasDatabaseName("ix_transaction_set_claim");

                    b.HasIndex("LegalEntityId", "EvidenceKind", "EvidenceRef")
                        .IsUnique()
                        .HasDatabaseName("ux_transaction_set_evidence")
                        .HasFilter("evidence_ref IS NOT NULL");

                    b.ToTable("transaction_set", "clm", t =>
                        {
                            t.HasCheckConstraint("ck_transaction_set_approved_shape", "status NOT IN ('APPROVED', 'POSTED') OR approved_at IS NOT NULL");

                            t.HasCheckConstraint("ck_transaction_set_evidence", "(evidence_kind IS NULL AND evidence_ref IS NULL) OR (evidence_kind IN ('BIL_ALLOCATION','FS_NOTIFICATION','FS_STATEMENT_LINE','DISBURSEMENT_OUTCOME') AND evidence_ref IS NOT NULL)");

                            t.HasCheckConstraint("ck_transaction_set_jurisdiction", "jurisdiction ~ '^[A-Z]{2}$'");

                            t.HasCheckConstraint("ck_transaction_set_pending_shape", "status <> 'PENDING_APPROVAL' OR (approval_request_id IS NOT NULL AND approval_payload_hash IS NOT NULL)");

                            t.HasCheckConstraint("ck_transaction_set_record_version", "record_version >= 1");

                            t.HasCheckConstraint("ck_transaction_set_rejected_shape", "status <> 'REJECTED' OR rejection_reason IS NOT NULL");

                            t.HasCheckConstraint("ck_transaction_set_status", "status IN ('DRAFT', 'SUBMITTED', 'PENDING_APPROVAL', 'APPROVED', 'REJECTED', 'POSTED')");
                        });
                });

            modelBuilder.Entity("CoreIns.Modules.Claims.Persistence.ClaimPaymentRow", b =>
                {
                    b.HasOne("CoreIns.Modules.Claims.Persistence.ExposureRow", null)
                        .WithMany()
                        .HasForeignKey("ExposureId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_claim_payment_exposure");

                    b.HasOne("CoreIns.Modules.Claims.Persistence.ClaimPaymentRow", null)
                        .WithMany()
                        .HasForeignKey("ReissueOf")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_claim_payment_reissue");

                    b.HasOne("CoreIns.Modules.Claims.Persistence.ClaimPaymentRow", null)
                        .WithMany()
                        .HasForeignKey("ReversalOf")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_claim_payment_reversal");

                    b.HasOne("CoreIns.Modules.Claims.Persistence.TransactionSetRow", null)
                        .WithMany()
                        .HasForeignKey("SetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_claim_payment_set");
                });

            modelBuilder.Entity("CoreIns.Modules.Claims.Persistence.ClaimRow", b =>
                {
                    b.HasOne("CoreIns.Modules.Claims.Persistence.ClaimRow", null)
                        .WithMany()
                        .HasForeignKey("DuplicateOfClaimId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_claim_duplicate_of");
                });

            modelBuilder.Entity("CoreIns.Modules.Claims.Persistence.ClaimantRow", b =>
                {
                    b.HasOne("CoreIns.Modules.Claims.Persistence.ClaimRow", null)
                        .WithMany()
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_claimant_claim");
                });

            modelBuilder.Entity("CoreIns.Modules.Claims.Persistence.ExposureRow", b =>
                {
                    b.HasOne("CoreIns.Modules.Claims.Persistence.ClaimRow", null)
                        .WithMany()
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_exposure_claim");

                    b.HasOne("CoreIns.Modules.Claims.Persistence.ClaimantRow", null)
                        .WithMany()
                        .HasForeignKey("ClaimantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_exposure_claimant");

                    b.HasOne("CoreIns.Modules.Claims.Persistence.IncidentRow", null)
                        .WithMany()
                        .HasForeignKey("IncidentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_exposure_incident");
                });

            modelBuilder.Entity("CoreIns.Modules.Claims.Persistence.FinancialTransactionRow", b =>
                {
                    b.HasOne("CoreIns.Modules.Claims.Persistence.RecoveryRow", null)
                        .WithMany()
                        .HasForeignKey("RecoveryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_financial_transaction_recovery");

                    b.HasOne("CoreIns.Modules.Claims.Persistence.ReserveLineRow", null)
                        .WithMany()
                        .HasForeignKey("ReserveLineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_financial_transaction_line");

                    b.HasOne("CoreIns.Modules.Claims.Persistence.FinancialTransactionRow", null)
                        .WithMany()
                        .HasForeignKey("ReversesTxnId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_financial_transaction_reverses");

                    b.HasOne("CoreIns.Modules.Claims.Persistence.TransactionSetRow", null)
                        .WithMany()
                        .HasForeignKey("SetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_financial_transaction_set");
                });

            modelBuilder.Entity("CoreIns.Modules.Claims.Persistence.FnolSnapshotRow", b =>
                {
                    b.HasOne("CoreIns.Modules.Claims.Persistence.ClaimRow", null)
                        .WithMany()
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_fnol_snapshot_claim");
                });

            modelBuilder.Entity("CoreIns.Modules.Claims.Persistence.FsCaseRow", b =>
                {
                    b.HasOne("CoreIns.Modules.Claims.Persistence.ClaimRow", null)
                        .WithMany()
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_fs_case_claim");

                    b.HasOne("CoreIns.Modules.Claims.Persistence.ExposureRow", null)
                        .WithMany()
                        .HasForeignKey("ExposureId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_fs_case_exposure");

                    b.HasOne("CoreIns.Modules.Claims.Persistence.RecoveryRow", null)
                        .WithMany()
                        .HasForeignKey("RecoveryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_fs_case_recovery");
                });

            modelBuilder.Entity("CoreIns.Modules.Claims.Persistence.FsStatementLineRow", b =>
                {
                    b.HasOne("CoreIns.Modules.Claims.Persistence.ClaimRow", null)
                        .WithMany()
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_fs_statement_line_claim");

                    b.HasOne("CoreIns.Modules.Claims.Persistence.ClaimPaymentRow", null)
                        .WithMany()
                        .HasForeignKey("ClaimPaymentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_fs_statement_line_payment");

                    b.HasOne("CoreIns.Modules.Claims.Persistence.FsCaseRow", null)
                        .WithMany()
                        .HasForeignKey("FsCaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_fs_statement_line_case");

                    b.HasOne("CoreIns.Modules.Claims.Persistence.FsStatementRow", null)
                        .WithMany()
                        .HasForeignKey("FsStatementId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_fs_statement_line_statement");

                    b.HasOne("CoreIns.Modules.Claims.Persistence.RecoveryRow", null)
                        .WithMany()
                        .HasForeignKey("RecoveryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_fs_statement_line_recovery");
                });

            modelBuilder.Entity("CoreIns.Modules.Claims.Persistence.IncidentRow", b =>
                {
                    b.HasOne("CoreIns.Modules.Claims.Persistence.ClaimRow", null)
                        .WithMany()
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_incident_claim");
                });

            modelBuilder.Entity("CoreIns.Modules.Claims.Persistence.PayeeAccountViewRow", b =>
                {
                    b.HasOne("CoreIns.Modules.Claims.Persistence.ClaimRow", null)
                        .WithMany()
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_payee_account_view_claim");
                });

            modelBuilder.Entity("CoreIns.Modules.Claims.Persistence.RecoveryRow", b =>
                {
                    b.HasOne("CoreIns.Modules.Claims.Persistence.ClaimRow", null)
                        .WithMany()
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_recovery_claim");

                    b.HasOne("CoreIns.Modules.Claims.Persistence.ExposureRow", null)
                        .WithMany()
                        .HasForeignKey("ExposureId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_recovery_exposure");
                });

            modelBuilder.Entity("CoreIns.Modules.Claims.Persistence.ReserveLineRow", b =>
                {
                    b.HasOne("CoreIns.Modules.Claims.Persistence.ClaimRow", null)
                        .WithMany()
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_reserve_line_claim");

                    b.HasOne("CoreIns.Modules.Claims.Persistence.ExposureRow", null)
                        .WithMany()
                        .HasForeignKey("ExposureId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_reserve_line_exposure");
                });

            modelBuilder.Entity("CoreIns.Modules.Claims.Persistence.ReverificationRow", b =>
                {
                    b.HasOne("CoreIns.Modules.Claims.Persistence.ClaimRow", null)
                        .WithMany()
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_reverification_claim");
                });

            modelBuilder.Entity("CoreIns.Modules.Claims.Persistence.SetApprovalRow", b =>
                {
                    b.HasOne("CoreIns.Modules.Claims.Persistence.TransactionSetRow", null)
                        .WithMany()
                        .HasForeignKey("SetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_set_approval_set");
                });

            modelBuilder.Entity("CoreIns.Modules.Claims.Persistence.TransactionSetRow", b =>
                {
                    b.HasOne("CoreIns.Modules.Claims.Persistence.ClaimRow", null)
                        .WithMany()
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_transaction_set_claim");
                });
#pragma warning restore 612, 618
        }
    }
}
