// <auto-generated />
using System;
using CoreIns.Modules.Claims.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CoreIns.Modules.Claims.Persistence.Migrations
{
    [DbContext(typeof(ClaimsDbContext))]
    partial class ClaimsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("clm")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CoreIns.Modules.Claims.Persistence.ClaimRow", b =>
                {
                    b.Property<Guid>("ClaimId")
                        .HasColumnType("uuid")
                        .HasColumnName("claim_id");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("channel");

                    b.Property<string>("ClaimNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("claim_number");

                    b.Property<string>("CloseReasonCode")
                        .HasColumnType("text")
                        .HasColumnName("close_reason_code");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("closed_at");

                    b.Property<bool>("CoverageInQuestion")
                        .HasColumnType("boolean")
                        .HasColumnName("coverage_in_question");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<byte[]>("DescriptionEncrypted")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("description_encrypted");

                    b.Property<Guid?>("DuplicateOfClaimId")
                        .HasColumnType("uuid")
                        .HasColumnName("duplicate_of_claim_id");

                    b.Property<string>("DuplicateReasonCode")
                        .HasColumnType("text")
                        .HasColumnName("duplicate_reason_code");

                    b.Property<string>("Handler")
                        .HasColumnType("text")
                        .HasColumnName("handler");

                    b.Property<string>("HandlingSegment")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("handling_segment");

                    b.Property<Guid>("InsuredPartyId")
                        .HasColumnType("uuid")
                        .HasColumnName("insured_party_id");

                    b.Property<string>("Jurisdiction")
                        .IsRequired()
                        .HasColumnType("char(2)")
                        .HasColumnName("jurisdiction");

                    b.Property<int>("LastExposureSequence")
                        .HasColumnType("integer")
                        .HasColumnName("last_exposure_sequence");

                    b.Property<Guid>("LegalEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("legal_entity_id");

                    b.Property<string>("LineOfBusiness")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("line_of_business");

                    b.Property<DateTime>("LossAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("loss_at");

                    b.Property<string>("LossCause")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("loss_cause");

                    b.Property<DateOnly>("LossDate")
                        .HasColumnType("date")
                        .HasColumnName("loss_date");

                    b.Property<byte[]>("LossLocationEncrypted")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("loss_location_encrypted");

                    b.Property<DateOnly>("NoticeOn")
                        .HasColumnType("date")
                        .HasColumnName("notice_on");

                    b.Property<string>("Outcome")
                        .HasColumnType("text")
                        .HasColumnName("outcome");

                    b.Property<Guid>("PolicyId")
                        .HasColumnType("uuid")
                        .HasColumnName("policy_id");

                    b.Property<bool>("PolicyInForceAtLoss")
                        .HasColumnType("boolean")
                        .HasColumnName("policy_in_force_at_loss");

                    b.Property<string>("PolicyNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("policy_number");

                    b.Property<string>("PolicyStatusAtLoss")
                        .HasColumnType("text")
                        .HasColumnName("policy_status_at_loss");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("product_code");

                    b.Property<string>("ProductVersion")
                        .HasColumnType("text")
                        .HasColumnName("product_version");

                    b.Property<string>("ReceiptMedium")
                        .HasColumnType("text")
                        .HasColumnName("receipt_medium");

                    b.Property<int>("RecordVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("record_version");

                    b.Property<int>("ReopenCount")
                        .HasColumnType("integer")
                        .HasColumnName("reopen_count");

                    b.PrimitiveCollection<string[]>("SnapshotCoverageCodes")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("snapshot_coverage_codes");

                    b.Property<DateTime>("SnapshotKnownAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("snapshot_known_at");

                    b.Property<string>("SnapshotRef")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("snapshot_ref");

                    b.Property<Guid?>("SnapshotSegmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("snapshot_segment_id");

                    b.Property<string>("SnapshotStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("snapshot_status");

                    b.Property<DateTime>("SnapshotValidAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("snapshot_valid_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("SubStatus")
                        .HasColumnType("text")
                        .HasColumnName("sub_status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("ClaimId")
                        .HasName("pk_claim");

                    b.HasIndex("DuplicateOfClaimId");

                    b.HasIndex("LegalEntityId", "ClaimNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_claim_number");

                    b.HasIndex("LegalEntityId", "InsuredPartyId")
                        .HasDatabaseName("ix_claim_insured_party");

                    b.HasIndex("LegalEntityId", "PolicyNumber")
                        .HasDatabaseName("ix_claim_policy_number");

                    b.HasIndex("LegalEntityId", "PolicyId", "LossDate")
                        .HasDatabaseName("ix_claim_policy_loss_date");

                    b.ToTable("claim", "clm", t =>
                        {
                            t.HasCheckConstraint("ck_claim_closed_shape", "status <> 'CLOSED' OR (sub_status IS NULL AND outcome IS NOT NULL AND closed_at IS NOT NULL)");

                            t.HasCheckConstraint("ck_claim_exposure_sequence", "last_exposure_sequence >= 0");

                            t.HasCheckConstraint("ck_claim_jurisdiction", "jurisdiction ~ '^[A-Z]{2}$'");

                            t.HasCheckConstraint("ck_claim_notice_after_loss", "notice_on >= loss_date");

                            t.HasCheckConstraint("ck_claim_open_shape", "status <> 'OPEN' OR (sub_status IS NOT NULL AND outcome IS NULL AND closed_at IS NULL)");

                            t.HasCheckConstraint("ck_claim_outcome", "outcome IS NULL OR outcome IN ('COMPLETED', 'DENIED', 'WITHDRAWN', 'DUPLICATE', 'NO_PAYMENT')");

                            t.HasCheckConstraint("ck_claim_record_version", "record_version >= 1");

                            t.HasCheckConstraint("ck_claim_snapshot_status", "snapshot_status IN ('PENDING', 'VERIFIED', 'REVERIFICATION_REQUIRED')");

                            t.HasCheckConstraint("ck_claim_status", "status IN ('DRAFT', 'OPEN', 'CLOSED')");

                            t.HasCheckConstraint("ck_claim_sub_status", "sub_status IS NULL OR sub_status IN ('NEW', 'IN_PROGRESS', 'UNDER_INVESTIGATION', 'SETTLED')");
                        });
                });

            modelBuilder.Entity("CoreIns.Modules.Claims.Persistence.ClaimantRow", b =>
                {
                    b.Property<Guid>("ClaimantId")
                        .HasColumnType("uuid")
                        .HasColumnName("claimant_id");

                    b.Property<Guid>("ClaimId")
                        .HasColumnType("uuid")
                        .HasColumnName("claim_id");

                    b.Property<string>("ClaimantType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("claimant_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Jurisdiction")
                        .IsRequired()
                        .HasColumnType("char(2)")
                        .HasColumnName("jurisdiction");

                    b.Property<Guid>("LegalEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("legal_entity_id");

                    b.Property<Guid>("PartyId")
                        .HasColumnType("uuid")
                        .HasColumnName("party_id");

                    b.Property<int>("RecordVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("record_version");

                    b.HasKey("ClaimantId")
                        .HasName("pk_claimant");

                    b.HasIndex("ClaimId", "PartyId")
                        .IsUnique()
                        .HasDatabaseName("ux_claimant_claim_party");

                    b.HasIndex("LegalEntityId", "PartyId")
                        .HasDatabaseName("ix_claimant_party");

                    b.ToTable("claimant", "clm", t =>
                        {
                            t.HasCheckConstraint("ck_claimant_jurisdiction", "jurisdiction ~ '^[A-Z]{2}$'");

                            t.HasCheckConstraint("ck_claimant_record_version", "record_version >= 1");

                            t.HasCheckConstraint("ck_claimant_type", "claimant_type IN ('INSURED', 'THIRD_PARTY', 'GUARANTEE_FUND', 'BUREAU')");
                        });
                });

            modelBuilder.Entity("CoreIns.Modules.Claims.Persistence.ExposureRow", b =>
                {
                    b.Property<Guid>("ExposureId")
                        .HasColumnType("uuid")
                        .HasColumnName("exposure_id");

                    b.Property<Guid>("ClaimId")
                        .HasColumnType("uuid")
                        .HasColumnName("claim_id");

                    b.Property<Guid>("ClaimantId")
                        .HasColumnType("uuid")
                        .HasColumnName("claimant_id");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("closed_at");

                    b.Property<string>("CoverageCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("coverage_code");

                    b.Property<string>("CoverageDecision")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("coverage_decision");

                    b.Property<string>("CoverageIndication")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("coverage_indication");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("DuplicateReason")
                        .HasColumnType("text")
                        .HasColumnName("duplicate_reason");

                    b.Property<string>("ExposureNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("exposure_number");

                    b.Property<Guid?>("IncidentId")
                        .HasColumnType("uuid")
                        .HasColumnName("incident_id");

                    b.Property<string>("Jurisdiction")
                        .IsRequired()
                        .HasColumnType("char(2)")
                        .HasColumnName("jurisdiction");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<Guid>("LegalEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("legal_entity_id");

                    b.Property<string>("Outcome")
                        .HasColumnType("text")
                        .HasColumnName("outcome");

                    b.Property<int>("RecordVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("record_version");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer")
                        .HasColumnName("sequence");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("SubStatus")
                        .HasColumnType("text")
                        .HasColumnName("sub_status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("ExposureId")
                        .HasName("pk_exposure");

                    b.HasIndex("ClaimantId");

                    b.HasIndex("IncidentId");

                    b.HasIndex("ClaimId", "Sequence")
                        .IsUnique()
                        .HasDatabaseName("ux_exposure_claim_sequence");

                    b.HasIndex("LegalEntityId", "ExposureNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_exposure_number");

                    b.HasIndex("ClaimId", "CoverageCode", "ClaimantId", "IncidentId")
                        .IsUnique()
                        .HasDatabaseName("ux_exposure_open_coverage_claimant_incident")
                        .HasFilter("status = 'OPEN' AND duplicate_reason IS NULL");

                    NpgsqlIndexBuilderExtensions.AreNullsDistinct(b.HasIndex("ClaimId", "CoverageCode", "ClaimantId", "IncidentId"), false);

                    b.ToTable("exposure", "clm", t =>
                        {
                            t.HasCheckConstraint("ck_exposure_closed_shape", "status <> 'CLOSED' OR (sub_status IS NULL AND outcome IS NOT NULL AND closed_at IS NOT NULL)");

                            t.HasCheckConstraint("ck_exposure_decision", "coverage_decision IN ('PENDING', 'COVERED', 'COVERED_WITH_RESERVATION', 'PARTIALLY_COVERED', 'NOT_COVERED')");

                            t.HasCheckConstraint("ck_exposure_indication", "coverage_indication IN ('COVERED', 'NOT_COVERED', 'IN_QUESTION')");

                            t.HasCheckConstraint("ck_exposure_jurisdiction", "jurisdiction ~ '^[A-Z]{2}$'");

                            t.HasCheckConstraint("ck_exposure_open_shape", "status <> 'OPEN' OR (sub_status IS NOT NULL AND outcome IS NULL AND closed_at IS NULL)");

                            t.HasCheckConstraint("ck_exposure_outcome", "outcome IS NULL OR outcome IN ('COMPLETED', 'DENIED', 'WITHDRAWN', 'DUPLICATE', 'NO_PAYMENT')");

                            t.HasCheckConstraint("ck_exposure_record_version", "record_version >= 1");

                            t.HasCheckConstraint("ck_exposure_sequence", "sequence >= 1");

                            t.HasCheckConstraint("ck_exposure_status", "status IN ('OPEN', 'CLOSED')");

                            t.HasCheckConstraint("ck_exposure_sub_status", "sub_status IS NULL OR sub_status IN ('NEW', 'IN_PROGRESS')");
                        });
                });

            modelBuilder.Entity("CoreIns.Modules.Claims.Persistence.FnolSnapshotRow", b =>
                {
                    b.Property<Guid>("FnolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("fnol_id");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("channel");

                    b.Property<Guid>("ClaimId")
                        .HasColumnType("uuid")
                        .HasColumnName("claim_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Jurisdiction")
                        .IsRequired()
                        .HasColumnType("char(2)")
                        .HasColumnName("jurisdiction");

                    b.Property<Guid>("LegalEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("legal_entity_id");

                    b.Property<byte[]>("PayloadEncrypted")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("payload_encrypted");

                    b.Property<int>("RecordVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("record_version");

                    b.Property<Guid?>("ReporterPartyId")
                        .HasColumnType("uuid")
                        .HasColumnName("reporter_party_id");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("submitted_at");

                    b.HasKey("FnolId")
                        .HasName("pk_fnol_snapshot");

                    b.HasIndex("ClaimId")
                        .IsUnique()
                        .HasDatabaseName("ux_fnol_snapshot_claim");

                    b.ToTable("fnol_snapshot", "clm", t =>
                        {
                            t.HasCheckConstraint("ck_fnol_snapshot_jurisdiction", "jurisdiction ~ '^[A-Z]{2}$'");

                            t.HasCheckConstraint("ck_fnol_snapshot_record_version", "record_version >= 1");
                        });
                });

            modelBuilder.Entity("CoreIns.Modules.Claims.Persistence.IncidentRow", b =>
                {
                    b.Property<Guid>("IncidentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("incident_id");

                    b.Property<Guid>("ClaimId")
                        .HasColumnType("uuid")
                        .HasColumnName("claim_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.PrimitiveCollection<string[]>("DamageAreas")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("damage_areas");

                    b.Property<bool?>("Drivable")
                        .HasColumnType("boolean")
                        .HasColumnName("drivable");

                    b.Property<string>("IncidentType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("incident_type");

                    b.Property<string>("Jurisdiction")
                        .IsRequired()
                        .HasColumnType("char(2)")
                        .HasColumnName("jurisdiction");

                    b.Property<Guid>("LegalEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("legal_entity_id");

                    b.Property<int>("RecordVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("record_version");

                    b.Property<string>("VehicleRef")
                        .HasColumnType("text")
                        .HasColumnName("vehicle_ref");

                    b.HasKey("IncidentId")
                        .HasName("pk_incident");

                    b.HasIndex("ClaimId")
                        .HasDatabaseName("ix_incident_claim");

                    b.ToTable("incident", "clm", t =>
                        {
                            t.HasCheckConstraint("ck_incident_jurisdiction", "jurisdiction ~ '^[A-Z]{2}$'");

                            t.HasCheckConstraint("ck_incident_record_version", "record_version >= 1");

                            t.HasCheckConstraint("ck_incident_type", "incident_type IN ('VEHICLE', 'PROPERTY', 'INJURY', 'LIABILITY')");
                        });
                });

            modelBuilder.Entity("CoreIns.Modules.Claims.Persistence.ClaimRow", b =>
                {
                    b.HasOne("CoreIns.Modules.Claims.Persistence.ClaimRow", null)
                        .WithMany()
                        .HasForeignKey("DuplicateOfClaimId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_claim_duplicate_of");
                });

            modelBuilder.Entity("CoreIns.Modules.Claims.Persistence.ClaimantRow", b =>
                {
                    b.HasOne("CoreIns.Modules.Claims.Persistence.ClaimRow", null)
                        .WithMany()
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_claimant_claim");
                });

            modelBuilder.Entity("CoreIns.Modules.Claims.Persistence.ExposureRow", b =>
                {
                    b.HasOne("CoreIns.Modules.Claims.Persistence.ClaimRow", null)
                        .WithMany()
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_exposure_claim");

                    b.HasOne("CoreIns.Modules.Claims.Persistence.ClaimantRow", null)
                        .WithMany()
                        .HasForeignKey("ClaimantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_exposure_claimant");

                    b.HasOne("CoreIns.Modules.Claims.Persistence.IncidentRow", null)
                        .WithMany()
                        .HasForeignKey("IncidentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_exposure_incident");
                });

            modelBuilder.Entity("CoreIns.Modules.Claims.Persistence.FnolSnapshotRow", b =>
                {
                    b.HasOne("CoreIns.Modules.Claims.Persistence.ClaimRow", null)
                        .WithMany()
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_fnol_snapshot_claim");
                });

            modelBuilder.Entity("CoreIns.Modules.Claims.Persistence.IncidentRow", b =>
                {
                    b.HasOne("CoreIns.Modules.Claims.Persistence.ClaimRow", null)
                        .WithMany()
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_incident_claim");
                });
#pragma warning restore 612, 618
        }
    }
}
