// <auto-generated />
using System;
using CoreIns.Modules.Claims.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CoreIns.Modules.Claims.Persistence.Migrations
{
    [DbContext(typeof(ClaimsDbContext))]
    partial class ClaimsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("clm")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CoreIns.Modules.Claims.Persistence.ClaimPaymentRow", b =>
                {
                    b.Property<Guid>("ClaimPaymentId")
                        .HasColumnType("uuid")
                        .HasColumnName("claim_payment_id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("amount");

                    b.Property<string>("ApprovalEvidenceRef")
                        .HasColumnType("text")
                        .HasColumnName("approval_evidence_ref");

                    b.Property<Guid>("ClaimId")
                        .HasColumnType("uuid")
                        .HasColumnName("claim_id");

                    b.Property<DateTime?>("ClearedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("cleared_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("char(3)")
                        .HasColumnName("currency");

                    b.Property<string>("DisbursementContentHash")
                        .IsRequired()
                        .HasColumnType("char(64)")
                        .HasColumnName("disbursement_content_hash");

                    b.Property<Guid?>("DisbursementId")
                        .HasColumnType("uuid")
                        .HasColumnName("disbursement_id");

                    b.Property<Guid>("ExposureId")
                        .HasColumnType("uuid")
                        .HasColumnName("exposure_id");

                    b.Property<string>("HoldReason")
                        .HasColumnType("text")
                        .HasColumnName("hold_reason");

                    b.Property<DateTime?>("IssuedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("issued_at");

                    b.Property<string>("Jurisdiction")
                        .IsRequired()
                        .HasColumnType("char(2)")
                        .HasColumnName("jurisdiction");

                    b.Property<Guid>("LegalEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("legal_entity_id");

                    b.Property<string>("MaskedAccount")
                        .HasColumnType("text")
                        .HasColumnName("masked_account");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("method");

                    b.Property<Guid>("PayeeAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("payee_account_id");

                    b.Property<Guid>("PayeePartyId")
                        .HasColumnType("uuid")
                        .HasColumnName("payee_party_id");

                    b.Property<string>("PaymentType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payment_type");

                    b.Property<int>("RecordVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("record_version");

                    b.Property<Guid>("SetId")
                        .HasColumnType("uuid")
                        .HasColumnName("set_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("submitted_at");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("ClaimPaymentId")
                        .HasName("pk_claim_payment");

                    b.HasIndex("ClaimId")
                        .HasDatabaseName("ix_claim_payment_claim");

                    b.HasIndex("DisbursementId")
                        .IsUnique()
                        .HasDatabaseName("ux_claim_payment_disbursement")
                        .HasFilter("disbursement_id IS NOT NULL");

                    b.HasIndex("ExposureId");

                    b.HasIndex("SetId")
                        .HasDatabaseName("ix_claim_payment_set");

                    b.ToTable("claim_payment", "clm", t =>
                        {
                            t.HasCheckConstraint("ck_claim_payment_amount", "amount > 0");

                            t.HasCheckConstraint("ck_claim_payment_hold_shape", "status <> 'ON_HOLD' OR hold_reason IS NOT NULL");

                            t.HasCheckConstraint("ck_claim_payment_jurisdiction", "jurisdiction ~ '^[A-Z]{2}$'");

                            t.HasCheckConstraint("ck_claim_payment_record_version", "record_version >= 1");

                            t.HasCheckConstraint("ck_claim_payment_status", "status IN ('PENDING', 'APPROVED', 'ON_HOLD', 'SUBMITTED', 'ISSUED', 'CLEARED', 'REJECTED')");

                            t.HasCheckConstraint("ck_claim_payment_submitted_shape", "status NOT IN ('SUBMITTED', 'ISSUED', 'CLEARED') OR disbursement_id IS NOT NULL");

                            t.HasCheckConstraint("ck_claim_payment_type", "payment_type IN ('PARTIAL', 'FINAL')");
                        });
                });

            modelBuilder.Entity("CoreIns.Modules.Claims.Persistence.ClaimRow", b =>
                {
                    b.Property<Guid>("ClaimId")
                        .HasColumnType("uuid")
                        .HasColumnName("claim_id");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("channel");

                    b.Property<string>("ClaimNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("claim_number");

                    b.Property<string>("CloseReasonCode")
                        .HasColumnType("text")
                        .HasColumnName("close_reason_code");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("closed_at");

                    b.Property<bool>("CoverageInQuestion")
                        .HasColumnType("boolean")
                        .HasColumnName("coverage_in_question");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<byte[]>("DescriptionEncrypted")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("description_encrypted");

                    b.Property<Guid?>("DuplicateOfClaimId")
                        .HasColumnType("uuid")
                        .HasColumnName("duplicate_of_claim_id");

                    b.Property<string>("DuplicateReasonCode")
                        .HasColumnType("text")
                        .HasColumnName("duplicate_reason_code");

                    b.Property<string>("Handler")
                        .HasColumnType("text")
                        .HasColumnName("handler");

                    b.Property<string>("HandlingSegment")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("handling_segment");

                    b.Property<Guid>("InsuredPartyId")
                        .HasColumnType("uuid")
                        .HasColumnName("insured_party_id");

                    b.Property<string>("Jurisdiction")
                        .IsRequired()
                        .HasColumnType("char(2)")
                        .HasColumnName("jurisdiction");

                    b.Property<int>("LastExposureSequence")
                        .HasColumnType("integer")
                        .HasColumnName("last_exposure_sequence");

                    b.Property<int>("LastTransactionSequence")
                        .HasColumnType("integer")
                        .HasColumnName("last_transaction_sequence");

                    b.Property<Guid>("LegalEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("legal_entity_id");

                    b.Property<string>("LineOfBusiness")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("line_of_business");

                    b.Property<DateTime>("LossAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("loss_at");

                    b.Property<string>("LossCause")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("loss_cause");

                    b.Property<DateOnly>("LossDate")
                        .HasColumnType("date")
                        .HasColumnName("loss_date");

                    b.Property<byte[]>("LossLocationEncrypted")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("loss_location_encrypted");

                    b.Property<DateOnly>("NoticeOn")
                        .HasColumnType("date")
                        .HasColumnName("notice_on");

                    b.Property<string>("Outcome")
                        .HasColumnType("text")
                        .HasColumnName("outcome");

                    b.Property<Guid>("PolicyId")
                        .HasColumnType("uuid")
                        .HasColumnName("policy_id");

                    b.Property<bool>("PolicyInForceAtLoss")
                        .HasColumnType("boolean")
                        .HasColumnName("policy_in_force_at_loss");

                    b.Property<string>("PolicyNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("policy_number");

                    b.Property<string>("PolicyStatusAtLoss")
                        .HasColumnType("text")
                        .HasColumnName("policy_status_at_loss");

                    b.Property<Guid?>("PolicyTermId")
                        .HasColumnType("uuid")
                        .HasColumnName("policy_term_id");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("product_code");

                    b.Property<string>("ProductVersion")
                        .HasColumnType("text")
                        .HasColumnName("product_version");

                    b.Property<string>("ReceiptMedium")
                        .HasColumnType("text")
                        .HasColumnName("receipt_medium");

                    b.Property<int>("RecordVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("record_version");

                    b.Property<int>("ReopenCount")
                        .HasColumnType("integer")
                        .HasColumnName("reopen_count");

                    b.PrimitiveCollection<string[]>("SnapshotCoverageCodes")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("snapshot_coverage_codes");

                    b.Property<DateTime>("SnapshotKnownAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("snapshot_known_at");

                    b.Property<string>("SnapshotRef")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("snapshot_ref");

                    b.Property<Guid?>("SnapshotSegmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("snapshot_segment_id");

                    b.Property<string>("SnapshotStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("snapshot_status");

                    b.Property<DateTime>("SnapshotValidAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("snapshot_valid_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("SubStatus")
                        .HasColumnType("text")
                        .HasColumnName("sub_status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("ClaimId")
                        .HasName("pk_claim");

                    b.HasIndex("DuplicateOfClaimId");

                    b.HasIndex("LegalEntityId", "ClaimNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_claim_number");

                    b.HasIndex("LegalEntityId", "InsuredPartyId")
                        .HasDatabaseName("ix_claim_insured_party");

                    b.HasIndex("LegalEntityId", "PolicyNumber")
                        .HasDatabaseName("ix_claim_policy_number");

                    b.HasIndex("LegalEntityId", "PolicyId", "LossDate")
                        .HasDatabaseName("ix_claim_policy_loss_date");

                    b.ToTable("claim", "clm", t =>
                        {
                            t.HasCheckConstraint("ck_claim_closed_shape", "status <> 'CLOSED' OR (sub_status IS NULL AND outcome IS NOT NULL AND closed_at IS NOT NULL)");

                            t.HasCheckConstraint("ck_claim_exposure_sequence", "last_exposure_sequence >= 0");

                            t.HasCheckConstraint("ck_claim_jurisdiction", "jurisdiction ~ '^[A-Z]{2}$'");

                            t.HasCheckConstraint("ck_claim_notice_after_loss", "notice_on >= loss_date");

                            t.HasCheckConstraint("ck_claim_open_shape", "status <> 'OPEN' OR (sub_status IS NOT NULL AND outcome IS NULL AND closed_at IS NULL)");

                            t.HasCheckConstraint("ck_claim_outcome", "outcome IS NULL OR outcome IN ('COMPLETED', 'DENIED', 'WITHDRAWN', 'DUPLICATE', 'NO_PAYMENT')");

                            t.HasCheckConstraint("ck_claim_record_version", "record_version >= 1");

                            t.HasCheckConstraint("ck_claim_snapshot_status", "snapshot_status IN ('PENDING', 'VERIFIED', 'REVERIFICATION_REQUIRED')");

                            t.HasCheckConstraint("ck_claim_status", "status IN ('DRAFT', 'OPEN', 'CLOSED')");

                            t.HasCheckConstraint("ck_claim_sub_status", "sub_status IS NULL OR sub_status IN ('NEW', 'IN_PROGRESS', 'UNDER_INVESTIGATION', 'SETTLED')");

                            t.HasCheckConstraint("ck_claim_transaction_sequence", "last_transaction_sequence >= 0");
                        });
                });

            modelBuilder.Entity("CoreIns.Modules.Claims.Persistence.ClaimantRow", b =>
                {
                    b.Property<Guid>("ClaimantId")
                        .HasColumnType("uuid")
                        .HasColumnName("claimant_id");

                    b.Property<Guid>("ClaimId")
                        .HasColumnType("uuid")
                        .HasColumnName("claim_id");

                    b.Property<string>("ClaimantType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("claimant_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Jurisdiction")
                        .IsRequired()
                        .HasColumnType("char(2)")
                        .HasColumnName("jurisdiction");

                    b.Property<Guid>("LegalEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("legal_entity_id");

                    b.Property<Guid>("PartyId")
                        .HasColumnType("uuid")
                        .HasColumnName("party_id");

                    b.Property<int>("RecordVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("record_version");

                    b.HasKey("ClaimantId")
                        .HasName("pk_claimant");

                    b.HasIndex("ClaimId", "PartyId")
                        .IsUnique()
                        .HasDatabaseName("ux_claimant_claim_party");

                    b.HasIndex("LegalEntityId", "PartyId")
                        .HasDatabaseName("ix_claimant_party");

                    b.ToTable("claimant", "clm", t =>
                        {
                            t.HasCheckConstraint("ck_claimant_jurisdiction", "jurisdiction ~ '^[A-Z]{2}$'");

                            t.HasCheckConstraint("ck_claimant_record_version", "record_version >= 1");

                            t.HasCheckConstraint("ck_claimant_type", "claimant_type IN ('INSURED', 'THIRD_PARTY', 'GUARANTEE_FUND', 'BUREAU')");
                        });
                });

            modelBuilder.Entity("CoreIns.Modules.Claims.Persistence.ExposureRow", b =>
                {
                    b.Property<Guid>("ExposureId")
                        .HasColumnType("uuid")
                        .HasColumnName("exposure_id");

                    b.Property<Guid>("ClaimId")
                        .HasColumnType("uuid")
                        .HasColumnName("claim_id");

                    b.Property<Guid>("ClaimantId")
                        .HasColumnType("uuid")
                        .HasColumnName("claimant_id");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("closed_at");

                    b.Property<string>("CoverageCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("coverage_code");

                    b.Property<string>("CoverageDecision")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("coverage_decision");

                    b.Property<string>("CoverageIndication")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("coverage_indication");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("DuplicateReason")
                        .HasColumnType("text")
                        .HasColumnName("duplicate_reason");

                    b.Property<string>("ExposureNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("exposure_number");

                    b.Property<Guid?>("IncidentId")
                        .HasColumnType("uuid")
                        .HasColumnName("incident_id");

                    b.Property<string>("Jurisdiction")
                        .IsRequired()
                        .HasColumnType("char(2)")
                        .HasColumnName("jurisdiction");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<Guid>("LegalEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("legal_entity_id");

                    b.Property<string>("Outcome")
                        .HasColumnType("text")
                        .HasColumnName("outcome");

                    b.Property<int>("RecordVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("record_version");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer")
                        .HasColumnName("sequence");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("SubStatus")
                        .HasColumnType("text")
                        .HasColumnName("sub_status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("ExposureId")
                        .HasName("pk_exposure");

                    b.HasIndex("ClaimantId");

                    b.HasIndex("IncidentId");

                    b.HasIndex("ClaimId", "Sequence")
                        .IsUnique()
                        .HasDatabaseName("ux_exposure_claim_sequence");

                    b.HasIndex("LegalEntityId", "ExposureNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_exposure_number");

                    b.HasIndex("ClaimId", "CoverageCode", "ClaimantId", "IncidentId")
                        .IsUnique()
                        .HasDatabaseName("ux_exposure_open_coverage_claimant_incident")
                        .HasFilter("status = 'OPEN' AND duplicate_reason IS NULL");

                    NpgsqlIndexBuilderExtensions.AreNullsDistinct(b.HasIndex("ClaimId", "CoverageCode", "ClaimantId", "IncidentId"), false);

                    b.ToTable("exposure", "clm", t =>
                        {
                            t.HasCheckConstraint("ck_exposure_closed_shape", "status <> 'CLOSED' OR (sub_status IS NULL AND outcome IS NOT NULL AND closed_at IS NOT NULL)");

                            t.HasCheckConstraint("ck_exposure_decision", "coverage_decision IN ('PENDING', 'COVERED', 'COVERED_WITH_RESERVATION', 'PARTIALLY_COVERED', 'NOT_COVERED')");

                            t.HasCheckConstraint("ck_exposure_indication", "coverage_indication IN ('COVERED', 'NOT_COVERED', 'IN_QUESTION')");

                            t.HasCheckConstraint("ck_exposure_jurisdiction", "jurisdiction ~ '^[A-Z]{2}$'");

                            t.HasCheckConstraint("ck_exposure_open_shape", "status <> 'OPEN' OR (sub_status IS NOT NULL AND outcome IS NULL AND closed_at IS NULL)");

                            t.HasCheckConstraint("ck_exposure_outcome", "outcome IS NULL OR outcome IN ('COMPLETED', 'DENIED', 'WITHDRAWN', 'DUPLICATE', 'NO_PAYMENT')");

                            t.HasCheckConstraint("ck_exposure_record_version", "record_version >= 1");

                            t.HasCheckConstraint("ck_exposure_sequence", "sequence >= 1");

                            t.HasCheckConstraint("ck_exposure_status", "status IN ('OPEN', 'CLOSED')");

                            t.HasCheckConstraint("ck_exposure_sub_status", "sub_status IS NULL OR sub_status IN ('NEW', 'IN_PROGRESS')");
                        });
                });

            modelBuilder.Entity("CoreIns.Modules.Claims.Persistence.FinancialTransactionRow", b =>
                {
                    b.Property<Guid>("TxnId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("txn_id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("amount");

                    b.Property<Guid>("ClaimId")
                        .HasColumnType("uuid")
                        .HasColumnName("claim_id");

                    b.Property<Guid?>("ClaimPaymentId")
                        .HasColumnType("uuid")
                        .HasColumnName("claim_payment_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("char(3)")
                        .HasColumnName("currency");

                    b.Property<bool?>("Eroding")
                        .HasColumnType("boolean")
                        .HasColumnName("eroding");

                    b.Property<Guid>("ExposureId")
                        .HasColumnType("uuid")
                        .HasColumnName("exposure_id");

                    b.Property<decimal>("FunctionalAmount")
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("functional_amount");

                    b.Property<string>("FunctionalCurrency")
                        .IsRequired()
                        .HasColumnType("char(3)")
                        .HasColumnName("functional_currency");

                    b.Property<Guid?>("FxRateId")
                        .HasColumnType("uuid")
                        .HasColumnName("fx_rate_id");

                    b.Property<decimal>("GroupAmount")
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("group_amount");

                    b.Property<string>("GroupCurrency")
                        .IsRequired()
                        .HasColumnType("char(3)")
                        .HasColumnName("group_currency");

                    b.Property<string>("Jurisdiction")
                        .IsRequired()
                        .HasColumnType("char(2)")
                        .HasColumnName("jurisdiction");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<Guid>("LegalEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("legal_entity_id");

                    b.Property<string>("PaymentType")
                        .HasColumnType("text")
                        .HasColumnName("payment_type");

                    b.Property<bool>("Proposed")
                        .HasColumnType("boolean")
                        .HasColumnName("proposed");

                    b.Property<string>("ReasonCode")
                        .HasColumnType("text")
                        .HasColumnName("reason_code");

                    b.Property<int>("RecordVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("record_version");

                    b.Property<Guid>("ReserveLineId")
                        .HasColumnType("uuid")
                        .HasColumnName("reserve_line_id");

                    b.Property<Guid?>("ReversesTxnId")
                        .HasColumnType("uuid")
                        .HasColumnName("reverses_txn_id");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer")
                        .HasColumnName("sequence");

                    b.Property<Guid>("SetId")
                        .HasColumnType("uuid")
                        .HasColumnName("set_id");

                    b.Property<DateOnly>("TransactionDate")
                        .HasColumnType("date")
                        .HasColumnName("transaction_date");

                    b.Property<string>("TxnNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("txn_number");

                    b.HasKey("TxnId")
                        .HasName("pk_financial_transaction");

                    b.HasIndex("ReserveLineId")
                        .HasDatabaseName("ix_financial_transaction_line");

                    b.HasIndex("ReversesTxnId");

                    b.HasIndex("SetId")
                        .HasDatabaseName("ix_financial_transaction_set");

                    b.HasIndex("ClaimId", "Sequence")
                        .IsUnique()
                        .HasDatabaseName("ux_financial_transaction_claim_sequence");

                    b.ToTable("financial_transaction", "clm", t =>
                        {
                            t.HasCheckConstraint("ck_financial_transaction_amount", "amount <> 0");

                            t.HasCheckConstraint("ck_financial_transaction_currencies", "currency ~ '^[A-Z]{3}$' AND functional_currency ~ '^[A-Z]{3}$' AND group_currency ~ '^[A-Z]{3}$'");

                            t.HasCheckConstraint("ck_financial_transaction_jurisdiction", "jurisdiction ~ '^[A-Z]{2}$'");

                            t.HasCheckConstraint("ck_financial_transaction_kind", "kind IN ('RESERVE', 'PAYMENT')");

                            t.HasCheckConstraint("ck_financial_transaction_payment_shape", "kind <> 'PAYMENT' OR (amount > 0 AND eroding IS NOT NULL AND payment_type IS NOT NULL AND claim_payment_id IS NOT NULL)");

                            t.HasCheckConstraint("ck_financial_transaction_record_version", "record_version >= 1");

                            t.HasCheckConstraint("ck_financial_transaction_reserve_shape", "kind <> 'RESERVE' OR (eroding IS NULL AND payment_type IS NULL AND claim_payment_id IS NULL)");

                            t.HasCheckConstraint("ck_financial_transaction_sequence", "sequence >= 1");
                        });
                });

            modelBuilder.Entity("CoreIns.Modules.Claims.Persistence.FnolSnapshotRow", b =>
                {
                    b.Property<Guid>("FnolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("fnol_id");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("channel");

                    b.Property<Guid>("ClaimId")
                        .HasColumnType("uuid")
                        .HasColumnName("claim_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Jurisdiction")
                        .IsRequired()
                        .HasColumnType("char(2)")
                        .HasColumnName("jurisdiction");

                    b.Property<Guid>("LegalEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("legal_entity_id");

                    b.Property<byte[]>("PayloadEncrypted")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("payload_encrypted");

                    b.Property<int>("RecordVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("record_version");

                    b.Property<Guid?>("ReporterPartyId")
                        .HasColumnType("uuid")
                        .HasColumnName("reporter_party_id");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("submitted_at");

                    b.HasKey("FnolId")
                        .HasName("pk_fnol_snapshot");

                    b.HasIndex("ClaimId")
                        .IsUnique()
                        .HasDatabaseName("ux_fnol_snapshot_claim");

                    b.ToTable("fnol_snapshot", "clm", t =>
                        {
                            t.HasCheckConstraint("ck_fnol_snapshot_jurisdiction", "jurisdiction ~ '^[A-Z]{2}$'");

                            t.HasCheckConstraint("ck_fnol_snapshot_record_version", "record_version >= 1");
                        });
                });

            modelBuilder.Entity("CoreIns.Modules.Claims.Persistence.IncidentRow", b =>
                {
                    b.Property<Guid>("IncidentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("incident_id");

                    b.Property<Guid>("ClaimId")
                        .HasColumnType("uuid")
                        .HasColumnName("claim_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.PrimitiveCollection<string[]>("DamageAreas")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("damage_areas");

                    b.Property<bool?>("Drivable")
                        .HasColumnType("boolean")
                        .HasColumnName("drivable");

                    b.Property<string>("IncidentType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("incident_type");

                    b.Property<string>("Jurisdiction")
                        .IsRequired()
                        .HasColumnType("char(2)")
                        .HasColumnName("jurisdiction");

                    b.Property<Guid>("LegalEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("legal_entity_id");

                    b.Property<int>("RecordVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("record_version");

                    b.Property<string>("VehicleRef")
                        .HasColumnType("text")
                        .HasColumnName("vehicle_ref");

                    b.HasKey("IncidentId")
                        .HasName("pk_incident");

                    b.HasIndex("ClaimId")
                        .HasDatabaseName("ix_incident_claim");

                    b.ToTable("incident", "clm", t =>
                        {
                            t.HasCheckConstraint("ck_incident_jurisdiction", "jurisdiction ~ '^[A-Z]{2}$'");

                            t.HasCheckConstraint("ck_incident_record_version", "record_version >= 1");

                            t.HasCheckConstraint("ck_incident_type", "incident_type IN ('VEHICLE', 'PROPERTY', 'INJURY', 'LIABILITY')");
                        });
                });

            modelBuilder.Entity("CoreIns.Modules.Claims.Persistence.PayeeAccountViewRow", b =>
                {
                    b.Property<Guid>("ClaimId")
                        .HasColumnType("uuid")
                        .HasColumnName("claim_id");

                    b.Property<Guid>("PayeeAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("payee_account_id");

                    b.Property<DateOnly?>("CoolingOffUntil")
                        .HasColumnType("date")
                        .HasColumnName("cooling_off_until");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsChange")
                        .HasColumnType("boolean")
                        .HasColumnName("is_change");

                    b.Property<string>("Jurisdiction")
                        .IsRequired()
                        .HasColumnType("char(2)")
                        .HasColumnName("jurisdiction");

                    b.Property<Guid>("LegalEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("legal_entity_id");

                    b.Property<string>("MaskedIban")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("masked_iban");

                    b.Property<Guid>("PartyId")
                        .HasColumnType("uuid")
                        .HasColumnName("party_id");

                    b.Property<int>("RecordVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("record_version");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<string>("VerificationStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("verification_status");

                    b.HasKey("ClaimId", "PayeeAccountId")
                        .HasName("pk_payee_account_view");

                    b.ToTable("payee_account_view", "clm", t =>
                        {
                            t.HasCheckConstraint("ck_payee_account_view_jurisdiction", "jurisdiction ~ '^[A-Z]{2}$'");

                            t.HasCheckConstraint("ck_payee_account_view_record_version", "record_version >= 1");
                        });
                });

            modelBuilder.Entity("CoreIns.Modules.Claims.Persistence.ReserveLineRow", b =>
                {
                    b.Property<Guid>("ReserveLineId")
                        .HasColumnType("uuid")
                        .HasColumnName("reserve_line_id");

                    b.Property<Guid>("ClaimId")
                        .HasColumnType("uuid")
                        .HasColumnName("claim_id");

                    b.Property<string>("CostCategory")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cost_category");

                    b.Property<string>("CostType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cost_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("char(3)")
                        .HasColumnName("currency");

                    b.Property<Guid>("ExposureId")
                        .HasColumnType("uuid")
                        .HasColumnName("exposure_id");

                    b.Property<bool>("FinalFlag")
                        .HasColumnType("boolean")
                        .HasColumnName("final_flag");

                    b.Property<string>("Jurisdiction")
                        .IsRequired()
                        .HasColumnType("char(2)")
                        .HasColumnName("jurisdiction");

                    b.Property<Guid>("LegalEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("legal_entity_id");

                    b.Property<int>("RecordVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("record_version");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("ReserveLineId")
                        .HasName("pk_reserve_line");

                    b.HasIndex("ClaimId")
                        .HasDatabaseName("ix_reserve_line_claim");

                    b.HasIndex("ExposureId", "CostType", "CostCategory", "Currency")
                        .IsUnique()
                        .HasDatabaseName("ux_reserve_line_key");

                    b.ToTable("reserve_line", "clm", t =>
                        {
                            t.HasCheckConstraint("ck_reserve_line_cost_type", "cost_type IN ('INDEMNITY', 'EXPENSE_ALLOCATED', 'EXPENSE_UNALLOCATED', 'STATUTORY_INTEREST')");

                            t.HasCheckConstraint("ck_reserve_line_currency", "currency ~ '^[A-Z]{3}$'");

                            t.HasCheckConstraint("ck_reserve_line_jurisdiction", "jurisdiction ~ '^[A-Z]{2}$'");

                            t.HasCheckConstraint("ck_reserve_line_record_version", "record_version >= 1");
                        });
                });

            modelBuilder.Entity("CoreIns.Modules.Claims.Persistence.ReverificationRow", b =>
                {
                    b.Property<Guid>("ReverificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("reverification_id");

                    b.Property<Guid>("CauseEventId")
                        .HasColumnType("uuid")
                        .HasColumnName("cause_event_id");

                    b.Property<string>("CauseEventType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cause_event_type");

                    b.Property<Guid>("ClaimId")
                        .HasColumnType("uuid")
                        .HasColumnName("claim_id");

                    b.Property<byte[]>("CommentEncrypted")
                        .HasColumnType("bytea")
                        .HasColumnName("comment_encrypted");

                    b.Property<bool?>("CoverageInQuestion")
                        .HasColumnType("boolean")
                        .HasColumnName("coverage_in_question");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DecidedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("decided_at");

                    b.Property<string>("DecidedBy")
                        .HasColumnType("text")
                        .HasColumnName("decided_by");

                    b.Property<string>("Jurisdiction")
                        .IsRequired()
                        .HasColumnType("char(2)")
                        .HasColumnName("jurisdiction");

                    b.Property<Guid>("LegalEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("legal_entity_id");

                    b.Property<string>("NewSnapshotRef")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("new_snapshot_ref");

                    b.Property<string>("OldSnapshotRef")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("old_snapshot_ref");

                    b.Property<DateTime>("RaisedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("raised_at");

                    b.Property<string>("ReasonCode")
                        .HasColumnType("text")
                        .HasColumnName("reason_code");

                    b.Property<int>("RecordVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("record_version");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("ReverificationId")
                        .HasName("pk_reverification");

                    b.HasIndex("ClaimId", "CauseEventId")
                        .IsUnique()
                        .HasDatabaseName("ux_reverification_claim_cause");

                    b.HasIndex("ClaimId", "Status")
                        .HasDatabaseName("ix_reverification_claim_status");

                    b.ToTable("reverification", "clm", t =>
                        {
                            t.HasCheckConstraint("ck_reverification_decided_shape", "(status = 'OPEN') = (decided_at IS NULL)");

                            t.HasCheckConstraint("ck_reverification_jurisdiction", "jurisdiction ~ '^[A-Z]{2}$'");

                            t.HasCheckConstraint("ck_reverification_reason", "status = 'OPEN' OR reason_code IS NOT NULL");

                            t.HasCheckConstraint("ck_reverification_record_version", "record_version >= 1");

                            t.HasCheckConstraint("ck_reverification_refs", "old_snapshot_ref <> new_snapshot_ref");

                            t.HasCheckConstraint("ck_reverification_status", "status IN ('OPEN', 'KEPT', 'ADOPTED')");
                        });
                });

            modelBuilder.Entity("CoreIns.Modules.Claims.Persistence.SetApprovalRow", b =>
                {
                    b.Property<Guid>("ApprovalRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("approval_request_id");

                    b.Property<string>("ApprovalType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("approval_type");

                    b.Property<decimal>("AuthorityAmount")
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("authority_amount");

                    b.Property<string>("AuthorityCostType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("authority_cost_type");

                    b.Property<string>("AuthorityType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("authority_type");

                    b.Property<string>("Checker")
                        .HasColumnType("text")
                        .HasColumnName("checker");

                    b.Property<Guid?>("CheckerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("checker_user_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("char(3)")
                        .HasColumnName("currency");

                    b.Property<DateTime?>("DecidedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("decided_at");

                    b.Property<string>("Jurisdiction")
                        .IsRequired()
                        .HasColumnType("char(2)")
                        .HasColumnName("jurisdiction");

                    b.Property<Guid>("LegalEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("legal_entity_id");

                    b.Property<string>("PayloadHash")
                        .IsRequired()
                        .HasColumnType("char(64)")
                        .HasColumnName("payload_hash");

                    b.Property<int>("RecordVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("record_version");

                    b.Property<Guid>("SetId")
                        .HasColumnType("uuid")
                        .HasColumnName("set_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("SubjectId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subject_id");

                    b.Property<string>("SubjectType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subject_type");

                    b.HasKey("ApprovalRequestId")
                        .HasName("pk_set_approval");

                    b.HasIndex("SetId", "AuthorityType", "AuthorityCostType")
                        .IsUnique()
                        .HasDatabaseName("ux_set_approval_bucket");

                    b.ToTable("set_approval", "clm", t =>
                        {
                            t.HasCheckConstraint("ck_set_approval_amount", "authority_amount > 0");

                            t.HasCheckConstraint("ck_set_approval_jurisdiction", "jurisdiction ~ '^[A-Z]{2}$'");

                            t.HasCheckConstraint("ck_set_approval_record_version", "record_version >= 1");

                            t.HasCheckConstraint("ck_set_approval_status", "status IN ('PENDING', 'APPROVED', 'REJECTED')");
                        });
                });

            modelBuilder.Entity("CoreIns.Modules.Claims.Persistence.TransactionSetRow", b =>
                {
                    b.Property<Guid>("SetId")
                        .HasColumnType("uuid")
                        .HasColumnName("set_id");

                    b.Property<decimal?>("ApprovalAuthorityAmount")
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("approval_authority_amount");

                    b.Property<string>("ApprovalAuthorityCostType")
                        .HasColumnType("text")
                        .HasColumnName("approval_authority_cost_type");

                    b.Property<string>("ApprovalAuthorityType")
                        .HasColumnType("text")
                        .HasColumnName("approval_authority_type");

                    b.Property<string>("ApprovalPayloadHash")
                        .HasColumnType("char(64)")
                        .HasColumnName("approval_payload_hash");

                    b.Property<Guid?>("ApprovalRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("approval_request_id");

                    b.Property<string>("ApprovalSubjectId")
                        .HasColumnType("text")
                        .HasColumnName("approval_subject_id");

                    b.Property<string>("ApprovalSubjectType")
                        .HasColumnType("text")
                        .HasColumnName("approval_subject_type");

                    b.Property<string>("ApprovalType")
                        .HasColumnType("text")
                        .HasColumnName("approval_type");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("approved_at");

                    b.Property<string>("Approver")
                        .HasColumnType("text")
                        .HasColumnName("approver");

                    b.Property<Guid?>("ApproverUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("approver_user_id");

                    b.PrimitiveCollection<Guid[]>("AuthorityCheckIds")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("authority_check_ids");

                    b.Property<string>("BasisHash")
                        .IsRequired()
                        .HasColumnType("char(64)")
                        .HasColumnName("basis_hash");

                    b.Property<Guid>("ClaimId")
                        .HasColumnType("uuid")
                        .HasColumnName("claim_id");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasColumnType("char(64)")
                        .HasColumnName("content_hash");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<long>("CreatedTxid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("created_txid")
                        .HasDefaultValueSql("txid_current()");

                    b.Property<DateTime?>("DecidedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("decided_at");

                    b.Property<bool>("FourEyes")
                        .HasColumnType("boolean")
                        .HasColumnName("four_eyes");

                    b.Property<string>("Jurisdiction")
                        .IsRequired()
                        .HasColumnType("char(2)")
                        .HasColumnName("jurisdiction");

                    b.Property<Guid>("LegalEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("legal_entity_id");

                    b.Property<int>("RecordVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("record_version");

                    b.Property<string>("ReferralRole")
                        .HasColumnType("text")
                        .HasColumnName("referral_role");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("text")
                        .HasColumnName("rejection_reason");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("submitted_at");

                    b.Property<string>("Submitter")
                        .HasColumnType("text")
                        .HasColumnName("submitter");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("SetId")
                        .HasName("pk_transaction_set");

                    b.HasIndex("ApprovalRequestId")
                        .IsUnique()
                        .HasDatabaseName("ux_transaction_set_approval_request")
                        .HasFilter("approval_request_id IS NOT NULL");

                    b.HasIndex("ClaimId")
                        .HasDatabaseName("ix_transaction_set_claim");

                    b.ToTable("transaction_set", "clm", t =>
                        {
                            t.HasCheckConstraint("ck_transaction_set_approved_shape", "status NOT IN ('APPROVED', 'POSTED') OR approved_at IS NOT NULL");

                            t.HasCheckConstraint("ck_transaction_set_jurisdiction", "jurisdiction ~ '^[A-Z]{2}$'");

                            t.HasCheckConstraint("ck_transaction_set_pending_shape", "status <> 'PENDING_APPROVAL' OR (approval_request_id IS NOT NULL AND approval_payload_hash IS NOT NULL)");

                            t.HasCheckConstraint("ck_transaction_set_record_version", "record_version >= 1");

                            t.HasCheckConstraint("ck_transaction_set_rejected_shape", "status <> 'REJECTED' OR rejection_reason IS NOT NULL");

                            t.HasCheckConstraint("ck_transaction_set_status", "status IN ('DRAFT', 'SUBMITTED', 'PENDING_APPROVAL', 'APPROVED', 'REJECTED', 'POSTED')");
                        });
                });

            modelBuilder.Entity("CoreIns.Modules.Claims.Persistence.ClaimPaymentRow", b =>
                {
                    b.HasOne("CoreIns.Modules.Claims.Persistence.ExposureRow", null)
                        .WithMany()
                        .HasForeignKey("ExposureId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_claim_payment_exposure");

                    b.HasOne("CoreIns.Modules.Claims.Persistence.TransactionSetRow", null)
                        .WithMany()
                        .HasForeignKey("SetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_claim_payment_set");
                });

            modelBuilder.Entity("CoreIns.Modules.Claims.Persistence.ClaimRow", b =>
                {
                    b.HasOne("CoreIns.Modules.Claims.Persistence.ClaimRow", null)
                        .WithMany()
                        .HasForeignKey("DuplicateOfClaimId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_claim_duplicate_of");
                });

            modelBuilder.Entity("CoreIns.Modules.Claims.Persistence.ClaimantRow", b =>
                {
                    b.HasOne("CoreIns.Modules.Claims.Persistence.ClaimRow", null)
                        .WithMany()
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_claimant_claim");
                });

            modelBuilder.Entity("CoreIns.Modules.Claims.Persistence.ExposureRow", b =>
                {
                    b.HasOne("CoreIns.Modules.Claims.Persistence.ClaimRow", null)
                        .WithMany()
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_exposure_claim");

                    b.HasOne("CoreIns.Modules.Claims.Persistence.ClaimantRow", null)
                        .WithMany()
                        .HasForeignKey("ClaimantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_exposure_claimant");

                    b.HasOne("CoreIns.Modules.Claims.Persistence.IncidentRow", null)
                        .WithMany()
                        .HasForeignKey("IncidentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_exposure_incident");
                });

            modelBuilder.Entity("CoreIns.Modules.Claims.Persistence.FinancialTransactionRow", b =>
                {
                    b.HasOne("CoreIns.Modules.Claims.Persistence.ReserveLineRow", null)
                        .WithMany()
                        .HasForeignKey("ReserveLineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_financial_transaction_line");

                    b.HasOne("CoreIns.Modules.Claims.Persistence.FinancialTransactionRow", null)
                        .WithMany()
                        .HasForeignKey("ReversesTxnId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_financial_transaction_reverses");

                    b.HasOne("CoreIns.Modules.Claims.Persistence.TransactionSetRow", null)
                        .WithMany()
                        .HasForeignKey("SetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_financial_transaction_set");
                });

            modelBuilder.Entity("CoreIns.Modules.Claims.Persistence.FnolSnapshotRow", b =>
                {
                    b.HasOne("CoreIns.Modules.Claims.Persistence.ClaimRow", null)
                        .WithMany()
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_fnol_snapshot_claim");
                });

            modelBuilder.Entity("CoreIns.Modules.Claims.Persistence.IncidentRow", b =>
                {
                    b.HasOne("CoreIns.Modules.Claims.Persistence.ClaimRow", null)
                        .WithMany()
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_incident_claim");
                });

            modelBuilder.Entity("CoreIns.Modules.Claims.Persistence.PayeeAccountViewRow", b =>
                {
                    b.HasOne("CoreIns.Modules.Claims.Persistence.ClaimRow", null)
                        .WithMany()
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_payee_account_view_claim");
                });

            modelBuilder.Entity("CoreIns.Modules.Claims.Persistence.ReserveLineRow", b =>
                {
                    b.HasOne("CoreIns.Modules.Claims.Persistence.ClaimRow", null)
                        .WithMany()
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_reserve_line_claim");

                    b.HasOne("CoreIns.Modules.Claims.Persistence.ExposureRow", null)
                        .WithMany()
                        .HasForeignKey("ExposureId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_reserve_line_exposure");
                });

            modelBuilder.Entity("CoreIns.Modules.Claims.Persistence.ReverificationRow", b =>
                {
                    b.HasOne("CoreIns.Modules.Claims.Persistence.ClaimRow", null)
                        .WithMany()
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_reverification_claim");
                });

            modelBuilder.Entity("CoreIns.Modules.Claims.Persistence.SetApprovalRow", b =>
                {
                    b.HasOne("CoreIns.Modules.Claims.Persistence.TransactionSetRow", null)
                        .WithMany()
                        .HasForeignKey("SetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_set_approval_set");
                });

            modelBuilder.Entity("CoreIns.Modules.Claims.Persistence.TransactionSetRow", b =>
                {
                    b.HasOne("CoreIns.Modules.Claims.Persistence.ClaimRow", null)
                        .WithMany()
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_transaction_set_claim");
                });
#pragma warning restore 612, 618
        }
    }
}
