// <auto-generated />
using System;
using CoreIns.Modules.Billing.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CoreIns.Modules.Billing.Persistence.Migrations
{
    [DbContext(typeof(BillingDbContext))]
    [Migration("20261007195947_InitialBilling")]
    partial class InitialBilling
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("bil")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CoreIns.Modules.Billing.Persistence.AllocationRow", b =>
                {
                    b.Property<Guid>("AllocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("allocation_id");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("actor");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("amount");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("char(3)")
                        .HasColumnName("currency");

                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("invoice_id");

                    b.Property<Guid>("InvoiceItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("invoice_item_id");

                    b.Property<Guid>("LegalEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("legal_entity_id");

                    b.Property<Guid>("ReceiptId")
                        .HasColumnType("uuid")
                        .HasColumnName("receipt_id");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("recorded_at");

                    b.Property<string>("RuleId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("rule_id");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<Guid>("TermId")
                        .HasColumnType("uuid")
                        .HasColumnName("term_id");

                    b.HasKey("AllocationId")
                        .HasName("pk_allocation");

                    b.HasIndex("InvoiceItemId")
                        .HasDatabaseName("ix_allocation_item");

                    b.HasIndex("ReceiptId")
                        .HasDatabaseName("ix_allocation_receipt");

                    b.ToTable("allocation", "bil", t =>
                        {
                            t.HasCheckConstraint("ck_allocation_amount", "amount > 0");

                            t.HasCheckConstraint("ck_allocation_currency", "currency ~ '^[A-Z]{3}$'");

                            t.HasCheckConstraint("ck_allocation_source", "source IN ('RULE', 'AI', 'MANUAL')");
                        });
                });

            modelBuilder.Entity("CoreIns.Modules.Billing.Persistence.BillingAccountRow", b =>
                {
                    b.Property<Guid>("BillingAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("billing_account_id");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("account_number");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("char(3)")
                        .HasColumnName("currency");

                    b.Property<string>("Jurisdiction")
                        .IsRequired()
                        .HasColumnType("char(2)")
                        .HasColumnName("jurisdiction");

                    b.Property<Guid>("LegalEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("legal_entity_id");

                    b.Property<Guid>("PayerPartyId")
                        .HasColumnType("uuid")
                        .HasColumnName("payer_party_id");

                    b.Property<int>("RecordVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("record_version");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("BillingAccountId")
                        .HasName("pk_billing_account");

                    b.HasIndex("LegalEntityId", "AccountNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_billing_account_number");

                    b.HasIndex("LegalEntityId", "PayerPartyId", "Currency")
                        .IsUnique()
                        .HasDatabaseName("ux_billing_account_active_payer")
                        .HasFilter("status = 'ACTIVE'");

                    b.ToTable("billing_account", "bil", t =>
                        {
                            t.HasCheckConstraint("ck_billing_account_currency", "currency ~ '^[A-Z]{3}$'");

                            t.HasCheckConstraint("ck_billing_account_jurisdiction", "jurisdiction ~ '^[A-Z]{2}$'");

                            t.HasCheckConstraint("ck_billing_account_record_version", "record_version >= 1");

                            t.HasCheckConstraint("ck_billing_account_status", "status IN ('ACTIVE', 'SUSPENDED', 'CLOSING', 'CLOSED')");
                        });
                });

            modelBuilder.Entity("CoreIns.Modules.Billing.Persistence.ChargeRow", b =>
                {
                    b.Property<Guid>("ChargeId")
                        .HasColumnType("uuid")
                        .HasColumnName("charge_id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("amount");

                    b.Property<DateOnly>("BookingDate")
                        .HasColumnType("date")
                        .HasColumnName("booking_date");

                    b.Property<string>("ChargeCategory")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("charge_category");

                    b.Property<string>("ChargeType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("charge_type");

                    b.Property<string>("CorrelationKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("correlation_key");

                    b.Property<string>("CoverageCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("coverage_code");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("char(3)")
                        .HasColumnName("currency");

                    b.Property<string>("DeltaKind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("delta_kind");

                    b.Property<string>("ElementLocator")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("element_locator");

                    b.Property<string>("FiscalCategoryKey")
                        .HasColumnType("text")
                        .HasColumnName("fiscal_category_key");

                    b.Property<Guid>("LegalEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("legal_entity_id");

                    b.Property<Guid>("PolicyId")
                        .HasColumnType("uuid")
                        .HasColumnName("policy_id");

                    b.Property<string>("QuarantineReason")
                        .HasColumnType("text")
                        .HasColumnName("quarantine_reason");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("received_at");

                    b.Property<Guid>("SetId")
                        .HasColumnType("uuid")
                        .HasColumnName("set_id");

                    b.Property<int>("SetIndex")
                        .HasColumnType("integer")
                        .HasColumnName("set_index");

                    b.Property<int>("SetSize")
                        .HasColumnType("integer")
                        .HasColumnName("set_size");

                    b.Property<Guid>("SourceEventId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_event_id");

                    b.Property<long>("SourceSequence")
                        .HasColumnType("bigint")
                        .HasColumnName("source_sequence");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("TaxTreatmentRef")
                        .HasColumnType("text")
                        .HasColumnName("tax_treatment_ref");

                    b.Property<Guid>("TermId")
                        .HasColumnType("uuid")
                        .HasColumnName("term_id");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("transaction_id");

                    b.Property<DateOnly>("ValidFrom")
                        .HasColumnType("date")
                        .HasColumnName("valid_from");

                    b.Property<DateOnly?>("ValidTo")
                        .HasColumnType("date")
                        .HasColumnName("valid_to");

                    b.Property<Guid?>("WrittenEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("written_entry_id");

                    b.HasKey("ChargeId")
                        .HasName("pk_charge");

                    b.HasIndex("TermId")
                        .HasDatabaseName("ix_charge_term");

                    b.HasIndex("SetId", "SetIndex")
                        .IsUnique()
                        .HasDatabaseName("ux_charge_set_member");

                    b.ToTable("charge", "bil", t =>
                        {
                            t.HasCheckConstraint("ck_charge_currency", "currency ~ '^[A-Z]{3}$'");

                            t.HasCheckConstraint("ck_charge_quarantine", "(status = 'QUARANTINED') = (quarantine_reason IS NOT NULL)");

                            t.HasCheckConstraint("ck_charge_set", "set_index >= 1 AND set_index <= set_size");

                            t.HasCheckConstraint("ck_charge_status", "status IN ('RECEIVED', 'WRITTEN', 'ACCRUED', 'SCHEDULED', 'QUARANTINED')");

                            t.HasCheckConstraint("ck_charge_valid", "valid_to IS NULL OR valid_to > valid_from");
                        });
                });

            modelBuilder.Entity("CoreIns.Modules.Billing.Persistence.IntakeExceptionRow", b =>
                {
                    b.Property<Guid>("ExceptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("exception_id");

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("detail");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<Guid>("LegalEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("legal_entity_id");

                    b.Property<DateTime>("RaisedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("raised_at");

                    b.Property<string>("ReasonCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reason_code");

                    b.Property<Guid?>("SourceEventId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_event_id");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subject");

                    b.HasKey("ExceptionId")
                        .HasName("pk_intake_exception");

                    b.HasIndex("Kind", "Subject", "ReasonCode")
                        .IsUnique()
                        .HasDatabaseName("ux_intake_exception");

                    b.ToTable("intake_exception", "bil");
                });

            modelBuilder.Entity("CoreIns.Modules.Billing.Persistence.InvoiceItemRow", b =>
                {
                    b.Property<Guid>("InvoiceItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("invoice_item_id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("amount");

                    b.Property<string>("ChargeCategory")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("charge_category");

                    b.Property<Guid>("ChargeId")
                        .HasColumnType("uuid")
                        .HasColumnName("charge_id");

                    b.Property<string>("ChargeType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("charge_type");

                    b.Property<string>("CoverageCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("coverage_code");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("char(3)")
                        .HasColumnName("currency");

                    b.Property<string>("ElementLocator")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("element_locator");

                    b.Property<string>("FiscalCategoryKey")
                        .HasColumnType("text")
                        .HasColumnName("fiscal_category_key");

                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("invoice_id");

                    b.Property<Guid>("LegalEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("legal_entity_id");

                    b.Property<int>("LineNo")
                        .HasColumnType("integer")
                        .HasColumnName("line_no");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.Property<Guid>("TermId")
                        .HasColumnType("uuid")
                        .HasColumnName("term_id");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("transaction_id");

                    b.Property<DateOnly>("ValidFrom")
                        .HasColumnType("date")
                        .HasColumnName("valid_from");

                    b.Property<DateOnly?>("ValidTo")
                        .HasColumnType("date")
                        .HasColumnName("valid_to");

                    b.HasKey("InvoiceItemId")
                        .HasName("pk_invoice_item");

                    b.HasIndex("ChargeId")
                        .IsUnique()
                        .HasDatabaseName("ux_invoice_item_charge");

                    b.HasIndex("InvoiceId")
                        .HasDatabaseName("ix_invoice_item_invoice");

                    b.ToTable("invoice_item", "bil", t =>
                        {
                            t.HasCheckConstraint("ck_invoice_item_amount", "amount > 0");

                            t.HasCheckConstraint("ck_invoice_item_currency", "currency ~ '^[A-Z]{3}$'");

                            t.HasCheckConstraint("ck_invoice_item_state", "state IN ('PLANNED', 'BILLED', 'OPEN', 'SETTLED', 'CANCELLED', 'WRITTEN_OFF')");
                        });
                });

            modelBuilder.Entity("CoreIns.Modules.Billing.Persistence.InvoiceRow", b =>
                {
                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("invoice_id");

                    b.Property<Guid>("BillingAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("billing_account_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("char(3)")
                        .HasColumnName("currency");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("date")
                        .HasColumnName("due_date");

                    b.Property<Guid?>("FiscalDocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("fiscal_document_id");

                    b.Property<string>("FiscalDocumentType")
                        .HasColumnType("text")
                        .HasColumnName("fiscal_document_type");

                    b.Property<string>("FiscalMark")
                        .HasColumnType("text")
                        .HasColumnName("fiscal_mark");

                    b.Property<string>("FiscalNumber")
                        .HasColumnType("text")
                        .HasColumnName("fiscal_number");

                    b.PrimitiveCollection<string[]>("FiscalRejectionCodes")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("fiscal_rejection_codes");

                    b.Property<string>("FiscalSeries")
                        .HasColumnType("text")
                        .HasColumnName("fiscal_series");

                    b.Property<string>("FiscalStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("fiscal_status");

                    b.Property<string>("FiscalTriggerPoint")
                        .HasColumnType("text")
                        .HasColumnName("fiscal_trigger_point");

                    b.Property<string>("FiscalUid")
                        .HasColumnType("text")
                        .HasColumnName("fiscal_uid");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("invoice_number");

                    b.Property<DateOnly>("IssueDate")
                        .HasColumnType("date")
                        .HasColumnName("issue_date");

                    b.Property<string>("Jurisdiction")
                        .IsRequired()
                        .HasColumnType("char(2)")
                        .HasColumnName("jurisdiction");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<Guid>("LegalEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("legal_entity_id");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("method");

                    b.Property<Guid>("PolicyId")
                        .HasColumnType("uuid")
                        .HasColumnName("policy_id");

                    b.Property<int>("RecordVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("record_version");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.Property<Guid>("TermId")
                        .HasColumnType("uuid")
                        .HasColumnName("term_id");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("total");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("transaction_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("InvoiceId")
                        .HasName("pk_invoice");

                    b.HasIndex("BillingAccountId")
                        .HasDatabaseName("ix_invoice_account");

                    b.HasIndex("FiscalDocumentId")
                        .HasDatabaseName("ix_invoice_fiscal_document");

                    b.HasIndex("PolicyId")
                        .HasDatabaseName("ix_invoice_policy");

                    b.HasIndex("LegalEntityId", "InvoiceNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_invoice_number");

                    b.HasIndex("TransactionId", "Kind")
                        .IsUnique()
                        .HasDatabaseName("ux_invoice_transaction");

                    b.ToTable("invoice", "bil", t =>
                        {
                            t.HasCheckConstraint("ck_invoice_currency", "currency ~ '^[A-Z]{3}$'");

                            t.HasCheckConstraint("ck_invoice_fiscal_status", "fiscal_status IN ('NOT_REQUESTED', 'PENDING', 'REGISTERED', 'REJECTED', 'REQUEST_FAILED')");

                            t.HasCheckConstraint("ck_invoice_kind", "kind IN ('INVOICE', 'CREDIT_NOTE')");

                            t.HasCheckConstraint("ck_invoice_record_version", "record_version >= 1");

                            t.HasCheckConstraint("ck_invoice_state", "state IN ('PLANNED', 'BILLED', 'DUE', 'PAID', 'PARTIALLY_PAID', 'OVERDUE', 'WRITTEN_OFF', 'REVERSED')");

                            t.HasCheckConstraint("ck_invoice_total", "total > 0");
                        });
                });

            modelBuilder.Entity("CoreIns.Modules.Billing.Persistence.LedgerAccountRow", b =>
                {
                    b.Property<string>("AccountCode")
                        .HasColumnType("text")
                        .HasColumnName("account_code");

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("account_type");

                    b.Property<string>("NameEl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name_el");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name_en");

                    b.Property<string>("NormalBalance")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("normal_balance");

                    b.HasKey("AccountCode")
                        .HasName("pk_ledger_account");

                    b.ToTable("ledger_account", "bil", t =>
                        {
                            t.HasCheckConstraint("ck_ledger_account_code", "account_code ~ '^LA-[0-9]{2,3}$'");

                            t.HasCheckConstraint("ck_ledger_account_normal", "normal_balance IN ('DEBIT', 'CREDIT', 'EITHER')");
                        });
                });

            modelBuilder.Entity("CoreIns.Modules.Billing.Persistence.LedgerEntryRow", b =>
                {
                    b.Property<Guid>("EntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("entry_id");

                    b.Property<DateOnly>("AccountingDate")
                        .HasColumnType("date")
                        .HasColumnName("accounting_date");

                    b.Property<Guid>("BillingAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("billing_account_id");

                    b.Property<DateOnly>("BusinessDate")
                        .HasColumnType("date")
                        .HasColumnName("business_date");

                    b.Property<Guid?>("CauseEventId")
                        .HasColumnType("uuid")
                        .HasColumnName("cause_event_id");

                    b.Property<string>("CauseOperation")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cause_operation");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("correlation_id");

                    b.Property<string>("EntryType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("entry_type");

                    b.Property<string>("Jurisdiction")
                        .IsRequired()
                        .HasColumnType("char(2)")
                        .HasColumnName("jurisdiction");

                    b.Property<Guid>("LegalEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("legal_entity_id");

                    b.Property<string>("LineageKeys")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("lineage_keys");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("recorded_at");

                    b.Property<Guid?>("ReversesEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("reverses_entry_id");

                    b.HasKey("EntryId")
                        .HasName("pk_ledger_entry");

                    b.HasIndex("BillingAccountId")
                        .HasDatabaseName("ix_ledger_entry_account");

                    b.HasIndex("LegalEntityId", "AccountingDate")
                        .HasDatabaseName("ix_ledger_entry_date");

                    b.ToTable("ledger_entry", "bil", t =>
                        {
                            t.HasCheckConstraint("ck_ledger_entry_jurisdiction", "jurisdiction ~ '^[A-Z]{2}$'");
                        });
                });

            modelBuilder.Entity("CoreIns.Modules.Billing.Persistence.LedgerLineRow", b =>
                {
                    b.Property<Guid>("LineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("line_id");

                    b.Property<string>("AccountCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("account_code");

                    b.Property<Guid?>("AllocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("allocation_id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("amount");

                    b.Property<string>("BillMode")
                        .HasColumnType("text")
                        .HasColumnName("bill_mode");

                    b.Property<Guid?>("BillingAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("billing_account_id");

                    b.Property<string>("ChargeCategory")
                        .HasColumnType("text")
                        .HasColumnName("charge_category");

                    b.Property<Guid?>("ChargeId")
                        .HasColumnType("uuid")
                        .HasColumnName("charge_id");

                    b.Property<string>("ChargeType")
                        .HasColumnType("text")
                        .HasColumnName("charge_type");

                    b.Property<string>("CoverageCode")
                        .HasColumnType("text")
                        .HasColumnName("coverage_code");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("char(3)")
                        .HasColumnName("currency");

                    b.Property<Guid>("EntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("entry_id");

                    b.Property<Guid?>("InvoiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("invoice_id");

                    b.Property<Guid?>("InvoiceItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("invoice_item_id");

                    b.Property<Guid>("LegalEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("legal_entity_id");

                    b.Property<int>("LineNo")
                        .HasColumnType("integer")
                        .HasColumnName("line_no");

                    b.Property<Guid?>("PolicyId")
                        .HasColumnType("uuid")
                        .HasColumnName("policy_id");

                    b.Property<string>("ProductCode")
                        .HasColumnType("text")
                        .HasColumnName("product_code");

                    b.Property<Guid?>("ReceiptId")
                        .HasColumnType("uuid")
                        .HasColumnName("receipt_id");

                    b.Property<string>("RuleId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("rule_id");

                    b.Property<string>("Side")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("side");

                    b.Property<Guid?>("TermId")
                        .HasColumnType("uuid")
                        .HasColumnName("term_id");

                    b.Property<Guid?>("TransactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("transaction_id");

                    b.HasKey("LineId")
                        .HasName("pk_ledger_line");

                    b.HasIndex("AccountCode");

                    b.HasIndex("BillingAccountId", "AccountCode")
                        .HasDatabaseName("ix_ledger_line_account");

                    b.HasIndex("EntryId", "LineNo")
                        .IsUnique()
                        .HasDatabaseName("ux_ledger_line_no");

                    b.ToTable("ledger_line", "bil", t =>
                        {
                            t.HasCheckConstraint("ck_ledger_line_amount", "amount > 0");

                            t.HasCheckConstraint("ck_ledger_line_currency", "currency ~ '^[A-Z]{3}$'");

                            t.HasCheckConstraint("ck_ledger_line_side", "side IN ('DEBIT', 'CREDIT')");
                        });
                });

            modelBuilder.Entity("CoreIns.Modules.Billing.Persistence.LedgerRuleRow", b =>
                {
                    b.Property<string>("RuleId")
                        .HasColumnType("text")
                        .HasColumnName("rule_id");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.Property<string>("AmountExpression")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("amount_expression");

                    b.Property<string>("BillMode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("bill_mode");

                    b.Property<string>("ChargeCategory")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("charge_category");

                    b.Property<string>("CreditAccount")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("credit_account");

                    b.Property<string>("DebitAccount")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("debit_account");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_type");

                    b.Property<string>("Jurisdiction")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("jurisdiction");

                    b.Property<string>("Qualifier")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("qualifier");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<DateOnly>("ValidFrom")
                        .HasColumnType("date")
                        .HasColumnName("valid_from");

                    b.Property<DateOnly?>("ValidTo")
                        .HasColumnType("date")
                        .HasColumnName("valid_to");

                    b.HasKey("RuleId", "Version")
                        .HasName("pk_ledger_rule");

                    b.HasIndex("CreditAccount");

                    b.HasIndex("DebitAccount");

                    b.ToTable("ledger_rule", "bil", t =>
                        {
                            t.HasCheckConstraint("ck_ledger_rule_version", "version >= 1");
                        });
                });

            modelBuilder.Entity("CoreIns.Modules.Billing.Persistence.PlanInstanceRow", b =>
                {
                    b.Property<Guid>("TermId")
                        .HasColumnType("uuid")
                        .HasColumnName("term_id");

                    b.Property<string>("ArtefactHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("artefact_hash");

                    b.Property<string>("BillMode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("bill_mode");

                    b.Property<Guid>("BillingAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("billing_account_id");

                    b.Property<Guid>("BoundTransactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("bound_transaction_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid>("LegalEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("legal_entity_id");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("method");

                    b.Property<string>("PlanCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("plan_code");

                    b.Property<Guid>("PlanInstanceId")
                        .HasColumnType("uuid")
                        .HasColumnName("plan_instance_id");

                    b.Property<Guid>("PolicyId")
                        .HasColumnType("uuid")
                        .HasColumnName("policy_id");

                    b.Property<string>("PolicyNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("policy_number");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("product_code");

                    b.Property<string>("ProductVersion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("product_version");

                    b.Property<Guid>("SourceEventId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_event_id");

                    b.Property<long>("SourceSequence")
                        .HasColumnType("bigint")
                        .HasColumnName("source_sequence");

                    b.Property<DateOnly>("TermFrom")
                        .HasColumnType("date")
                        .HasColumnName("term_from");

                    b.Property<int>("TermNumber")
                        .HasColumnType("integer")
                        .HasColumnName("term_number");

                    b.Property<DateOnly>("TermTo")
                        .HasColumnType("date")
                        .HasColumnName("term_to");

                    b.HasKey("TermId")
                        .HasName("pk_plan_instance");

                    b.HasIndex("BillingAccountId")
                        .HasDatabaseName("ix_plan_instance_account");

                    b.HasIndex("PlanInstanceId")
                        .IsUnique()
                        .HasDatabaseName("ux_plan_instance_id");

                    b.HasIndex("PolicyId")
                        .HasDatabaseName("ix_plan_instance_policy");

                    b.ToTable("plan_instance", "bil", t =>
                        {
                            t.HasCheckConstraint("ck_plan_instance_bill_mode", "bill_mode IN ('DIRECT_BILL', 'AGENCY_BILL')");

                            t.HasCheckConstraint("ck_plan_instance_term", "term_to > term_from");
                        });
                });

            modelBuilder.Entity("CoreIns.Modules.Billing.Persistence.ReceiptRow", b =>
                {
                    b.Property<Guid>("ReceiptId")
                        .HasColumnType("uuid")
                        .HasColumnName("receipt_id");

                    b.Property<DateOnly>("AccountingDate")
                        .HasColumnType("date")
                        .HasColumnName("accounting_date");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("amount");

                    b.Property<string>("BankReference")
                        .HasColumnType("text")
                        .HasColumnName("bank_reference");

                    b.Property<Guid>("BillingAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("billing_account_id");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("channel");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("char(3)")
                        .HasColumnName("currency");

                    b.Property<Guid?>("InvoiceRef")
                        .HasColumnType("uuid")
                        .HasColumnName("invoice_ref");

                    b.Property<string>("Jurisdiction")
                        .IsRequired()
                        .HasColumnType("char(2)")
                        .HasColumnName("jurisdiction");

                    b.Property<Guid>("LegalEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("legal_entity_id");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("method");

                    b.Property<string>("ReceiptNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("receipt_number");

                    b.Property<int>("RecordVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("record_version");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("recorded_at");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.Property<string>("SuspenseReason")
                        .HasColumnType("text")
                        .HasColumnName("suspense_reason");

                    b.Property<DateOnly>("ValueDate")
                        .HasColumnType("date")
                        .HasColumnName("value_date");

                    b.HasKey("ReceiptId")
                        .HasName("pk_receipt");

                    b.HasIndex("BillingAccountId")
                        .HasDatabaseName("ix_receipt_account");

                    b.HasIndex("LegalEntityId", "ReceiptNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_receipt_number");

                    b.ToTable("receipt", "bil", t =>
                        {
                            t.HasCheckConstraint("ck_receipt_amount", "amount > 0");

                            t.HasCheckConstraint("ck_receipt_currency", "currency ~ '^[A-Z]{3}$'");

                            t.HasCheckConstraint("ck_receipt_method", "method IN ('BANK_TRANSFER', 'CASHIER')");

                            t.HasCheckConstraint("ck_receipt_record_version", "record_version >= 1");

                            t.HasCheckConstraint("ck_receipt_state", "state IN ('RECEIVED', 'ALLOCATED', 'PARTIALLY_ALLOCATED', 'SUSPENSE', 'REVERSED', 'REFUNDED')");

                            t.HasCheckConstraint("ck_receipt_suspense", "(state = 'SUSPENSE') = (suspense_reason IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("CoreIns.Modules.Billing.Persistence.AllocationRow", b =>
                {
                    b.HasOne("CoreIns.Modules.Billing.Persistence.InvoiceItemRow", null)
                        .WithMany()
                        .HasForeignKey("InvoiceItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_allocation_item");

                    b.HasOne("CoreIns.Modules.Billing.Persistence.ReceiptRow", null)
                        .WithMany()
                        .HasForeignKey("ReceiptId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_allocation_receipt");
                });

            modelBuilder.Entity("CoreIns.Modules.Billing.Persistence.InvoiceItemRow", b =>
                {
                    b.HasOne("CoreIns.Modules.Billing.Persistence.ChargeRow", null)
                        .WithMany()
                        .HasForeignKey("ChargeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_invoice_item_charge");

                    b.HasOne("CoreIns.Modules.Billing.Persistence.InvoiceRow", null)
                        .WithMany()
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_invoice_item_invoice");
                });

            modelBuilder.Entity("CoreIns.Modules.Billing.Persistence.InvoiceRow", b =>
                {
                    b.HasOne("CoreIns.Modules.Billing.Persistence.BillingAccountRow", null)
                        .WithMany()
                        .HasForeignKey("BillingAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_invoice_account");
                });

            modelBuilder.Entity("CoreIns.Modules.Billing.Persistence.LedgerLineRow", b =>
                {
                    b.HasOne("CoreIns.Modules.Billing.Persistence.LedgerAccountRow", null)
                        .WithMany()
                        .HasForeignKey("AccountCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ledger_line_account");

                    b.HasOne("CoreIns.Modules.Billing.Persistence.LedgerEntryRow", null)
                        .WithMany()
                        .HasForeignKey("EntryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ledger_line_entry");
                });

            modelBuilder.Entity("CoreIns.Modules.Billing.Persistence.LedgerRuleRow", b =>
                {
                    b.HasOne("CoreIns.Modules.Billing.Persistence.LedgerAccountRow", null)
                        .WithMany()
                        .HasForeignKey("CreditAccount")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ledger_rule_credit");

                    b.HasOne("CoreIns.Modules.Billing.Persistence.LedgerAccountRow", null)
                        .WithMany()
                        .HasForeignKey("DebitAccount")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ledger_rule_debit");
                });

            modelBuilder.Entity("CoreIns.Modules.Billing.Persistence.PlanInstanceRow", b =>
                {
                    b.HasOne("CoreIns.Modules.Billing.Persistence.BillingAccountRow", null)
                        .WithMany()
                        .HasForeignKey("BillingAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_plan_instance_account");
                });

            modelBuilder.Entity("CoreIns.Modules.Billing.Persistence.ReceiptRow", b =>
                {
                    b.HasOne("CoreIns.Modules.Billing.Persistence.BillingAccountRow", null)
                        .WithMany()
                        .HasForeignKey("BillingAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_receipt_account");
                });
#pragma warning restore 612, 618
        }
    }
}
