// <auto-generated />
using System;
using CoreIns.Modules.Market.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CoreIns.Modules.Market.Persistence.Migrations
{
    [DbContext(typeof(MarketDbContext))]
    partial class MarketDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("mkt")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CoreIns.Modules.Market.Persistence.LegalEntityRow", b =>
                {
                    b.Property<Guid>("LegalEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("legal_entity_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("FunctionalCurrency")
                        .IsRequired()
                        .HasColumnType("char(3)")
                        .HasColumnName("functional_currency");

                    b.Property<string>("HomeJurisdiction")
                        .IsRequired()
                        .HasColumnType("char(2)")
                        .HasColumnName("home_jurisdiction");

                    b.Property<bool>("IsTestEntity")
                        .HasColumnType("boolean")
                        .HasColumnName("is_test_entity");

                    b.Property<string>("LatinName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("latin_name");

                    b.Property<string>("NativeName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("native_name");

                    b.Property<string>("PackId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("pack_id");

                    b.Property<int>("RecordVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("record_version");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("timezone");

                    b.HasKey("LegalEntityId")
                        .HasName("pk_legal_entity");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_legal_entity_code");

                    b.ToTable("legal_entity", "mkt", t =>
                        {
                            t.HasCheckConstraint("ck_legal_entity_functional_currency", "functional_currency ~ '^[A-Z]{3}$'");

                            t.HasCheckConstraint("ck_legal_entity_home_jurisdiction", "home_jurisdiction ~ '^[A-Z]{2}$'");

                            t.HasCheckConstraint("ck_legal_entity_status", "status IN ('PLANNED', 'ONBOARDING', 'ACTIVE', 'RUN_OFF', 'CLOSED')");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
