// <auto-generated />
using System;
using CoreIns.Modules.Product.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CoreIns.Modules.Product.Persistence.Migrations
{
    [DbContext(typeof(ProductDbContext))]
    [Migration("20261007181254_InitialProduct")]
    partial class InitialProduct
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("pfc")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CoreIns.Modules.Product.Persistence.ArtifactRow", b =>
                {
                    b.Property<string>("ArtefactHash")
                        .HasColumnType("char(64)")
                        .HasColumnName("artefact_hash");

                    b.Property<string>("CanonicalJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("canonical_json");

                    b.Property<int>("SizeBytes")
                        .HasColumnType("integer")
                        .HasColumnName("size_bytes");

                    b.Property<DateTime>("StoredAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("stored_at");

                    b.HasKey("ArtefactHash")
                        .HasName("pk_artifact");

                    b.ToTable("artifact", "pfc", t =>
                        {
                            t.HasCheckConstraint("ck_artifact_hash", "artefact_hash ~ '^[0-9a-f]{64}$'");

                            t.HasCheckConstraint("ck_artifact_size", "size_bytes > 0");
                        });
                });

            modelBuilder.Entity("CoreIns.Modules.Product.Persistence.ProductRow", b =>
                {
                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("CustomerType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("customer_type");

                    b.Property<string>("Jurisdiction")
                        .IsRequired()
                        .HasColumnType("char(2)")
                        .HasColumnName("jurisdiction");

                    b.Property<Guid>("LegalEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("legal_entity_id");

                    b.Property<string>("LineCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("line_code");

                    b.Property<string>("LineFamily")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("line_family");

                    b.Property<string>("NameEl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name_el");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name_en");

                    b.Property<string>("ProductType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("product_type");

                    b.Property<int>("RecordVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("record_version");

                    b.HasKey("ProductId")
                        .HasName("pk_product");

                    b.HasIndex("LegalEntityId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ux_product_code");

                    b.ToTable("product", "pfc", t =>
                        {
                            t.HasCheckConstraint("ck_product_jurisdiction", "jurisdiction ~ '^[A-Z]{2}$'");

                            t.HasCheckConstraint("ck_product_record_version", "record_version >= 1");
                        });
                });

            modelBuilder.Entity("CoreIns.Modules.Product.Persistence.ProductVersionRow", b =>
                {
                    b.Property<Guid>("ProductVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_version_id");

                    b.Property<string>("ArtefactHash")
                        .IsRequired()
                        .HasColumnType("char(64)")
                        .HasColumnName("artefact_hash");

                    b.PrimitiveCollection<string[]>("Channels")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("channels");

                    b.Property<string>("ContractCurrency")
                        .IsRequired()
                        .HasColumnType("char(3)")
                        .HasColumnName("contract_currency");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsAbstract")
                        .HasColumnType("boolean")
                        .HasColumnName("is_abstract");

                    b.Property<string>("Jurisdiction")
                        .IsRequired()
                        .HasColumnType("char(2)")
                        .HasColumnName("jurisdiction");

                    b.Property<Guid>("LegalEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("legal_entity_id");

                    b.Property<string>("LifecycleSubstate")
                        .HasColumnType("text")
                        .HasColumnName("lifecycle_substate");

                    b.Property<DateTime?>("LockedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("locked_at");

                    b.Property<int>("Major")
                        .HasColumnType("integer")
                        .HasColumnName("major");

                    b.Property<int>("Minor")
                        .HasColumnType("integer")
                        .HasColumnName("minor");

                    b.Property<DateOnly>("NewBusinessFrom")
                        .HasColumnType("date")
                        .HasColumnName("new_business_from");

                    b.Property<DateOnly?>("NewBusinessTo")
                        .HasColumnType("date")
                        .HasColumnName("new_business_to");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<int>("RecordVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("record_version");

                    b.Property<DateOnly>("RenewalFrom")
                        .HasColumnType("date")
                        .HasColumnName("renewal_from");

                    b.Property<DateOnly?>("RenewalTo")
                        .HasColumnType("date")
                        .HasColumnName("renewal_to");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("integer")
                        .HasColumnName("schema_version");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("ProductVersionId")
                        .HasName("pk_product_version");

                    b.HasIndex("ArtefactHash");

                    b.HasIndex("LegalEntityId", "Status")
                        .HasDatabaseName("ix_product_version_resolution");

                    b.HasIndex("ProductId", "Major", "Minor")
                        .IsUnique()
                        .HasDatabaseName("ux_product_version_number");

                    b.ToTable("product_version", "pfc", t =>
                        {
                            t.HasCheckConstraint("ck_product_version_channels", "cardinality(channels) >= 1");

                            t.HasCheckConstraint("ck_product_version_hash", "artefact_hash ~ '^[0-9a-f]{64}$'");

                            t.HasCheckConstraint("ck_product_version_nb_window", "new_business_to IS NULL OR new_business_to > new_business_from");

                            t.HasCheckConstraint("ck_product_version_number", "major >= 0 AND minor >= 0");

                            t.HasCheckConstraint("ck_product_version_renewal_window", "renewal_to IS NULL OR renewal_to > renewal_from");

                            t.HasCheckConstraint("ck_product_version_status", "status IN ('DRAFT', 'SUBMITTED', 'APPROVED', 'LOCKED', 'RETIRED')");

                            t.HasCheckConstraint("ck_product_version_substate", "lifecycle_substate IN ('ACTIVE', 'CLOSED_TO_NEW_BUSINESS', 'RUN_OFF')");

                            t.HasCheckConstraint("ck_product_version_substate_locked", "(status = 'LOCKED') = (lifecycle_substate IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("CoreIns.Modules.Product.Persistence.ProductVersionRow", b =>
                {
                    b.HasOne("CoreIns.Modules.Product.Persistence.ArtifactRow", null)
                        .WithMany()
                        .HasForeignKey("ArtefactHash")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_product_version_artifact");

                    b.HasOne("CoreIns.Modules.Product.Persistence.ProductRow", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_product_version_product");
                });
#pragma warning restore 612, 618
        }
    }
}
