import { readFileSync } from 'node:fs';
import { join } from 'node:path';

import { describe, expect, it } from 'vitest';

import { collectTokenNames, renderTokenNames } from '../../../scripts/gen-token-names.mjs';
import { breakpoints, cssVar, isTokenName, minWidthQuery, springs, tokenNames } from './index';

const dir = join(import.meta.dirname);

describe('tokens', () => {
  it('token-names.ts is current (run `npm run tokens:gen`)', () => {
    const generated = renderTokenNames(collectTokenNames());
    expect(readFileSync(join(dir, 'token-names.ts'), 'utf8')).toBe(generated);
  });

  it('includes the D-FE-07 tokens', () => {
    for (const name of [
      'size-row-queue-compact',
      'size-row-queue-default',
      'size-row-queue-comfortable',
      'size-table-header',
      'color-interactive-primary-sheen',
      'motion-ease-emphasized',
    ]) {
      expect(isTokenName(name)).toBe(true);
    }
    expect(tokenNames.length).toBeGreaterThan(400);
  });

  it('defines queue rows as 60/64/72 and the header as 38 px', () => {
    const css = readFileSync(join(dir, 'aegean-extensions.css'), 'utf8');
    expect(css).toMatch(/--size-row-queue-compact: 60px/);
    expect(css).toMatch(/--size-row-queue-default: 64px/);
    expect(css).toMatch(/--size-row-queue-comfortable: 72px/);
    expect(css).toMatch(/--size-table-header: 38px/);
  });

  it('keeps aegean.css exactly as generated by the design guide', () => {
    const css = readFileSync(join(dir, 'aegean.css'), 'utf8');
    expect(css.startsWith('/* Generated by tools/build_tokens.py')).toBe(true);
    // v3 primary button: white fill and the violet → blue → teal border.
    expect(css).toMatch(/--color-interactive-primary-bg: #FFFFFF/);
    expect(css).toMatch(/--gradient-cta: linear-gradient\(120deg, #8250F2 0%, #3F63F0 50%, #14988D 100%\)/);
  });

  it('exposes typed helpers', () => {
    expect(cssVar('color-text-primary')).toBe('var(--color-text-primary)');
    expect(minWidthQuery('lg')).toBe('(min-width: 1240px)');
    expect(breakpoints.md).toBe(905);
    expect(springs.snappy).toMatchObject({ stiffness: 520, damping: 42 });
  });
});
