// <auto-generated />
using System;
using System.Collections.Generic;
using CoreIns.Modules.Policy.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CoreIns.Modules.Policy.Persistence.Migrations
{
    [DbContext(typeof(PolicyDbContext))]
    [Migration("20261008134924_JobParticipants")]
    partial class JobParticipants
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("pol")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CoreIns.Modules.Policy.Persistence.ChargeLineRow", b =>
                {
                    b.Property<Guid>("ChargeId")
                        .HasColumnType("uuid")
                        .HasColumnName("charge_id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("amount");

                    b.Property<decimal>("AnnualRate")
                        .HasColumnType("numeric")
                        .HasColumnName("annual_rate");

                    b.Property<DateOnly>("BookingDate")
                        .HasColumnType("date")
                        .HasColumnName("booking_date");

                    b.Property<string>("ChargeCategory")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("charge_category");

                    b.Property<string>("ChargeType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("charge_type");

                    b.Property<string>("CorrelationKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("correlation_key");

                    b.Property<string>("CoverageCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("coverage_code");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("char(3)")
                        .HasColumnName("currency");

                    b.Property<string>("DeltaKind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("delta_kind");

                    b.Property<string>("ElementLocator")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("element_locator");

                    b.Property<Guid>("LegalEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("legal_entity_id");

                    b.Property<string>("LegalStatus")
                        .HasColumnType("text")
                        .HasColumnName("legal_status");

                    b.Property<Guid>("PolicyId")
                        .HasColumnType("uuid")
                        .HasColumnName("policy_id");

                    b.Property<bool?>("Provisional")
                        .HasColumnType("boolean")
                        .HasColumnName("provisional");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("recorded_at");

                    b.Property<int>("SetIndex")
                        .HasColumnType("integer")
                        .HasColumnName("set_index");

                    b.Property<int>("SetSize")
                        .HasColumnType("integer")
                        .HasColumnName("set_size");

                    b.Property<string>("TaxTreatmentRef")
                        .HasColumnType("text")
                        .HasColumnName("tax_treatment_ref");

                    b.Property<Guid>("TermId")
                        .HasColumnType("uuid")
                        .HasColumnName("term_id");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("transaction_id");

                    b.Property<DateOnly>("ValidFrom")
                        .HasColumnType("date")
                        .HasColumnName("valid_from");

                    b.Property<DateOnly>("ValidTo")
                        .HasColumnType("date")
                        .HasColumnName("valid_to");

                    b.HasKey("ChargeId")
                        .HasName("pk_charge_line");

                    b.HasIndex("TermId")
                        .HasDatabaseName("ix_charge_line_term");

                    b.HasIndex("TransactionId", "SetIndex")
                        .IsUnique()
                        .HasDatabaseName("ux_charge_line_set");

                    b.ToTable("charge_line", "pol", t =>
                        {
                            t.HasCheckConstraint("ck_charge_line_currency", "currency ~ '^[A-Z]{3}$'");

                            t.HasCheckConstraint("ck_charge_line_set", "set_index >= 1 AND set_index <= set_size");

                            t.HasCheckConstraint("ck_charge_line_valid", "valid_to > valid_from");
                        });
                });

            modelBuilder.Entity("CoreIns.Modules.Policy.Persistence.JobRow", b =>
                {
                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<Guid?>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<string>("ArtefactHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("artefact_hash");

                    b.Property<Guid?>("BoundTransactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("bound_transaction_id");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("channel");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("char(3)")
                        .HasColumnName("currency");

                    b.Property<int>("CurrentVersionNo")
                        .HasColumnType("integer")
                        .HasColumnName("current_version_no");

                    b.Property<Guid?>("DeclineId")
                        .HasColumnType("uuid")
                        .HasColumnName("decline_id");

                    b.Property<DateTime>("EffectiveAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("effective_at");

                    b.Property<DateTime>("ExpirationAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("expiration_at");

                    b.Property<string>("JobNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("job_number");

                    b.Property<string>("JobType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("job_type");

                    b.Property<string>("Jurisdiction")
                        .IsRequired()
                        .HasColumnType("char(2)")
                        .HasColumnName("jurisdiction");

                    b.Property<Guid>("LegalEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("legal_entity_id");

                    b.PrimitiveCollection<List<string>>("Participants")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text[]")
                        .HasColumnName("participants")
                        .HasDefaultValueSql("'{}'::text[]");

                    b.Property<Guid>("PolicyId")
                        .HasColumnType("uuid")
                        .HasColumnName("policy_id");

                    b.Property<Guid>("PolicyholderPartyId")
                        .HasColumnType("uuid")
                        .HasColumnName("policyholder_party_id");

                    b.Property<string>("ProducerCode")
                        .HasColumnType("text")
                        .HasColumnName("producer_code");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("product_code");

                    b.Property<string>("ProductVersion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("product_version");

                    b.Property<string>("QuoteType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("quote_type");

                    b.Property<string>("RatingArtefactHash")
                        .HasColumnType("text")
                        .HasColumnName("rating_artefact_hash");

                    b.Property<int>("RecordVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("record_version");

                    b.Property<bool>("Referred")
                        .HasColumnType("boolean")
                        .HasColumnName("referred");

                    b.Property<string>("ResolutionHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("resolution_hash");

                    b.Property<string>("ResolutionManifest")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("resolution_manifest");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("JobId")
                        .HasName("pk_job");

                    b.HasIndex("PolicyId")
                        .HasDatabaseName("ix_job_policy");

                    b.HasIndex("LegalEntityId", "JobNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_job_number");

                    b.HasIndex("LegalEntityId", "PolicyholderPartyId")
                        .HasDatabaseName("ix_job_policyholder");

                    b.ToTable("job", "pol", t =>
                        {
                            t.HasCheckConstraint("ck_job_currency", "currency ~ '^[A-Z]{3}$'");

                            t.HasCheckConstraint("ck_job_jurisdiction", "jurisdiction ~ '^[A-Z]{2}$'");

                            t.HasCheckConstraint("ck_job_period", "expiration_at > effective_at");

                            t.HasCheckConstraint("ck_job_quote_type", "quote_type IN ('QUICK', 'FULL')");

                            t.HasCheckConstraint("ck_job_record_version", "record_version >= 1");

                            t.HasCheckConstraint("ck_job_state", "state IN ('DRAFT', 'QUOTED', 'BOUND', 'SCHEDULED', 'RESCINDED', 'WITHDRAWN', 'DECLINED', 'NOT_TAKEN', 'EXPIRED')");

                            t.HasCheckConstraint("ck_job_type", "job_type IN ('SUBMISSION')");
                        });
                });

            modelBuilder.Entity("CoreIns.Modules.Policy.Persistence.PolicyRow", b =>
                {
                    b.Property<Guid>("PolicyId")
                        .HasColumnType("uuid")
                        .HasColumnName("policy_id");

                    b.Property<Guid?>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Jurisdiction")
                        .IsRequired()
                        .HasColumnType("char(2)")
                        .HasColumnName("jurisdiction");

                    b.Property<Guid>("LegalEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("legal_entity_id");

                    b.Property<string>("PolicyNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("policy_number");

                    b.Property<Guid>("PolicyholderPartyId")
                        .HasColumnType("uuid")
                        .HasColumnName("policyholder_party_id");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("product_code");

                    b.Property<int>("RecordVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("record_version");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("recorded_at");

                    b.HasKey("PolicyId")
                        .HasName("pk_policy");

                    b.HasIndex("LegalEntityId", "PolicyNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_policy_number");

                    b.HasIndex("LegalEntityId", "PolicyholderPartyId")
                        .HasDatabaseName("ix_policy_policyholder");

                    b.ToTable("policy", "pol", t =>
                        {
                            t.HasCheckConstraint("ck_policy_jurisdiction", "jurisdiction ~ '^[A-Z]{2}$'");
                        });
                });

            modelBuilder.Entity("CoreIns.Modules.Policy.Persistence.PolicyTermRow", b =>
                {
                    b.Property<Guid>("TermVersionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("term_version_id");

                    b.Property<string>("ArtefactHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("artefact_hash");

                    b.Property<string>("ConfigurationHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("configuration_hash");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("char(3)")
                        .HasColumnName("currency");

                    b.Property<Guid>("HeadTransactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("head_transaction_id");

                    b.Property<Guid>("LegalEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("legal_entity_id");

                    b.Property<string>("PaymentPlanRef")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payment_plan_ref");

                    b.Property<Guid>("PolicyId")
                        .HasColumnType("uuid")
                        .HasColumnName("policy_id");

                    b.Property<string>("ProducerCode")
                        .HasColumnType("text")
                        .HasColumnName("producer_code");

                    b.Property<string>("ProductVersion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("product_version");

                    b.Property<string>("RatingArtefactHash")
                        .HasColumnType("text")
                        .HasColumnName("rating_artefact_hash");

                    b.Property<DateTime>("RecordedFrom")
                        .HasColumnType("timestamptz")
                        .HasColumnName("recorded_from");

                    b.Property<DateTime?>("RecordedTo")
                        .HasColumnType("timestamptz")
                        .HasColumnName("recorded_to");

                    b.Property<string>("ResolutionHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("resolution_hash");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.Property<Guid>("TermId")
                        .HasColumnType("uuid")
                        .HasColumnName("term_id");

                    b.Property<int>("TermNumber")
                        .HasColumnType("integer")
                        .HasColumnName("term_number");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("timestamptz")
                        .HasColumnName("valid_from");

                    b.Property<DateTime>("ValidTo")
                        .HasColumnType("timestamptz")
                        .HasColumnName("valid_to");

                    b.Property<DateOnly>("WrittenDate")
                        .HasColumnType("date")
                        .HasColumnName("written_date");

                    b.HasKey("TermVersionId")
                        .HasName("pk_policy_term");

                    b.HasIndex("TermId")
                        .IsUnique()
                        .HasDatabaseName("ux_policy_term_current")
                        .HasFilter("recorded_to IS NULL");

                    b.HasIndex("PolicyId", "TermNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_policy_term_number")
                        .HasFilter("recorded_to IS NULL");

                    b.ToTable("policy_term", "pol", t =>
                        {
                            t.HasCheckConstraint("ck_policy_term_number", "term_number >= 1");

                            t.HasCheckConstraint("ck_policy_term_recorded", "recorded_to IS NULL OR recorded_to > recorded_from");

                            t.HasCheckConstraint("ck_policy_term_state", "state IN ('SCHEDULED', 'IN_FORCE', 'PENDING_CANCELLATION', 'CANCELLED', 'EXPIRED', 'VOIDED', 'REWRITTEN')");

                            t.HasCheckConstraint("ck_policy_term_valid", "valid_to > valid_from");
                        });
                });

            modelBuilder.Entity("CoreIns.Modules.Policy.Persistence.PolicyTransactionRow", b =>
                {
                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("transaction_id");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("actor");

                    b.Property<string>("ArtefactHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("artefact_hash");

                    b.Property<string>("ConfigurationHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("configuration_hash");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("correlation_id");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("char(3)")
                        .HasColumnName("currency");

                    b.Property<DateTime>("EffectiveAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("effective_at");

                    b.Property<string>("Intent")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("intent");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<Guid>("LegalEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("legal_entity_id");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("origin");

                    b.Property<Guid>("PolicyId")
                        .HasColumnType("uuid")
                        .HasColumnName("policy_id");

                    b.Property<decimal>("Premium")
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("premium");

                    b.Property<string>("RatingArtefactHash")
                        .HasColumnType("text")
                        .HasColumnName("rating_artefact_hash");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("recorded_at");

                    b.Property<string>("ResolutionHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("resolution_hash");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer")
                        .HasColumnName("sequence");

                    b.Property<decimal>("Taxes")
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("taxes");

                    b.Property<Guid>("TermId")
                        .HasColumnType("uuid")
                        .HasColumnName("term_id");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("total");

                    b.Property<string>("WorksheetId")
                        .HasColumnType("text")
                        .HasColumnName("worksheet_id");

                    b.HasKey("TransactionId")
                        .HasName("pk_policy_transaction");

                    b.HasIndex("JobId")
                        .IsUnique()
                        .HasDatabaseName("ux_policy_transaction_job");

                    b.HasIndex("PolicyId", "Sequence")
                        .IsUnique()
                        .HasDatabaseName("ux_policy_transaction_sequence");

                    b.ToTable("policy_transaction", "pol", t =>
                        {
                            t.HasCheckConstraint("ck_policy_transaction_kind", "kind IN ('ISSUANCE', 'CHANGE', 'CANCELLATION', 'REINSTATEMENT', 'REWRITE', 'RENEWAL', 'CARRY_FORWARD', 'SUSPENSION', 'REACTIVATION', 'VOID', 'REVERSAL')");

                            t.HasCheckConstraint("ck_policy_transaction_sequence", "sequence >= 1");

                            t.HasCheckConstraint("ck_policy_transaction_totals", "total = premium + taxes");
                        });
                });

            modelBuilder.Entity("CoreIns.Modules.Policy.Persistence.QuoteVersionRow", b =>
                {
                    b.Property<Guid>("QuoteId")
                        .HasColumnType("uuid")
                        .HasColumnName("quote_id");

                    b.Property<bool?>("Bindable")
                        .HasColumnType("boolean")
                        .HasColumnName("bindable");

                    b.Property<string>("Charges")
                        .HasColumnType("jsonb")
                        .HasColumnName("charges");

                    b.Property<string>("ConfigurationHash")
                        .HasColumnType("text")
                        .HasColumnName("configuration_hash");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<int>("DraftVersion")
                        .HasColumnType("integer")
                        .HasColumnName("draft_version");

                    b.Property<string>("Issues")
                        .HasColumnType("jsonb")
                        .HasColumnName("issues");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<Guid>("LegalEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("legal_entity_id");

                    b.Property<decimal?>("Premium")
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("premium");

                    b.Property<DateTime?>("QuotedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("quoted_at");

                    b.Property<int>("RecordVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("record_version");

                    b.Property<string>("RiskTree")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("risk_tree");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.Property<decimal?>("Taxes")
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("taxes");

                    b.Property<decimal?>("Total")
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("total");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UwEvaluationId")
                        .HasColumnType("uuid")
                        .HasColumnName("uw_evaluation_id");

                    b.Property<DateTime?>("ValidUntil")
                        .HasColumnType("timestamptz")
                        .HasColumnName("valid_until");

                    b.Property<int>("VersionNo")
                        .HasColumnType("integer")
                        .HasColumnName("version_no");

                    b.Property<string>("WorksheetHash")
                        .HasColumnType("text")
                        .HasColumnName("worksheet_hash");

                    b.Property<string>("WorksheetId")
                        .HasColumnType("text")
                        .HasColumnName("worksheet_id");

                    b.HasKey("QuoteId")
                        .HasName("pk_quote_version");

                    b.HasIndex("JobId", "VersionNo")
                        .IsUnique()
                        .HasDatabaseName("ux_quote_version_job_no");

                    b.ToTable("quote_version", "pol", t =>
                        {
                            t.HasCheckConstraint("ck_quote_version_draft", "draft_version >= 0");

                            t.HasCheckConstraint("ck_quote_version_no", "version_no >= 1 AND version_no <= 20");

                            t.HasCheckConstraint("ck_quote_version_quoted", "state <> 'QUOTED' OR (quoted_at IS NOT NULL AND charges IS NOT NULL AND total IS NOT NULL)");

                            t.HasCheckConstraint("ck_quote_version_state", "state IN ('DRAFT', 'QUOTED', 'SUPERSEDED', 'EXPIRED')");
                        });
                });

            modelBuilder.Entity("CoreIns.Modules.Policy.Persistence.SegmentRow", b =>
                {
                    b.Property<Guid>("SegmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("segment_id");

                    b.Property<Guid>("LegalEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("legal_entity_id");

                    b.Property<Guid>("PolicyId")
                        .HasColumnType("uuid")
                        .HasColumnName("policy_id");

                    b.Property<DateTime>("RecordedFrom")
                        .HasColumnType("timestamptz")
                        .HasColumnName("recorded_from");

                    b.Property<DateTime?>("RecordedTo")
                        .HasColumnType("timestamptz")
                        .HasColumnName("recorded_to");

                    b.Property<string>("Snapshot")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("snapshot");

                    b.Property<string>("SnapshotHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("snapshot_hash");

                    b.Property<Guid>("TermId")
                        .HasColumnType("uuid")
                        .HasColumnName("term_id");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("transaction_id");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("timestamptz")
                        .HasColumnName("valid_from");

                    b.Property<DateTime>("ValidTo")
                        .HasColumnType("timestamptz")
                        .HasColumnName("valid_to");

                    b.Property<string>("WorksheetId")
                        .HasColumnType("text")
                        .HasColumnName("worksheet_id");

                    b.HasKey("SegmentId")
                        .HasName("pk_segment");

                    b.HasIndex("TermId")
                        .HasDatabaseName("ix_segment_term");

                    b.HasIndex("TransactionId");

                    b.ToTable("segment", "pol", t =>
                        {
                            t.HasCheckConstraint("ck_segment_recorded", "recorded_to IS NULL OR recorded_to > recorded_from");

                            t.HasCheckConstraint("ck_segment_snapshot_hash", "snapshot_hash ~ '^[0-9a-f]{64}$'");

                            t.HasCheckConstraint("ck_segment_valid", "valid_to > valid_from");
                        });
                });

            modelBuilder.Entity("CoreIns.Modules.Policy.Persistence.ChargeLineRow", b =>
                {
                    b.HasOne("CoreIns.Modules.Policy.Persistence.PolicyTransactionRow", null)
                        .WithMany()
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_charge_line_transaction");
                });

            modelBuilder.Entity("CoreIns.Modules.Policy.Persistence.PolicyTermRow", b =>
                {
                    b.HasOne("CoreIns.Modules.Policy.Persistence.PolicyRow", null)
                        .WithMany()
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_policy_term_policy");
                });

            modelBuilder.Entity("CoreIns.Modules.Policy.Persistence.PolicyTransactionRow", b =>
                {
                    b.HasOne("CoreIns.Modules.Policy.Persistence.PolicyRow", null)
                        .WithMany()
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_policy_transaction_policy");
                });

            modelBuilder.Entity("CoreIns.Modules.Policy.Persistence.QuoteVersionRow", b =>
                {
                    b.HasOne("CoreIns.Modules.Policy.Persistence.JobRow", null)
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_quote_version_job");
                });

            modelBuilder.Entity("CoreIns.Modules.Policy.Persistence.SegmentRow", b =>
                {
                    b.HasOne("CoreIns.Modules.Policy.Persistence.PolicyTransactionRow", null)
                        .WithMany()
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_segment_transaction");
                });
#pragma warning restore 612, 618
        }
    }
}
