using System.Text;

namespace CoreIns.ContractGen;

/// <summary>A C# type: full text (global-qualified) and whether it is a value type.</summary>
/// <param name="Text">Type text, e.g. <c>global::CoreIns.SharedKernel.Money</c>.</param>
/// <param name="IsValueType">True for structs and enums (nullable becomes <c>Nullable&lt;T&gt;</c>).</param>
/// <param name="Converter">Property-level JSON converter type, when the type needs one (decimal strings).</param>
/// <param name="Note">Remark for the property doc (e.g. an untyped id).</param>
internal sealed record TypeRef(string Text, bool IsValueType, string? Converter = null, string? Note = null)
{
    public static TypeRef String { get; } = new("string", false);

    public static TypeRef Bool { get; } = new("bool", true);

    public static TypeRef Int { get; } = new("int", true);

    public static TypeRef Guid { get; } = new("global::System.Guid", true);

    public static TypeRef Json { get; } = new("global::System.Text.Json.JsonElement", true);

    public static TypeRef ListOf(TypeRef item) =>
        item.Converter is not null
            ? throw new InvalidOperationException($"A collection of {item.Text} needs an element converter; not supported.")
            : new($"global::System.Collections.Generic.IReadOnlyList<{item.Text}>", false, null, item.Note);

    public static TypeRef MapOf(TypeRef value) =>
        value.Converter is not null
            ? throw new InvalidOperationException($"A map of {value.Text} needs an element converter; not supported.")
            : new($"global::System.Collections.Generic.IReadOnlyDictionary<string, {value.Text}>", false);
}

/// <summary>One property of a generated record.</summary>
internal sealed class PropDef
{
    public required string JsonName { get; init; }

    public required string Name { get; init; }

    public required TypeRef Type { get; init; }

    /// <summary>In the schema's <c>required</c> list (C# <c>required</c>).</summary>
    public bool Required { get; init; }

    /// <summary>The C# type is nullable (schema allows null, or the member is optional).</summary>
    public bool Nullable { get; init; }

    /// <summary>Omit the member when null (optional and the schema does not allow null).</summary>
    public bool OmitWhenNull { get; init; }

    public string? Doc { get; init; }

    public List<string> Remarks { get; } = [];
}

internal abstract class TypeDef
{
    public required string Name { get; init; }

    public string? Summary { get; init; }

    public List<string> Remarks { get; } = [];
}

/// <summary>A string enum.</summary>
internal sealed class EnumDef : TypeDef
{
    public List<(string Json, string Member)> Members { get; } = [];
}

/// <summary>A sealed record with init properties.</summary>
internal sealed class RecordDef : TypeDef
{
    public List<PropDef> Props { get; } = [];

    public List<TypeDef> Nested { get; } = [];

    /// <summary>Base list after <c>:</c>.</summary>
    public string? Bases { get; set; }

    /// <summary>Extra member lines (already indented one level), emitted before the properties.</summary>
    public List<string> Members { get; } = [];

    /// <summary>Names the scope must not hand out (metadata members, the type's own name).</summary>
    public NameScope Scope { get; init; } = new();
}

/// <summary>Emits C# source text (LF line endings, four-space indents).</summary>
internal sealed class CodeWriter
{
    public const string Header = "// <auto-generated/>\n// Generated by tools/CoreIns.ContractGen from contracts/. Do not edit: change the contract and regenerate.\n#nullable enable\n";

    private readonly StringBuilder _sb = new();
    private int _indent;

    public CodeWriter Line(string text = "")
    {
        if (text.Length == 0)
        {
            _sb.Append('\n');
        }
        else
        {
            _sb.Append(' ', _indent * 4).Append(text).Append('\n');
        }

        return this;
    }

    public CodeWriter Open(string text)
    {
        Line(text);
        Line("{");
        _indent++;
        return this;
    }

    public CodeWriter Close(string suffix = "")
    {
        _indent--;
        return Line("}" + suffix);
    }

    public CodeWriter Doc(string? summary, IEnumerable<string>? remarks = null)
    {
        var s = Names.Xml(summary);
        Line($"/// <summary>{(s.Length == 0 ? "Generated contract member." : s)}</summary>");
        var r = (remarks ?? []).Select(Names.Xml).Where(x => x.Length > 0).ToList();
        if (r.Count > 0)
        {
            Line("/// <remarks>");
            foreach (var x in r)
            {
                Line($"/// <para>{x}</para>");
            }

            Line("/// </remarks>");
        }

        return this;
    }

    public override string ToString() => _sb.ToString();

    public static string File(string ns, Action<CodeWriter> body)
    {
        var w = new CodeWriter();
        w._sb.Append(Header).Append('\n');
        w.Line($"namespace {ns};");
        w.Line();
        body(w);
        return w.ToString();
    }

    public void Type(TypeDef def)
    {
        switch (def)
        {
            case EnumDef e:
                Enum(e);
                break;
            case RecordDef r:
                Record(r);
                break;
        }
    }

    private void Enum(EnumDef e)
    {
        Doc(e.Summary, e.Remarks);
        Line($"[global::System.Text.Json.Serialization.JsonConverter(typeof(global::System.Text.Json.Serialization.JsonStringEnumConverter<{e.Name}>))]");
        Line("[global::System.CodeDom.Compiler.GeneratedCode(\"CoreIns.ContractGen\", \"1.0\")]");
        Open($"public enum {e.Name}");
        foreach (var (json, member) in e.Members)
        {
            Line($"/// <summary><c>{Names.Xml(json)}</c></summary>");
            Line($"[global::System.Text.Json.Serialization.JsonStringEnumMemberName({Names.Literal(json)})]");
            Line($"{member},");
            if ((json, member) != e.Members[^1])
            {
                Line();
            }
        }

        Close();
    }

    private void Record(RecordDef r)
    {
        Doc(r.Summary, r.Remarks);
        Line("[global::System.CodeDom.Compiler.GeneratedCode(\"CoreIns.ContractGen\", \"1.0\")]");
        Open($"public sealed record {r.Name}{(r.Bases is null ? string.Empty : " : " + r.Bases)}");
        var first = true;
        foreach (var m in r.Members)
        {
            if (m.Length == 0)
            {
                Line();
                continue;
            }

            Line(m);
            first = false;
        }

        foreach (var p in r.Props)
        {
            if (!first)
            {
                Line();
            }

            first = false;
            Doc(p.Doc ?? $"Contract member '{p.JsonName}'.", p.Remarks);
            Line($"[global::System.Text.Json.Serialization.JsonPropertyName({Names.Literal(p.JsonName)})]");
            if (p.OmitWhenNull)
            {
                Line("[global::System.Text.Json.Serialization.JsonIgnore(Condition = global::System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]");
            }

            if (p.Type.Converter is { } converter)
            {
                Line($"[global::System.Text.Json.Serialization.JsonConverter(typeof({converter}))]");
            }

            var type = p.Nullable ? p.Type.Text + "?" : p.Type.Text;
            Line($"public {(p.Required ? "required " : string.Empty)}{type} {p.Name} {{ get; init; }}");
        }

        foreach (var nested in r.Nested)
        {
            Line();
            Type(nested);
        }

        Close();
    }
}
