// <auto-generated />
using System;
using CoreIns.Modules.Party.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CoreIns.Modules.Party.Persistence.Migrations
{
    [DbContext(typeof(PartyDbContext))]
    [Migration("20261007164406_InitialParty")]
    partial class InitialParty
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("pty")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CoreIns.Modules.Party.Persistence.IntermediaryRow", b =>
                {
                    b.Property<Guid>("IntermediaryId")
                        .HasColumnType("uuid")
                        .HasColumnName("intermediary_id");

                    b.Property<string>("Chamber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("chamber");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("EvidenceRef")
                        .HasColumnType("text")
                        .HasColumnName("evidence_ref");

                    b.Property<string>("IntermediaryType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("intermediary_type");

                    b.Property<Guid>("LegalEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("legal_entity_id");

                    b.Property<Guid>("PartyId")
                        .HasColumnType("uuid")
                        .HasColumnName("party_id");

                    b.Property<int>("RecordVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("record_version");

                    b.Property<string>("RegisterName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("register_name");

                    b.Property<string>("RegisterNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("register_number");

                    b.Property<string>("RegisterStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("register_status");

                    b.Property<DateTime>("RegisterVerifiedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("register_verified_at");

                    b.Property<string>("RegistrationCategory")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("registration_category");

                    b.Property<DateOnly>("RegistrationDate")
                        .HasColumnType("date")
                        .HasColumnName("registration_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<DateOnly>("ValidFrom")
                        .HasColumnType("date")
                        .HasColumnName("valid_from");

                    b.Property<string>("VerificationLink")
                        .HasColumnType("text")
                        .HasColumnName("verification_link");

                    b.HasKey("IntermediaryId")
                        .HasName("pk_intermediary");

                    b.HasIndex("PartyId");

                    b.HasIndex("LegalEntityId", "PartyId")
                        .IsUnique()
                        .HasDatabaseName("ux_intermediary_party");

                    b.ToTable("intermediary", "pty", t =>
                        {
                            t.HasCheckConstraint("ck_intermediary_record_version", "record_version >= 1");

                            t.HasCheckConstraint("ck_intermediary_register_status", "register_status IN ('ACTIVE', 'SUSPENDED', 'DELETED')");

                            t.HasCheckConstraint("ck_intermediary_status", "status IN ('ONBOARDING', 'ACTIVE', 'SUSPENDED', 'TERMINATED')");
                        });
                });

            modelBuilder.Entity("CoreIns.Modules.Party.Persistence.PartyAddressRow", b =>
                {
                    b.Property<Guid>("AddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("address_id");

                    b.Property<string>("Building")
                        .HasColumnType("text")
                        .HasColumnName("building");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("char(2)")
                        .HasColumnName("country");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Floor")
                        .HasColumnType("text")
                        .HasColumnName("floor");

                    b.PrimitiveCollection<string[]>("FormattedLines")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("formatted_lines");

                    b.PrimitiveCollection<string[]>("FormattedLinesLatin")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("formatted_lines_latin");

                    b.PrimitiveCollection<string[]>("FreeLines")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("free_lines");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean")
                        .HasColumnName("is_primary");

                    b.Property<string>("LatinBuilding")
                        .HasColumnType("text")
                        .HasColumnName("latin_building");

                    b.PrimitiveCollection<string[]>("LatinFreeLines")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("latin_free_lines");

                    b.Property<string>("LatinLocality")
                        .HasColumnType("text")
                        .HasColumnName("latin_locality");

                    b.Property<string>("LatinMunicipality")
                        .HasColumnType("text")
                        .HasColumnName("latin_municipality");

                    b.Property<string>("LatinRegion")
                        .HasColumnType("text")
                        .HasColumnName("latin_region");

                    b.Property<string>("LatinRegionalUnit")
                        .HasColumnType("text")
                        .HasColumnName("latin_regional_unit");

                    b.Property<string>("LatinStreet")
                        .HasColumnType("text")
                        .HasColumnName("latin_street");

                    b.Property<Guid>("LegalEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("legal_entity_id");

                    b.Property<string>("Locality")
                        .HasColumnType("text")
                        .HasColumnName("locality");

                    b.Property<string>("Municipality")
                        .HasColumnType("text")
                        .HasColumnName("municipality");

                    b.Property<string>("Number")
                        .HasColumnType("text")
                        .HasColumnName("number");

                    b.Property<Guid>("PartyId")
                        .HasColumnType("uuid")
                        .HasColumnName("party_id");

                    b.Property<string>("Postcode")
                        .HasColumnType("text")
                        .HasColumnName("postcode");

                    b.Property<DateTime>("RecordedFrom")
                        .HasColumnType("timestamptz")
                        .HasColumnName("recorded_from");

                    b.Property<DateTime?>("RecordedTo")
                        .HasColumnType("timestamptz")
                        .HasColumnName("recorded_to");

                    b.Property<string>("Region")
                        .HasColumnType("text")
                        .HasColumnName("region");

                    b.Property<string>("RegionalUnit")
                        .HasColumnType("text")
                        .HasColumnName("regional_unit");

                    b.Property<string>("RuleSetId")
                        .HasColumnType("text")
                        .HasColumnName("rule_set_id");

                    b.Property<string>("Street")
                        .HasColumnType("text")
                        .HasColumnName("street");

                    b.PrimitiveCollection<string[]>("Types")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("types");

                    b.Property<string>("Unit")
                        .HasColumnType("text")
                        .HasColumnName("unit");

                    b.Property<DateOnly>("ValidFrom")
                        .HasColumnType("date")
                        .HasColumnName("valid_from");

                    b.Property<DateOnly?>("ValidTo")
                        .HasColumnType("date")
                        .HasColumnName("valid_to");

                    b.Property<string>("ValidationState")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("validation_state");

                    b.HasKey("AddressId")
                        .HasName("pk_party_address");

                    b.HasIndex("PartyId")
                        .HasDatabaseName("ix_party_address_party");

                    b.HasIndex("LegalEntityId", "Postcode")
                        .HasDatabaseName("ix_party_address_postcode");

                    b.ToTable("party_address", "pty", t =>
                        {
                            t.HasCheckConstraint("ck_party_address_recorded", "recorded_to IS NULL OR recorded_to > recorded_from");

                            t.HasCheckConstraint("ck_party_address_state", "validation_state IN ('VALIDATED', 'UNVALIDATED', 'INVALID')");

                            t.HasCheckConstraint("ck_party_address_types", "cardinality(types) >= 1");

                            t.HasCheckConstraint("ck_party_address_valid", "valid_to IS NULL OR valid_to > valid_from");
                        });
                });

            modelBuilder.Entity("CoreIns.Modules.Party.Persistence.PartyContactPointRow", b =>
                {
                    b.Property<Guid>("ContactPointId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("contact_point_id");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean")
                        .HasColumnName("is_primary");

                    b.Property<Guid>("LegalEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("legal_entity_id");

                    b.Property<Guid>("PartyId")
                        .HasColumnType("uuid")
                        .HasColumnName("party_id");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("purpose");

                    b.Property<DateTime>("RecordedFrom")
                        .HasColumnType("timestamptz")
                        .HasColumnName("recorded_from");

                    b.Property<DateTime?>("RecordedTo")
                        .HasColumnType("timestamptz")
                        .HasColumnName("recorded_to");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<DateOnly>("ValidFrom")
                        .HasColumnType("date")
                        .HasColumnName("valid_from");

                    b.Property<DateOnly?>("ValidTo")
                        .HasColumnType("date")
                        .HasColumnName("valid_to");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.Property<string>("VerificationStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("verification_status");

                    b.HasKey("ContactPointId")
                        .HasName("pk_party_contact_point");

                    b.HasIndex("PartyId")
                        .HasDatabaseName("ix_party_contact_point_party");

                    b.ToTable("party_contact_point", "pty", t =>
                        {
                            t.HasCheckConstraint("ck_party_contact_point_purpose", "purpose IN ('PERSONAL', 'WORK')");

                            t.HasCheckConstraint("ck_party_contact_point_recorded", "recorded_to IS NULL OR recorded_to > recorded_from");

                            t.HasCheckConstraint("ck_party_contact_point_type", "type IN ('MOBILE', 'LANDLINE', 'WORK_PHONE', 'FAX', 'EMAIL', 'SECURE_INBOX')");

                            t.HasCheckConstraint("ck_party_contact_point_valid", "valid_to IS NULL OR valid_to > valid_from");

                            t.HasCheckConstraint("ck_party_contact_point_verification", "verification_status IN ('UNVERIFIED', 'VERIFIED', 'BOUNCING')");
                        });
                });

            modelBuilder.Entity("CoreIns.Modules.Party.Persistence.PartyIdentifierRow", b =>
                {
                    b.Property<Guid>("IdentifierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("identifier_id");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("DisplaySuffix")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_suffix");

                    b.Property<string>("IssuingCountry")
                        .HasColumnType("char(2)")
                        .HasColumnName("issuing_country");

                    b.Property<Guid>("LegalEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("legal_entity_id");

                    b.Property<Guid>("PartyId")
                        .HasColumnType("uuid")
                        .HasColumnName("party_id");

                    b.Property<DateTime>("RecordedFrom")
                        .HasColumnType("timestamptz")
                        .HasColumnName("recorded_from");

                    b.Property<DateTime?>("RecordedTo")
                        .HasColumnType("timestamptz")
                        .HasColumnName("recorded_to");

                    b.Property<string>("Scheme")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("scheme");

                    b.Property<DateOnly>("ValidFrom")
                        .HasColumnType("date")
                        .HasColumnName("valid_from");

                    b.Property<DateOnly?>("ValidTo")
                        .HasColumnType("date")
                        .HasColumnName("valid_to");

                    b.Property<string>("ValidatorVersion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("validator_version");

                    b.Property<string>("ValueBlindIndex")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value_blind_index");

                    b.Property<byte[]>("ValueEncrypted")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("value_encrypted");

                    b.Property<string>("VerificationSource")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("verification_source");

                    b.Property<string>("VerificationStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("verification_status");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("verified_at");

                    b.HasKey("IdentifierId")
                        .HasName("pk_party_identifier");

                    b.HasIndex("PartyId")
                        .HasDatabaseName("ix_party_identifier_party");

                    b.HasIndex("LegalEntityId", "Scheme", "ValueBlindIndex")
                        .IsUnique()
                        .HasDatabaseName("ux_party_identifier_current")
                        .HasFilter("valid_to IS NULL AND recorded_to IS NULL");

                    b.ToTable("party_identifier", "pty", t =>
                        {
                            t.HasCheckConstraint("ck_party_identifier_blind_index", "value_blind_index ~ '^v[0-9]+:'");

                            t.HasCheckConstraint("ck_party_identifier_recorded", "recorded_to IS NULL OR recorded_to > recorded_from");

                            t.HasCheckConstraint("ck_party_identifier_valid", "valid_to IS NULL OR valid_to > valid_from");

                            t.HasCheckConstraint("ck_party_identifier_verification", "verification_status IN ('SELF_DECLARED', 'DOCUMENT_VERIFIED', 'REGISTRY_VERIFIED', 'VERIFICATION_FAILED', 'EXPIRED')");
                        });
                });

            modelBuilder.Entity("CoreIns.Modules.Party.Persistence.PartyNameRow", b =>
                {
                    b.Property<Guid>("NameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("name_id");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("FamilyName")
                        .HasColumnType("text")
                        .HasColumnName("family_name");

                    b.Property<string>("FatherName")
                        .HasColumnType("text")
                        .HasColumnName("father_name");

                    b.Property<string>("Form")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("form");

                    b.Property<string>("GivenNames")
                        .HasColumnType("text")
                        .HasColumnName("given_names");

                    b.Property<Guid>("LegalEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("legal_entity_id");

                    b.Property<string>("MotherName")
                        .HasColumnType("text")
                        .HasColumnName("mother_name");

                    b.Property<string>("OrganisationName")
                        .HasColumnType("text")
                        .HasColumnName("organisation_name");

                    b.Property<Guid>("PartyId")
                        .HasColumnType("uuid")
                        .HasColumnName("party_id");

                    b.Property<DateTime>("RecordedFrom")
                        .HasColumnType("timestamptz")
                        .HasColumnName("recorded_from");

                    b.Property<DateTime?>("RecordedTo")
                        .HasColumnType("timestamptz")
                        .HasColumnName("recorded_to");

                    b.Property<string>("Script")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("script");

                    b.Property<string>("SourceDocumentRef")
                        .HasColumnType("text")
                        .HasColumnName("source_document_ref");

                    b.Property<string>("TradeName")
                        .HasColumnType("text")
                        .HasColumnName("trade_name");

                    b.Property<string>("TransliteratorVersion")
                        .HasColumnType("text")
                        .HasColumnName("transliterator_version");

                    b.Property<DateOnly>("ValidFrom")
                        .HasColumnType("date")
                        .HasColumnName("valid_from");

                    b.Property<DateOnly?>("ValidTo")
                        .HasColumnType("date")
                        .HasColumnName("valid_to");

                    b.HasKey("NameId")
                        .HasName("pk_party_name");

                    b.HasIndex("PartyId")
                        .HasDatabaseName("ix_party_name_party");

                    b.ToTable("party_name", "pty", t =>
                        {
                            t.HasCheckConstraint("ck_party_name_form", "form IN ('NATIVE', 'LATIN_GENERATED', 'LATIN_AS_ON_DOCUMENT')");

                            t.HasCheckConstraint("ck_party_name_recorded", "recorded_to IS NULL OR recorded_to > recorded_from");

                            t.HasCheckConstraint("ck_party_name_valid", "valid_to IS NULL OR valid_to > valid_from");
                        });
                });

            modelBuilder.Entity("CoreIns.Modules.Party.Persistence.PartyRow", b =>
                {
                    b.Property<Guid>("PartyId")
                        .HasColumnType("uuid")
                        .HasColumnName("party_id");

                    b.Property<byte[]>("BirthDateEncrypted")
                        .HasColumnType("bytea")
                        .HasColumnName("birth_date_encrypted");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Jurisdiction")
                        .IsRequired()
                        .HasColumnType("char(2)")
                        .HasColumnName("jurisdiction");

                    b.Property<Guid>("LegalEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("legal_entity_id");

                    b.Property<string>("PartyNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("party_number");

                    b.Property<string>("PartyType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("party_type");

                    b.Property<string>("PreferredLanguage")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("preferred_language");

                    b.Property<int>("RecordVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("record_version");

                    b.Property<string>("SourceChannel")
                        .HasColumnType("text")
                        .HasColumnName("source_channel");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("PartyId")
                        .HasName("pk_party");

                    b.HasIndex("LegalEntityId", "PartyNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_party_number");

                    b.ToTable("party", "pty", t =>
                        {
                            t.HasCheckConstraint("ck_party_jurisdiction", "jurisdiction ~ '^[A-Z]{2}$'");

                            t.HasCheckConstraint("ck_party_record_version", "record_version >= 1");

                            t.HasCheckConstraint("ck_party_status", "status IN ('PROSPECT', 'ACTIVE', 'INACTIVE', 'DECEASED', 'DISSOLVED', 'MERGED', 'RESTRICTED', 'ANONYMISED')");

                            t.HasCheckConstraint("ck_party_type", "party_type IN ('PERSON', 'ORGANISATION')");
                        });
                });

            modelBuilder.Entity("CoreIns.Modules.Party.Persistence.PartySearchKeyRow", b =>
                {
                    b.Property<long>("KeyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("key_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("KeyId"));

                    b.Property<string>("KeyKind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("key_kind");

                    b.Property<Guid>("LegalEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("legal_entity_id");

                    b.Property<Guid>("NameId")
                        .HasColumnType("uuid")
                        .HasColumnName("name_id");

                    b.Property<Guid>("PartyId")
                        .HasColumnType("uuid")
                        .HasColumnName("party_id");

                    b.Property<DateTime>("RecordedFrom")
                        .HasColumnType("timestamptz")
                        .HasColumnName("recorded_from");

                    b.Property<DateTime?>("RecordedTo")
                        .HasColumnType("timestamptz")
                        .HasColumnName("recorded_to");

                    b.Property<string>("RuleVersion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("rule_version");

                    b.Property<string>("SearchKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("search_key");

                    b.HasKey("KeyId")
                        .HasName("pk_party_search_key");

                    b.HasIndex("PartyId")
                        .HasDatabaseName("ix_party_search_key_party");

                    b.HasIndex("SearchKey")
                        .HasDatabaseName("ix_party_search_key_trgm");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SearchKey"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("SearchKey"), new[] { "gin_trgm_ops" });

                    b.HasIndex("LegalEntityId", "SearchKey")
                        .HasDatabaseName("ix_party_search_key_prefix")
                        .HasFilter("recorded_to IS NULL");

                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("LegalEntityId", "SearchKey"), new[] { "uuid_ops", "text_pattern_ops" });

                    b.ToTable("party_search_key", "pty", t =>
                        {
                            t.HasCheckConstraint("ck_party_search_key_kind", "key_kind IN ('FULL', 'PART')");
                        });
                });

            modelBuilder.Entity("CoreIns.Modules.Party.Persistence.ProducerCodeRow", b =>
                {
                    b.Property<Guid>("ProducerCodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("producer_code_id");

                    b.Property<bool>("BindWithinAuthority")
                        .HasColumnType("boolean")
                        .HasColumnName("bind_within_authority");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<bool>("CollectPremium")
                        .HasColumnType("boolean")
                        .HasColumnName("collect_premium");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<Guid>("IntermediaryId")
                        .HasColumnType("uuid")
                        .HasColumnName("intermediary_id");

                    b.Property<bool>("IssueCoverNotes")
                        .HasColumnType("boolean")
                        .HasColumnName("issue_cover_notes");

                    b.Property<Guid>("LegalEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("legal_entity_id");

                    b.Property<int>("RecordVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("record_version");

                    b.Property<bool>("ServiceOnly")
                        .HasColumnType("boolean")
                        .HasColumnName("service_only");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateOnly>("ValidFrom")
                        .HasColumnType("date")
                        .HasColumnName("valid_from");

                    b.Property<DateOnly?>("ValidTo")
                        .HasColumnType("date")
                        .HasColumnName("valid_to");

                    b.HasKey("ProducerCodeId")
                        .HasName("pk_producer_code");

                    b.HasIndex("IntermediaryId");

                    b.HasIndex("LegalEntityId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ux_producer_code_code");

                    b.ToTable("producer_code", "pty", t =>
                        {
                            t.HasCheckConstraint("ck_producer_code_status", "status IN ('ACTIVE', 'SUSPENDED', 'TERMINATED')");

                            t.HasCheckConstraint("ck_producer_code_validity", "valid_to IS NULL OR valid_to > valid_from");
                        });
                });

            modelBuilder.Entity("CoreIns.Modules.Party.Persistence.IntermediaryRow", b =>
                {
                    b.HasOne("CoreIns.Modules.Party.Persistence.PartyRow", null)
                        .WithMany()
                        .HasForeignKey("PartyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_intermediary_party");
                });

            modelBuilder.Entity("CoreIns.Modules.Party.Persistence.PartyAddressRow", b =>
                {
                    b.HasOne("CoreIns.Modules.Party.Persistence.PartyRow", null)
                        .WithMany()
                        .HasForeignKey("PartyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_party_address_party");
                });

            modelBuilder.Entity("CoreIns.Modules.Party.Persistence.PartyContactPointRow", b =>
                {
                    b.HasOne("CoreIns.Modules.Party.Persistence.PartyRow", null)
                        .WithMany()
                        .HasForeignKey("PartyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_party_contact_point_party");
                });

            modelBuilder.Entity("CoreIns.Modules.Party.Persistence.PartyIdentifierRow", b =>
                {
                    b.HasOne("CoreIns.Modules.Party.Persistence.PartyRow", null)
                        .WithMany()
                        .HasForeignKey("PartyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_party_identifier_party");
                });

            modelBuilder.Entity("CoreIns.Modules.Party.Persistence.PartyNameRow", b =>
                {
                    b.HasOne("CoreIns.Modules.Party.Persistence.PartyRow", null)
                        .WithMany()
                        .HasForeignKey("PartyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_party_name_party");
                });

            modelBuilder.Entity("CoreIns.Modules.Party.Persistence.PartySearchKeyRow", b =>
                {
                    b.HasOne("CoreIns.Modules.Party.Persistence.PartyRow", null)
                        .WithMany()
                        .HasForeignKey("PartyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_party_search_key_party");
                });

            modelBuilder.Entity("CoreIns.Modules.Party.Persistence.ProducerCodeRow", b =>
                {
                    b.HasOne("CoreIns.Modules.Party.Persistence.IntermediaryRow", null)
                        .WithMany()
                        .HasForeignKey("IntermediaryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_producer_code_intermediary");
                });
#pragma warning restore 612, 618
        }
    }
}
